input-output-hk/lace

.github/settings.yml, apps/browser-extension-wallet/CONTRIBUTING.md
Add final refinments to the github settings file.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/28/5134757143/index.html) for [f4fe528a](https://github.com/input-output-hk/lace/pull/22/commits/f4fe528a7d9eeed6ff3b082a422a5169853c3fc6)
=> chore: refine github settings

.github/settings.yml
Make Github settings more permissible
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/154/5178752728/index.html) for [7972c588](https://github.com/input-output-hk/lace/pull/69/commits/7972c588a0ac94f639fa6d1295ec9edbebee23ca)
=> chore: adjust github settings

.github/settings.yml
Relax permissions to allow lace memebers to merge PRs
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/210/5188399999/index.html) for [7aa1219e](https://github.com/input-output-hk/lace/pull/74/commits/7aa1219eca18cb05dc7ab595424b5758471cf150)
=> chore: relax merge restrictions

apps/browser-extension-wallet/src/stores/StoreProvider.tsx, apps/browser-extension-wallet/src/stores/createWalletStore.ts, apps/browser-extension-wallet/src/stores/slices/__tests__/lock-slice.test.ts, apps/browser-extension-wallet/src/stores/slices/__tests__/ui-slice.test.ts, apps/browser-extension-wallet/src/stores/slices/lock-slice.ts, apps/browser-extension-wallet/src/stores/slices/ui-slice.ts, apps/browser-extension-wallet/src/types/local-storage.ts, apps/browser-extension-wallet/src/utils/local-storage.ts, apps/browser-extension-wallet/test/__mocks__/set-env-vars.js
---
- Adds a new `hideBalance` field to the local storage to persist the balance visibility preference
- `getWalletUI` in `ui-slice` gets the value for the balance visibility from storage on load
- `setBalancesVisibility` in `ui-slice` now also saves the visibility state to the store
- Added a listener to update the visibility state on storage change in `ui-slice`
- Hiding/showing the balance from the popup should also do it in all open browser tabs
- Hiding/showing the balance from a browser tab should also do it in all other open browser tabs
- When re-opening the popup or opening/refreshing a tab the visibility state should be the same as the last time 
---
**smokeTests**: ✅ [test …
=> feat(extension): persist balance visibility

.github/settings.yml
Allow squash + merge as PR option for merging to `main` branch
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/262/5197108848/index.html) for [fff92283](https://github.com/input-output-hk/lace/pull/86/commits/fff922832155fbd297270bb5b7f017ec597e9472)
=> chore: allow squash and merge

apps/browser-extension-wallet/manifest.json, apps/browser-extension-wallet/package.json, apps/browser-extension-wallet/src/release-notes/1_2_0.tsx
- Version increment for v1.2.0
- Release notes added
With Lace 1.1.0 installed, upgrade to 1.2.0 and:
- assert release notes are viewable
- assert version is updates in `settings -> about`
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/310/5209282881/index.html) for [7acc266b](https://github.com/input-output-hk/lace/pull/97/commits/7acc266bc25160a448ac486ff23e7745fa5ce782)
=> feat(extension): release v1.2.0

apps/browser-extension-wallet/src/features/delegation/components/DelegationContainer.tsx
---
Add the blockchainProvider as a dependency into the useEffect that triggers the fetching.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/302/5204438587/index.html) for [96ad5beb](https://github.com/input-output-hk/lace/pull/94/commits/96ad5bebbe8a02170015a11826086842cfc9eb88)
=> fix(extension): reflect network change on stake poool page (popup)

apps/browser-extension-wallet/.env.defaults, apps/browser-extension-wallet/src/components/DataCheckContainer/CorruptedData.tsx, apps/browser-extension-wallet/src/components/DataCheckContainer/DataCheckContainer.tsx, apps/browser-extension-wallet/src/components/DataCheckContainer/index.ts, apps/browser-extension-wallet/src/components/MigrationContainer/FailedMigration.tsx, apps/browser-extension-wallet/src/components/MigrationContainer/MigrationContainer.tsx, apps/browser-extension-wallet/src/components/MigrationContainer/__tests__/MigrationContainer.test.tsx, apps/browser-extension-wallet/src/components/ResetDataError/ResetDataError.module.scss, apps/browser-extension-wallet/src/components/ResetDataError/ResetDataError.tsx, apps/browser-extension-wallet/src/components/ResetDataError/index.ts, apps/browser-extension-wallet/src/features/unlock-wallet/components/UnlockWalletContainer.tsx, apps/browser-extension-wallet/src/hooks/__tests__/useDataCheck.test.ts, apps/browser-extension-wallet/src/hooks/useDataCheck.ts, apps/browser-extension-wallet/src/hooks/useWalletManager.ts, apps/browser-extension-wallet/src/lib/translations/en.json, apps/browser-extension-wallet/src/popup.tsx, apps/browser-extension-wallet/src/utils/data-validators.ts, apps/browser-extension-wallet/src/utils/local-storage.ts, apps/browser-extension-wallet/src/utils/mocks/test-helpers.tsx, apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsSecurity.tsx, apps/browser-extension-wallet/src/views/browser-view/index.tsx
---
- Adds a hook and a component to perform data checks on storage
- Shows an error with a CTA to reset the wallet if data is corrupted
- Enable feature in local `.env` file to test
- Load the extension, delete different things from the storage, and reload the extension. Not every case will display the error, only the things needed for the wallet to work such as `lock`, `keyAgentsByChain`, and `keyAgentData`. Some may be re-created with a default like the wallet's name and some may disable features like show recovery passphrase.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/243/5190023316/index.html) for [709b5202](https://github.com/input-output-hk/lace/pull/79/commits/709b520 …
=> feat(extension): add corrupted data checks and error screen

.github/labeler.yml, .github/settings.yml
Update the labels list in `settings.yml` so the settings bot does not remove the `ui-toolkit` label assigned by `labeler.yml` and introduce a new `ci` label and colors.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/332/5220437290/index.html) for [584b8f4e](https://github.com/input-output-hk/lace/pull/106/commits/584b8f4e0885dc35da219639c98a95d91d9ca0a2)
=> ci(all): update labels

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/MetadataInput.module.scss, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/MetadataInput.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/__tests__/MetadataInput.test.tsx
---
Apply proper css stylings.
Check the description in the ticket.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/334/5220481365/index.html) for [90a5cfda](https://github.com/input-output-hk/lace/pull/107/commits/90a5cfdaff18dfccb31c8d1057b5c696274b88d0)
=> fix(extension): make remove option visible for non empty input

apps/browser-extension-wallet/src/views/browser-view/features/assets/components/Assets.tsx
---
Balance stays in a loading state when the wallet has one or more NFTs and no fungible tokens besides ADA.
- Do not take into account NFTs when checking if the user has tokens in `Assets.tsx` component as we are not showing them on this screen
Use a wallet with only NFTs and no other assets than ADA to test.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/345/5223610597/index.html) for [a415f415](https://github.com/input-output-hk/lace/pull/111/commits/a415f415619c0257691b3886f5fd124efa80d0dc)
| Total | 19     | 0      | 0       | 0     | 19    | ✅ …
=> fix(extension): filter out NFTs for `hasTokens` check in Asset list

.github/CODEOWNERS
Update would exclude review from lace-tech-leads for yarn.lock changes
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/399/5267196526/index.html) for [60b93f0e](https://github.com/input-output-hk/lace/pull/125/commits/60b93f0e6d77b451993ad5e0e56264825be3a6cf)
| Total | 13     | 6      | 0       | 0     | 19    | ❌     |
=> chore: update codeowners to not require review from leads for yarn.lock changes

apps/browser-extension-wallet/src/hooks/useInitializeTx.ts, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/types.ts, packages/cardano/src/wallet/index.ts
---
Utilises only building the transaction once with `txBuilder`, and signing only at point of submit
1. Open Lace with restored wallet
2. Click send
3. Use Ada
4. Proceed with sending transaction until the success screen
5. Copy the transaction hash
6. Go to activity section
7. Assert the transaction hash from step 5 matches the one display after the transaction has settled and links to correct cexplorer link
[LW-6991]: https://input-output.atlassian.net/browse/LW-6991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/396/5266923223/index.html) for …
=> fix: transaction builder signing

apps/browser-extension-wallet/src/release-notes/1_1_1.tsx, apps/browser-extension-wallet/src/release-notes/1_2_0.tsx
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/421/5279789225/index.html) for [7d3617d5](https://github.com/input-output-hk/lace/pull/131/commits/7d3617d50f72c0760f86126ee9641ee97c2dcb5d)
| Total | 18     | 1      | 0       | 0     | 19    | ❌     |
=> fix(extension): remove brave support from 1.2.0 release note

apps/browser-extension-wallet/src/utils/__tests__/get-assets-information.test.ts, apps/browser-extension-wallet/src/utils/get-assets-information.ts, packages/cardano/src/wallet/test/mocks/AssetsProviderStub.ts
---
- Replace calls to `assetProvider.getAsset` for each asset and instead call `assetProvider.getAssets` in chunks of 100 assets max in case the assets info wasn't found in the wallet's `assetInfo$`
Asset information should still be displayed properly everywhere, including dapp transactions
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/425/5280751044/index.html) for [7416df86](https://github.com/input-output-hk/lace/pull/116/commits/7416df86d1bb061891a4ee2aa0eea1eb973d53d1)
=> refactor(extension): use get-assets instead of get-asset as fallback

apps/browser-extension-wallet/src/providers/ThemeProvider/context.tsx, apps/browser-extension-wallet/src/views/browser-view/components/QRInfoWalletDrawer/QRInfoWalletDrawer.tsx, apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingModals/StakingModals.tsx, apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingModals/__tests__/StakingModals.test.tsx
---
pass proper values into the `setDrawerConfig` util.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/482/5312475880/index.html) for [a77f1951](https://github.com/input-output-hk/lace/pull/119/commits/a77f1951ac54d5e18d9bd9d1bc968ff456348be4)
=> fix(extension): add navigation and title into the recieve drawer in the staking flow

packages/staking/src/features/store/index.ts, packages/staking/src/features/store/stakingStore.ts, packages/staking/src/features/store/types.ts
---
Staking store added to the staking package
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/566/5339607524/index.html) for [1b777fa6](https://github.com/input-output-hk/lace/pull/163/commits/1b777fa682fde559416ea8032b3e108d6a536d0f)
=> feat(staking): add zustand store

packages/ui/README.md
We are missing information about how to structure storybook or file naming convention.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/532/5324084393/index.html) for [098c9beb](https://github.com/input-output-hk/lace/pull/152/commits/098c9beb3859fcb5cb498d19e4412605e344a349)
=> chore(ui): add existing convention to README.md

apps/browser-extension-wallet/src/lib/translations/en.json, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx, packages/core/src/ui/components/WalletSetup/WalletSetupMnemonicVerificationStep.tsx, packages/core/src/ui/components/WalletSetup/__tests__/WalletSetupMnemonicVerificationStep.test.tsx
---
Add missing description into the file with all the translations.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/365/5252048019/index.html) for [7433d618](https://github.com/input-output-hk/lace/pull/118/commits/7433d61855d0a58b9898225d50d79c21ee3a9944)
=> fix(extension): add description into the setup mnemonics for recovery flow

apps/browser-extension-wallet/src/features/dapp/components/ConfirmData.tsx, apps/browser-extension-wallet/src/features/dapp/components/ConfirmTransaction.tsx, packages/core/src/ui/components/DappTransaction/DappTransaction.module.scss
---
- Reduce calculations already handled within the wallet
- Filter external assets only if part of change output returned to wallet
Follow guidance in linked ticket
[LW-7134]: https://input-output.atlassian.net/browse/LW-7134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/582/5346328675/index.html) for [e136776a](https://github.com/input-output-hk/lace/pull/166/commits/e136776a4f36c5335f1c1c5ce1127c8169b45755)
| Total | 36     | 0      | 0       | 0     | 36 …
=> fix(extension): enable cip30 minting transaction signing

apps/browser-extension-wallet/src/styles/constants/breakpoints.ts, packages/common/src/ui/styles/theme.scss
---
Adds 1px to `breakpoint-small`
[LW-7115]: https://input-output.atlassian.net/browse/LW-7115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/590/5349615377/index.html) for [a5fed4da](https://github.com/input-output-hk/lace/pull/169/commits/a5fed4da63c0d36d13ddc7ee37e871f51d6d6323)
=> fix(extension): change small breakpoint size

.github/settings.yml
o Disable merge
o Enable rebase merge
o Allow lace-tech-leads to bypass reviews and checks
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/681/5404318659/index.html) for [73865c98](https://github.com/input-output-hk/lace/pull/195/commits/73865c98595bfa370bba82611827cf5d1a8d8ce6)
=> Chore: adjust main branch merge settings

packages/cardano/src/wallet/util/__tests__/stake-pool-transformer.test.ts, packages/cardano/src/wallet/util/stake-pool-transformer.ts, packages/staking/src/features/browse-pools/BrowsePools.tsx, packages/staking/src/features/browse-pools/search/Search.tsx, packages/staking/src/features/browse-pools/stake-pools-table/StakePoolsTable.tsx, packages/staking/src/features/i18n/translations/en.ts, packages/staking/src/features/i18n/types.ts
---
Add mocked search and filtering (temporary limitation).
1. Open Staking
2. Go to the Browse Pools tab
3. Search or Sort the Pools
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/700/5414784905/index.html) for [6f3cb083](https://github.com/input-output-hk/lace/pull/197/commits/6f3cb083a5e26321d057d5ed2b911a46717886c9)
| Total | 33     | 3      | 0       | 0     | 36    | ❌     |
=> feat(staking): add search and sort for stake pools browser

packages/core/src/ui/assets/icons/missing.component.svg, packages/core/src/ui/components/WalletAddresses/WalletAddressItem.module.scss, packages/core/src/ui/components/WalletAddresses/WalletAddressItem.tsx, packages/core/src/ui/components/WalletAddresses/__tests__/WalletAddressItem.test.tsx, packages/core/src/ui/lib/translations/en.json
---
Add an optional proptype to `WalletAddress` so that we can display a warning when an address has changed. 
Running the tests. 
Also, by going to the address book and setting the prop `isWarningVisible` to true/false. 
[LW-7304]: https://input-output.atlassian.net/browse/LW-7304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/719/5422813261/index.html) for [ceeed2b3](https://github.com/input-output-hk/lace/pull/202/commits/ceeed2b3430d8cf7d294dff7ceb18cbad6b83030)
|-------|--------|--------|---------|-------|-------|-------- …
=> feat(core): adds warning icon to wallet address item

apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/events.ts, apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetup.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
---
This PR adds tracking for the create wallet and restore onboarding PostHog events
[LW-7199]: https://input-output.atlassian.net/browse/LW-7199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LW-7201]: https://input-output.atlassian.net/browse/LW-7201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Implements Lace onboarding new wallet and restore events in PostHog

apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/events.ts, apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetup.tsx
---
This PR adds tracking for the hardware wallet onboarding PostHog events
[LW-7200]: https://input-output.atlassian.net/browse/LW-7200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/774/5447733466/index.html) for [a9a084af](https://github.com/input-output-hk/lace/pull/212/commits/a9a084afcb3874ba63169b00c4814ae4c20b16b9)
| Total | 29     | 7      | 0       | 0     | 36    | ❌     |
=> Implements hardware wallet post hog events

apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/events.ts, apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts, apps/browser-extension-wallet/src/providers/AnalyticsProvider/context.tsx, apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.ts, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetup.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
---
This PR adds tracking for the following PostHog events:
- wallet | change active page | view
- onboarding | new wallet | all done | go to my wallet | click
- onboarding | hardware wallet | all done | go to my wallet | click
- onboarding | restore wallet | all done | go to my wallet | click
You need access to our PostHog service and go through the steps required to trigger those events + check them in PostHog
=> feat(extension) add onboarding events to PostHog

packages/staking/.ladle/vite.config.ts
---
Enable ladle build with eslint errors. Ladle is used only for development purposes and our pipelines still won't allow merging PRs with ESLint errors.
=> chore(staking): enable ladle build with eslint errors

packages/core/src/ui/components/WalletAddresses/WalletAddressItem.module.scss
---
Resolves long address name issue on popup address book
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/887/5509456340/index.html) for [18ab7fd4](https://github.com/input-output-hk/lace/pull/243/commits/18ab7fd4767657286e27b45e1f4294d795116215)
=> fix: long address name overflow on popup address book

apps/browser-extension-wallet/src/features/nfts/components/NftDetail.tsx, apps/browser-extension-wallet/src/features/nfts/components/Nfts.tsx, apps/browser-extension-wallet/src/hooks/__tests__/useAssetInfo.test.ts, apps/browser-extension-wallet/src/hooks/index.ts, apps/browser-extension-wallet/src/hooks/useAssetInfo.ts, apps/browser-extension-wallet/src/utils/__tests__/get-asset-image.test.ts, apps/browser-extension-wallet/src/utils/get-asset-image.ts, apps/browser-extension-wallet/src/utils/get-token-list.ts, apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/CreateFolder/AssetPicker.tsx, apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/CreateFolder/NftsList.tsx, apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/NftsLayout.tsx, apps/browser-extension-wallet/src/views/browser-view/features/nfts/selectors.ts, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/AssetPicker.tsx
---
This PR adds handle information to assets so the personalized image can be used where nfts image are displayed.
- NFT screen
- NFT folder screen
- NFT detail screen
- Send screen asset picker
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/850/5486098721/index.html) for [10e3a214](https://github.com/input-output-hk/lace/pull/234/commits/10e3a21472a7589e5d4cf4b27e89ddc03689cabc)
| Total | 36     | 0      | 0 …
=> [LW-7324] Personalized ADA Handle in NFT screen

apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx, apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressDetailDrawer.tsx, apps/browser-extension-wallet/src/features/address-book/context/AddressBookProvider.tsx, apps/browser-extension-wallet/src/features/address-book/context/__test__/context.test.tsx, apps/browser-extension-wallet/src/features/address-book/context/context.ts, apps/browser-extension-wallet/src/features/address-book/hooks/__tests__/useGetFilteredAddressBook.test.tsx, apps/browser-extension-wallet/src/lib/storage/__tests__/address-book.test.ts, apps/browser-extension-wallet/src/lib/storage/__tests__/database.test.ts, apps/browser-extension-wallet/src/lib/storage/models/address-book.ts, apps/browser-extension-wallet/src/utils/validators/__tests__/address-book.test.ts, apps/browser-extension-wallet/src/utils/validators/address-book.ts, apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressBook/AddressBook.tsx, apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/AddressForm.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/AddressForm.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/AddressList.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/AddressFormFooter.tsx, packages/core/src/ui/components/WalletAddresses/WalletAddressItem.tsx
---
Adds `HandleResolution` to the `AddressBookContext` so that later on we can save and compare both values for a validation on the client side. 
- Run the app make sure ADA Handle works without any regression.
- Address book renders 
- Profile renders and they both render the address and the handle. 
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/858/5487037446/index.html) for [b81d60a3](https://github.com/input-output-hk/lace/pull/235/commits/b81d60a385606e54c1803abcf4ded26a959b9974)
| …
=> feat: persists HandleResolution to addressBookContext

apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx, packages/core/src/ui/components/WalletSetup/WalletSetupMnemonicVerificationStep.tsx, packages/core/src/ui/components/WalletSetup/__tests__/WalletSetupMnemonicVerificationStep.test.tsx
---
This PR fixes two separate issues:
1. Fixes a bug in the extension on-boarding flow outlined in https://input-output.atlassian.net/browse/LW-6141
2. Enable different mnemonic length selection for desktop on-boarding flow (to make it work like in the extension) 
1. follow the steps outlined in https://input-output.atlassian.net/browse/LW-6141 and you should see the expected result of seeing the first page of mnemonic input
2. Try restoring a wallet with 12/15 mnemonics on desktop app
https://user-images.githubusercontent.com/172414/236194207-85a3a192-d98a-422b-8490-d77c7a383725.mp4
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/912/5521455919/index.html) for …
=> fix(extension): onboarding bug with mnemonics

packages/staking/.eslintrc.cjs, packages/staking/package.json, packages/staking/src/features/drawer/StakePoolConfirmation.module.scss, packages/staking/src/features/drawer/StakePoolConfirmation.tsx, packages/staking/src/features/drawer/StakePoolDetail.tsx, packages/staking/src/features/outside-handles-provider/types.ts, packages/staking/src/features/staking/PortfolioBar.tsx, packages/staking/src/features/store/types.ts
---
Add support for displaying multiple stake pools in the confirmation step.
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/942/5530072710/index.html) for [be112d35](https://github.com/input-output-hk/lace/pull/256/commits/be112d35b34a15d37f3902148a13a4bb94738767)
=> feat(staking): handle multiple stake pools on staking confirmation drawer

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/HeaderView.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionLayout.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendWarningModal.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/store/uiStore.ts, apps/browser-extension-wallet/src/views/browser-view/stores/sections-store.ts
---
Resets the section store on drawer close.
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/928/5524199407/index.html) for [e27d0a38](https://github.com/input-output-hk/lace/pull/253/commits/e27d0a38266ae2efede28200b6842cec5eaa1c4a)
| Total | 30     | 6      | 0       | 0     | 36    | ❌     |
=> [LW-7422] Transaction confirmation screen is not purged

.github/workflows/e2e-tests-linux.yml, .github/workflows/e2e-tests-win.yml
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/982/5552989810/index.html) for [092edfa2](https://github.com/input-output-hk/lace/pull/271/commits/092edfa208a799fe1e8aba9c12b84614400c8c58)
=> test(extension): e2e - fix workflow when running multiple tags

apps/browser-extension-wallet/src/lib/translations/en.json, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx, packages/core/src/ui/components/WalletSetup/WalletSetupSelectAccountsStep.module.scss
---
This PR changes the copy for **Connect hardware wallet** and **Select Account** steps in onboarding flow.
Also address a small alignment issue with _Use your device to confirm the export of your public key_ text in **Select Account** step.
To be able see the changes on **Connect hardware wallet** step, the `USE_TREZOR_HW` env variable should be set to `true`, otherwise, the previous copy will be visible
For **Select Account** step it is necessary to connect HW to be able to see this step
[LW-6558]: https://input-output.atlassian.net/browse/LW-6558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LW-6557]: https://input-output.atlassian.net/browse/LW-6557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> Change copy for hardware wallet setup steps

packages/core/src/ui/components/AssetInput/AssetInput.tsx
---
- fire `focus({ cursor: 'end' });` event in case user clicks outside of input but within the clickable area;
- fire `focus({ cursor: 'end' });` event in case user clicks on input but `compactValue` differs from the actual one
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/843/5484473895/index.html) for [c123fdd5](https://github.com/input-output-hk/lace/pull/219/commits/c123fdd57eaf85a7c7eb16152f82b85ce944c2ba)
|       | passed | failed | skipped | flaky | total | result …
=> chore(extension): fix cursor position for unformatted values in coin input

packages/staking/src/features/i18n/translations/en.ts, packages/staking/src/features/i18n/types.ts, packages/staking/src/features/overview/staking-info-card/StakingInfoCard.tsx, packages/staking/src/features/overview/staking-info-card/StatsTooltip.tsx
---
Previous PR adding the saturation and retired indicators introduced a bug causing retired indicators being visible by default. Here this bug is eleminated.
Moreover one missing translation is added
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1053/5596372592/index.html) for [6a49338a](https://github.com/input-output-hk/lace/pull/289/commits/6a49338a8af2f256481981b431d43d80173cb114)
=> fix(staking): prevent retired indicator from being visible by default

.github/workflows/ci.yml, .github/workflows/smoke-tests.yml
I'd like to propose to run continous integration and smoke tests for all PRs, not only those targetting `main`.
Rationale: although it's recommended to avoid creating dependencies between PRs, in rare cases, development teams need to work with stacked PRs. Examples include working with temporary integration branches or while making contributions into someone else's PR. When such a PR is open, several checks are ran against it, but not CI nor smoke tests, which could delay finding problems in code to a point when it's merged to main PR.  
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1075/5602720685/index.html) for [33b2c2f4](https://github.com/input-output-hk/lace/pull/295/commi …
=> chore(all): run CI and smoke tests on all PRs

packages/common/src/ui/components/Drawer/DrawerNavigation.module.scss
---
Drawer title has prop "z-index: -1" which effectively hides it and is nowhere visible.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1113/5654100294/index.html) for [7e0a3e4e](https://github.com/input-output-hk/lace/pull/310/commits/7e0a3e4eb8718897d497dbe477b5d34728de2759)
=> chore(extension): set drawer title visible

apps/browser-extension-wallet/src/release-notes/1_3_1.tsx
Post release cherry-pick 3/3
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1120/5658476171/index.html) for [8c216b02](https://github.com/input-output-hk/lace/pull/314/commits/8c216b02ba0ce722fa912d6033b9fb8bbcd90d88)
=> chore(extension): update release notes for 1.3.1

.github/workflows/e2e-tests-linux.yml
Lace has been using catalyst infra for a while and now we need to migrate everything to our own infra
Created s3/cloudfront/authlambda with identical configuration as our old one and this PR changes upload location
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1171/5678713630/index.html) for [ef8d1674](https://github.com/input-output-hk/lace/pull/318/commits/ef8d16749d430351aa21c5f645720573a1ae5353)
=> ci: update e2e tests upload bucket

apps/browser-extension-wallet/src/api/transformers.ts, apps/browser-extension-wallet/src/features/delegation/stores/createDelegationStore.ts, apps/browser-extension-wallet/src/utils/__tests__/assets-transformers.test.ts, apps/browser-extension-wallet/src/utils/__tests__/format-number.test.ts, apps/browser-extension-wallet/src/utils/__tests__/get-number-unit.test.ts, apps/browser-extension-wallet/src/utils/assets-transformers.ts, apps/browser-extension-wallet/src/utils/constants.ts, apps/browser-extension-wallet/src/utils/format-number.ts, apps/browser-extension-wallet/src/utils/get-number-unit.ts, apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/CoinInput/__tests__/useSelectedCoins.test.ts, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/CoinInput/useSelectedCoins.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/store/store.ts, apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
---
Refactor util functions in `format-number.ts` file:
- Remove redundant code and functions
- Try to simplify over-complicated code
- Improve names and readability
- Try to make the functions less dependent on the UI
- Write more useful test cases
Impacts number formatting (units, commas, dots, decimals).
Everything should be working as it was before, especially the inputs for the send transaction screen.
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1150/5670103686/index.html) for [9124fcf2](https://github.com/input-output-hk/lace/pull/299/commits/9124fcf23c89b9909e960e72f07dc46541c904ab) …
=> chore/LW-7442 - Refactor format number utils

package.json, yarn.lock
---
This PR pins protobufjs version to 7.2.4 to resolve the [security vulnerability](https://security.snyk.io/vuln/SNYK-JS-PROTOBUFJS-5756498). This is a temporary fix, we're awaiting for a proper fix from Trezor team.
n/a
=> fix(all): fix protobufjs security vulnerability

apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts, apps/browser-extension-wallet/src/views/browser-view/components/SendReceiveBox/SendReceiveBox.tsx, apps/browser-extension-wallet/src/views/browser-view/features/assets/components/Assets.tsx, apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx, apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/NftsLayout.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/HeaderView.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/TransactionFail.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/TransactionSuccessView.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/store/store.ts, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/types.ts, apps/browser-extension-wallet/src/views/browser-view/features/settings/components/Collateral/__tests__/CollateralDrawer.test.tsx
---
This PR implements the Post Hog events for the send flow and adds the trigger point property on each event
List of events:
- send | send | click
- send | transaction data | review transaction | click
- send | transaction summary | confirm | click
- send | transaction confirmation | confirm | click
- send | all done | view
- send | all done | view transaction | click
- send | all done | close | click
- send | all done | x | click
- send | something went wrong | view
- send | something went wrong | back | click
- send | something went wrong | cancel | click
- send | something went wrong | x | click	
Go to post hog event explorer section, all send events should have a `trigger_point` property in the property tab,
depending from where the send drawer was opened, the `trigger_point` …
=> Implements Post Hog events for send flow

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/AddressInput.tsx
---
Fixed error thrown by finding a cardano address in an undefined handles array by replacing the address with an empty string
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1292/5749821165/index.html) for [a5f35b0e](https://github.com/input-output-hk/lace/pull/352/commits/a5f35b0ee0394fec3d6b762ed9fa0d006640acd9)
=> fix: error thrown by undefined handles array

packages/staking/package.json, packages/staking/src/features/browse-pools/stake-pools-table/StakePoolItemBrowser/StakePoolItemBrowser.tsx, packages/staking/src/features/drawer/StakePoolConfirmation.tsx, yarn.lock
---
The multi-delegation feature was broken due to a mismatch of SDK packages. Additionally, the StakePoolConfirmation could not create the transaction builder and calculate the fees because of the legacy condition related to single staking (that is now removed).
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1283/5740930842/index.html) for [a91d641e](https://github.com/input-output-hk/lace/pull/347/commits/a91d641e59204f7a0fa98e3a65d504a4e80e9f5e)
=> fix(staking): pool mapping conditions in StakePoolConfirmation and cardano-sdk pkg versions

packages/core/src/ui/components/DestinationAddressInput/DestinationAddressInput.tsx, packages/core/src/ui/components/WalletAddresses/WalletAddressItem.tsx, packages/core/src/ui/components/WalletAddresses/__tests__/WalletAddressList.test.tsx
---
Ellipsis the name of the contact after 12 chars. and at the end. 
Go to the address book, add contacts with less than, equal and longer than 12 char. and make sure that only those with 12 or more char have an ellipsis at the end. 
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1280/5740818217/index.html) for [b8b093ee](https://github.com/input-output-hk/lace/pull/346/commits/b8b093eefcf347aa42801b4a2ddf0e70b062f724)
=> fix: adds correct number fo characters before ellipsis on names

flake.lock, flake.nix, nix/lace-blockchain-services/internal/any-darwin.nix, nix/lace-blockchain-services/internal/common.nix, nix/lace-blockchain-services/internal/lace-blockchain-services/child-cardano-node.go, nix/lace-blockchain-services/internal/lace-blockchain-services/child-mithril.go, nix/lace-blockchain-services/internal/lace-blockchain-services/child-ogmios.go, nix/lace-blockchain-services/internal/lace-blockchain-services/child-provider-server.go, nix/lace-blockchain-services/internal/lace-blockchain-services/child.go, nix/lace-blockchain-services/internal/lace-blockchain-services/go.mod, nix/lace-blockchain-services/internal/lace-blockchain-services/go.sum, nix/lace-blockchain-services/internal/lace-blockchain-services/main.go, nix/lace-blockchain-services/internal/lace-blockchain-services/mainthread/mainthread.go, nix/lace-blockchain-services/internal/lace-blockchain-services/mainthread/mainthread_darwin.m, nix/lace-blockchain-services/internal/lace-blockchain-services/mainthread/mainthread_linux.c, nix/lace-blockchain-services/internal/lace-blockchain-services/mainthread/mainthread_linux.go, nix/lace-blockchain-services/internal/lace-blockchain-services/mainthread/mainthread_windows.c, nix/lace-blockchain-services/internal/lace-blockchain-services/openapi.json, nix/lace-blockchain-services/internal/lace-blockchain-services/setup_systray.go, nix/lace-blockchain-services/internal/lace-blockchain-services/types/types.go, nix/lace-blockchain-services/internal/x86_64-linux.nix, nix/lace-blockchain-services/internal/x86_64-windows.nix
---
Since currently Mithril cannot do incremental sync, we only add a button to force resync from scratch using Mithril
**Note**: it currently only works on Linux and macOS
Windows support is in PR #368
1. Click on this menu item in the system tray area: “**Resync with Mithril**”
2. Wait for the download and verification, watch the status in the tray menu
3. And also watch the status in “**Dashboard**”
4. `cardano-node` will be started automatically after that – wait for it to verify the new `chain` directory and start syncing by itself where Mithril left off
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1109/5647533090/index.html) for …
=> [LW-7659] lace-blockchain-services: integrate Mithril into the UI (triggering fast resync)

apps/browser-extension-wallet/manifest.json, apps/browser-extension-wallet/package.json, apps/browser-extension-wallet/src/release-notes/1_4_0.tsx
This pull request includes the commit made on the release branch to update the version to 1.4.0
[LW-7769]: https://input-output.atlassian.net/browse/LW-7769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1382/5798212343/index.html) for [fe421db7](https://github.com/input-output-hk/lace/pull/371/commits/fe421db7b91d2e6ad3e6f836d2cf8faf2bd3aaad)
=> chore(extension): bump to 1.4.0

nix/lace-blockchain-services/internal/lace-blockchain-services/child-mithril.go, nix/lace-blockchain-services/internal/lace-blockchain-services/setup_systray.go
---
It adds an item in the Mithril status submenu to open the explorer
Click the new item – is the Mithril Explorer opened?
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1305/5751604364/index.html) for [df47ddd5](https://github.com/input-output-hk/lace/pull/351/commits/df47ddd5a5fe2ae63904fd737b16025abff5cc92)
=> [LW-7775] lace-blockchain-services: link to Mithril Explorer

apps/browser-extension-wallet/src/components/MainMenu/MainFooter.tsx, apps/browser-extension-wallet/src/features/nfts/components/Nfts.tsx, apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts, apps/browser-extension-wallet/src/views/browser-view/components/SideMenu/SideMenu.tsx, apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/NftsLayout.tsx
---
This PR implements the following Post Hog events for NFT section: 
- nft | nfts | click
- nft | nfts | nft image | click
[LW-7369]: https://input-output.atlassian.net/browse/LW-7369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1364/5787871507/index.html) for [bd1ca548](https://github.com/input-output-hk/lace/pull/369/commits/bd1ca548538fb75033b1d0ef9e74cb4d900ca306)
| Total | 32     | 4      | 0       | 0     | 36    | ❌     |
=> feat(extension): add analytics actions for nft section

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/AddressForm.tsx
---
The bug was that we weren't awaiting to send the user back until the resolution of the save address in the db. 
Save a handle and make sure that on returning to the original screen, we are showing the name of the saved handle. 
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1395/5807925218/index.html) for [d0a3c50e](https://github.com/input-output-hk/lace/pull/376/commits/d0a3c50ec23c43037c15a352bf198de1f1f3686d)
| Total | 34     | 2      | 0       | 0     | 36    | ❌     |
=> [LW-7784] fixes the reload of the input form after adding a handle to address

apps/browser-extension-wallet/src/features/delegation/components/DelegationContainer.tsx
---
This PR adds missing event for staking section in popup view
- staking | staking | stake pool | click
[LW-7867]: https://input-output.atlassian.net/browse/LW-7867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1402/5808712777/index.html) for [b40ee921](https://github.com/input-output-hk/lace/pull/378/commits/b40ee92131127c0c247656e4b45551987a3462f9)
=> fix(extension): add missing staking events in popup view

nix/lace-blockchain-services/internal/any-darwin.nix, nix/lace-blockchain-services/internal/getlantern-systray--darwin-handle-reopen.patch, nix/lace-blockchain-services/internal/lace-blockchain-services/child-mithril.go, nix/lace-blockchain-services/internal/lace-blockchain-services/child.go, nix/lace-blockchain-services/internal/lace-blockchain-services/child_windows.go, nix/lace-blockchain-services/internal/lace-blockchain-services/main.go, nix/lace-blockchain-services/internal/lace-blockchain-services/ui/foreground_darwin.go, nix/lace-blockchain-services/internal/lace-blockchain-services/ui/foreground_darwin.m, nix/lace-blockchain-services/internal/lace-blockchain-services/ui/foreground_nondarwin.go, nix/lace-blockchain-services/internal/lace-blockchain-services/ui/handle_reopen.go, nix/lace-blockchain-services/internal/lace-blockchain-services/ui/handle_reopen_darwin.go, nix/lace-blockchain-services/internal/lace-blockchain-services/ui/ui.go
Also solves https://input-output.atlassian.net/browse/LW-7468
---
n/a
1. Check that interrupted Mithril downloads are deleted from the state directory (you can interrupt by "Quit" or "Force Restart", or by changing networks etc.)
2. Check there are less logs (debounced – at most 3 per second) when downloading Mithril snapshots
3. Console.app on macOS is not jumping between beginning and end of log during Mithril resync – select "Open Current Log" on macOS and trigger Mithril resync and observe Console.app
4. On macOS, have another app in foreground (Finder, Chrome, Terminal, whatever you wish), and trigger Mithril resync – did the question dialog window get shown on top of your active app?
5. On macOS, we show an alert message when the app was started twice – try to start it twice and …
=> [LW-7842] lace-blockchain-services: Mithril: small tweaks

apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts, apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts, apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.ts, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/__tests__/helpers.test.ts, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/TransactionSuccessView.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/helpers.ts, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/types.ts, apps/browser-extension-wallet/src/views/browser-view/features/settings/components/Collateral/__tests__/CollateralDrawer.test.tsx
---
This PR implements tokens custom property for send flow, where the property has an array of all tokens sent by the user.
The field of each token are:
- Id/Fingerprint
- amount
- Ticker
- Name
Follow the send flow until you reach the success step, a `send | all done | view event` should be on post hog Event Explorer section with the property tokens
[LW-7747]: https://input-output.atlassian.net/browse/LW-7747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1478/5866748675/index.html) for [432e8a92](https://github.com/input-output-hk/lace/pull/394/commits/432e8a92c048bfaab9cf952c7b3be5913a …
=> feat(extension): add custom properties for send flow last step

.github/shared/build/action.yml, .github/workflows/ci.yml, package.json, yarn.lock
---
Revert part of #159 in order to fix the development experience with `yarn watch` command.
Not required.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1561/5925201288/index.html) for [079e63a1](https://github.com/input-output-hk/lace/pull/421/commits/079e63a1e8fb5e406b59b26935dc0b755888b3b8)
=> chore(all): revert the replacement of wsrun with yarn3 workspaces command

.github/shared/build/action.yml, .github/workflows/packages-staking.yml, .github/workflows/smoke-tests.yml
---
With the upgrade to yarn 3 last week, there was a new issue in the CI builds where the error was `error: Error: EEXIST: file already exists, mkdir '/home/runner/work/lace/lace/node_modules/odiff-bin/3'`
This happened because yarn3's install with the immutable flag is more strict, and it so happened in our old github actions [we repeated the same steps of yarn install twice](https://github.com/input-output-hk/lace/blob/main/.github/workflows/smoke-tests.yml#L25-L42) and the old yarn repeated the install unnecessarily.  This removes that unnecessary step.
--- …
=> chore(all): fix yarn 3 upgrade issue in CI

.github/shared/build/action.yml
---
This PR removes the `--immutable-cache` line, which was causing building to fail on the staking GH actions. We don't need this line, because it refers to the caching of the new version of yarn's "plug n play" modules, which we aren't using yet. We are currently still using our own method of caching `node_modules`.
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1612/5943546460/index.html) for [0a95ce2f](https://github.com/input-output-hk/lace/pull/431/commits/0a95ce2fb8d2ad …
=> ci(all): remove --immutable-cache flag (yarn3) [LW-8078]

.github/shared/build/action.yml, .github/workflows/packages-staking.yml
---
Remove `--mode=skip-build` flag from `yarn install` step in CI. Most probably it fails to work due to the `node-gyp` (required by `node-sass`) which builds in postinstall step. This flag was introduced as a fix for `odiff-bin` postinstall build which caused some other problems. Note: `odiff-bin` is a part of the `lost-pixel` package which we used for visual regression in the `staking` package but currently we had to disable it, so it's no longer present in our dependencies.
Not required.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1620/5948909079/index.html) for [15ea1914](https://github.com/input-output-hk/lace/pull/435/commits/15ea19142f21a6cd7fa1eb1aed72aa9bbe5d8a47)
| …
=> chore(all): remove --mode=skip-build during CI install step

apps/browser-extension-wallet/manifest.json, apps/browser-extension-wallet/package.json, apps/browser-extension-wallet/src/release-notes/1_4_1.tsx
This PR update relevant changes from the release 1.4.1
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1653/5952593701/index.html) for [00e69b4e](https://github.com/input-output-hk/lace/pull/439/commits/00e69b4eb6b770c7ddc4c07dbfd5661d93c973e2)
| Total | 33     | 2      | 0       | 0     | 35    | ❌     |
=> chore(extension): bump version to 1.4.1 and added new release notes

apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts, apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.ts, apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/config.ts
---
This PR implements `posthog_project_id` for all Post Hog event. This property contains the ID of each project
Send an event to Post Hog, `posthog_project_id` should be visible in the event property list.
To verify if the project ID is correct, go to the `Project settings` section and look for `Project ID`, this should be the same as the ID in the event.
[LW-8081]: https://input-output.atlassian.net/browse/LW-8081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1732/5999090604/index.html) for [5d13d95e](https://github.com/input-output-hk/lace/pull/432/commits/5d13d95e577a38250775caff05cc …
=> feat(extension): add posthog_project_id property to events

packages/core/src/ui/components/WalletAddresses/WalletAddressItem.module.scss
---
Add `align-content` center for items in popup view to be aligned.
- Open popupview of Address book and add contacts, hover over them, make sure they are centered.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1702/5974374064/index.html) for [d5372d22](https://github.com/input-output-hk/lace/pull/449/commits/d5372d224b9509e315caef9f4b44bf880a2f449f)
=> [LW-8176] align center hovered items in address book

apps/browser-extension-wallet/src/views/browser-view/components/Layout/Layout.module.scss
---
https://github.com/input-output-hk/lace/assets/172414/5b7f4d33-e9b3-4abf-8772-4fd9c6eee4c3
This PR fixes the grid layout by removing `justify-content: center;` which seems to have caused this issue.
- Set up a wallet and start staking to any pool with a very long name (ellipsis must be present on smaller screens)
- Reduce screen size and the "Staking" headline should never be cut-off by the nav bar like in the video above
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1750/6001732186/index.html) for [2afeff6b](https://github.com/input-output-hk/lace/pull/456/commits/2afeff6bde773d39ec75f4d36fb78dc1057a27ef) …
=> fix(extension): nav menu overlap on staking screen LW-7778

apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts, apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.ts
---
This PR removes `url`, `$console_log_recording_enabled_server_side` and `$session_recording_recorder_version_server_side` PostHog properties as outlined in the acceptance criteria.
Perform various tracked interaction with PostHog and make sure properties listed above are no longer captured.
n/a
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1826/6036500830/index.html) for [d6b42de7](https://github.com/input-output-hk/lace/pull/469/commits/d6b42de7f2c302c18ff4dc21238b980bd22c34a1)
=> [LW-8265] Remove unnecesary Posthog properties

packages/staking/src/features/drawer/StakePoolPreferences.tsx
---
Render equal split (preference) on the pie chart in the management drawer.
PieChart should render the correct preference, even if the portfolio has drifted.
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1864/6072553642/index.html) for [1ffed89d](https://github.com/input-output-hk/lace/pull/483/commits/1ffed89d1187adfb96f71d6040437a62e15831a7)
=> feat(staking): show user staking preference on the PieChart (management drawer) [LW-8322]

packages/staking/src/features/overview/Overview.tsx, packages/staking/src/features/overview/OverviewPopup.tsx
---
Ensure that `rewardAccounts` are loaded and available on the Overview page.
Reload the app on the staking screen and ensure it doesn't break.
Before:
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1907/6084320758/index.html) for [b39273f2](https://github.com/input-output-hk/lace/pull/490/commits/b39273f27964077c6ff4f5f112976d9657f8dc93)
| Total | 28     | 7      | 0       | 0     | 35    | ❌     |
=> fix(staking): check rewardAccounts availability on the Overview page [LW-8215]

apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolsTable/StakePoolsTable.modules.scss, packages/common/src/ui/components/Search/Search.module.scss, packages/core/src/ui/components/EditAddressForm/EditAddressForm.module.scss, packages/staking/src/features/browse-pools/stake-pools-table/StakePoolsTable.module.scss
---
- Remove ` margin-right: size_unit(1)` from `:global(.anticon)` in `EditAddressForm.module.scss` as it is already in `AddressDetailDrawer.module.scss`
- `StakePoolsTable.modules.scss` is duplicated in both `browser-extension-wallet` app and `staking` package, but the rules in `.search` were not being applied when doing `<Search className={styles.search}` from the `staking` package. Move those rules to `Search.module.scss` in `common` package instead
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1833/6039061019/index.html) for [44575525](https://github.com/input-output-hk/lace/pull/460/commits/44575525a3cfb2233358b2e1b69c898807d20236)
|       | passed | failed | skipped | …
=> fix/LW-8182 - Alignment Issues

apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolDetails/StakePoolConfirmation.tsx
---
Fix the translation key for the old staking flow:
`browserView.staking.details.confirmation.totalCost.title`
⬇️
`browserView.staking.details.confirmation.transactionCost.title`
Please ensure that the text is rendered properly.
Before:
After:
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1957/6109045932/index.html) for [81cd4b7d](https://github.com/input-output-hk/lace/pull/506/commits/81cd4b7d49e9f82d17e5eda99aed861046e0d79e)
| Total | 29     | 3      | 0       | 0     | 32    | ❌     |
=> fix(staking): fix translation key for the old staking flow (confirmation summary) [LW-8368]

packages/ui/src/design-system/side-drawer/side-drawer-content-header.component.tsx
---
When the back button is not available, Align contents using flexbox
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1923/6089840498/index.html) for [da81ef4d](https://github.com/input-output-hk/lace/pull/497/commits/da81ef4d3d04504deffd4d58dd922604f65c97c1)
| Total | 28     | 7      | 0       | 0     | 35    | ❌     |
=> fix: center align side-drawer header text when back button is absent

apps/browser-extension-wallet/src/utils/validators/address-book.ts
---
We are handling a resolution of `null` from the SDK on handles, as a handle not found. 
Currently test that nothing has changed when validating handles at the time of sending a transaction or adding a handle to the address book. 
In the future, make sure it works when the new TypeOrm starts being used. 
N/A. 
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1956/6108223611/index.html) for [be56e655](https://github.com/input-output-hk/lace/pull/500/commits/be56e655bb67de9b954a71bd68d996e9a3fac3b4)
| Total | 29     | 3      | 0       | 0     | 32    | ❌ …
=> fix: lw-8342 lace takes null for not existent handles

apps/browser-extension-wallet/src/utils/__tests__/format-date.test.ts, apps/browser-extension-wallet/src/utils/format-date.ts
---
As pointed out in https://github.com/input-output-hk/lace/pull/472#discussion_r1314831035 , the `formatDate/Time()` helper, by using the `utc()` method even for local time resulted in the loss of info about the timezone. This is not an issue in the current code which doesn't include the timezone in the format, but might be in the future, so this PR removes the `utc()` transformation when formatting time as local.  
Check that time in transaction details and activity is shown with no changes
These are the screens that were impacted by this change
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1964/6119325675/index.html) for …
=> fix(extension): LW-8325 fix loss of timezone info when formatting time as local

apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts, apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/__tests__/pending-tx-transformer.test.ts, apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/__tests__/tx-history-transformer.test.ts, apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/pending-tx-transformer.ts, apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/tx-history-transformer.ts, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/TransactionSuccessView.tsx, apps/browser-extension-wallet/src/views/browser-view/features/settings/components/Collateral/__tests__/CollateralDrawer.test.tsx, packages/cardano/src/wallet/util/__tests__/unit-converters.test.ts, packages/cardano/src/wallet/util/unit-converters.ts
---
New event properties added on successful transaction.
check single and bundle transaction
---
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2013/6161895849/index.html) for [09231a7c](https://github.com/input-output-hk/lace/pull/514/commits/09231a7c6c113c7b9c0e1479b4b27b5e08a6e53b)
=> feat(extension): new event props on send transact

apps/browser-extension-wallet/.env.defaults, apps/browser-extension-wallet/.env.example
---
This PR disable the Post Hog production tracking in development stage, right now we have it set to true and we are using the production project tokens, so, we might be polluting the production project with incorrect events
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2026/6184611747/index.html) for [780f3130](https://github.com/input-output-hk/lace/pull/532/commits/780f31308df21f9bbb8825cabd7dff0b97b77c1b)
| Total | 31     | 1      | 0       | 0     | 32    | ❌     |
=> chore(extension): disable production mode tracking

.github/workflows/packages-staking.yml, packages/staking/src/features/overview/FundWalletBanner.tsx, packages/staking/src/features/overview/StakeFundsBanner.tsx, packages/staking/src/features/staking/Navigation.tsx
I noticed `main` CI is failing which turned out to be related to the recent eslint fix in CI
https://github.com/input-output-hk/lace/actions/runs/6183121545/job/16784211410
The `console.log` erro got meanwhile fixed, this PR nevertheless addresses the remaining two warnings
Moreover, workflow for `packages/staking` wasn't always executed as expected (can be seen e.g. here: https://github.com/input-output-hk/lace/pull/530), because the `staking` label, automatically added by the labeler job, wasn't present at the moment of the workflow execution, resulting in the workflow being skipped, this PR fixes that as well
run `yarn workspace @lace/staking eslint:check` and verify that there are no errors
---
**smokeTests**: ❌ [test …
=> fix(staking): fix eslint warnings, staking workflow not executing for labeled PRs

.github/workflows/packages-staking.yml
Turns out github workflow for staking wasn't run after opening the PR because the worklow didn't have access to the labels added by the Labeler job only later. This was attempted to be fixed in #465 but turns out that the job could get scheduled and remain unexecuted which blocked the pipeline (see e.g. https://github.com/input-output-hk/lace/pull/535) 
Moreover it turns out that the `actions/labeler` job doesn't trigger the `labeled` action at all, it can be triggered only manually (or through a personal access token), see this issue: https://github.com/actions/labeler/issues/315 . So the PRs wouldn't be properly checked for the first commit where the PR wasn't labeled yet and there doesn't seem to be a reasonable solution to this, if we want to preserve the selective execution of this …
=> ci(all): fix 'Build Staking Center' job filtering, run it always

apps/browser-extension-wallet/src/components/DropdownMenu/DropdownMenu.tsx, apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/DropdownMenuOverlay.tsx, apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/AddressBookLink.tsx, apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/LockWallet.tsx, apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/NetworkInfo.tsx, apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/SettingsLink.tsx, apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/ThemeSwitcher.tsx, apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx, apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts, apps/browser-extension-wallet/src/views/browser-view/features/settings/components/NetworkChoice.tsx, apps/browser-extension-wallet/src/views/browser-view/features/settings/components/NetworkChoiceDrawer.tsx
---
This PR implements events for the user dropdown menu on the top navigation bar
Event list:
- user/wallet profile | profile icon | click
- user/wallet profile | wallet address | click
- user/wallet profile | address book | click
- user/wallet profile | settings | click
- user/wallet profile | light mode | click
- user/wallet profile | dark mode | click
- user/wallet profile | network | click
- user/wallet profile | network | preview | click
- user/wallet profile | network | preprod | click
- user/wallet profile | network | mainnet | click
- user/wallet profile | lock wallet | click
[LW-8371]: https://input-output.atlassian.net/browse/LW-8371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
--- …
=> Implement events for user dropdown menu

packages/staking/src/features/overview/staking-info-card/StakingInfoCard.tsx
hotfixes edge-case with overflowing amounts for larger values
---
The overflowing issue found should really concern only edge-cases with very high fees/margin which seems an unlikely combination for any "serious" pool. The main issue is that the margin ADA amount may in theory be unbounded and as of now there aren't designs to handle that. A possible solution could be showing the amount in a compact format (e.g. 10k ADA), accompanied with a tooltip but this seems to be too much effort considering the unlikelyhood of this scenario in practice.
Another alternative solution proposed in the task description was to remove one of the breakpoints (the smallest one, presumably), but that would result in the staking info section not being aligned with the header which is not ideal either and would …
=> fix(staking): LW-8378 reduce amount of decimals shown in StakingInfoCard

packages/staking/src/features/drawer/StakePoolDetails.tsx, packages/staking/src/features/drawer/preferences/PoolDetailsCard/PoolDetailsCard.tsx, packages/staking/src/features/overview/helpers/isPortfolioDrifted.ts, packages/staking/src/features/store/delegationPortfolioStore/constants.ts, packages/staking/src/features/store/delegationPortfolioStore/selectors.ts, packages/staking/src/features/store/delegationPortfolioStore/stateMachine/atomicStateMutators.ts
---
Until the upcoming release the staking portfolio likely won't be persisted, yet we want to introduce the new "slider" UI for pools which is however incompatible with drift warning/"rebalance" CTA button. Therefore this PR introduces two `TMP_PERSISTENCE_HOTFIX_*` flags that disable these functionalities with minimum changes
* Open staking management drawer and check that "Confirm" button appears as soon as a slider is altered
* check that no drift warning is visible even if the portfolio is drifted (can be achieved e.g. by sending all or most available funds to the "receive" address
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfron …
=> fix(staking): [LW-8510] temporarily disable drift warning/rebalancing until portfolio persistence is done

apps/browser-extension-wallet/.env.defaults, apps/browser-extension-wallet/.env.example, apps/browser-extension-wallet/src/lib/scripts/background/index.ts, apps/browser-extension-wallet/src/lib/scripts/background/onUninstall.ts
---
This PR adds uninstall redirect logic, which can be used to redirect users who uninstall the extension to a configurable URL to give feedback.
1. By default nothing should happen on uninstall (because the environment flag for it is not set by default yet)
2. To enable the feature, set `LACE_EXTENSION_UNINSTALL_REDIRECT_URL=https://lace.io` in your `.env` and check that https://lace.io is opened after uninstalling the Chrome extension. 
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2279/6352714374/index.html) for [0f59ac32](https://github.com/input-output-hk/lace/pull/549/commits/0f59ac32e7c9cfe34622d8c3697ace2e1128d92e)
|       | passed | failed | skipped | flaky | total | …
=> feat(extension): add configurable extension uninstall redirect LW-8535

packages/staking/src/features/drawer/preferences/PoolDetailsCard/PoolDetailsCard.tsx, packages/staking/src/features/drawer/preferences/StepPreferencesContent.tsx, packages/staking/src/features/store/delegationPortfolioStore/stateMachine/processExpandedViewCases.ts
---
As agreed offline, let's initialize the slider values to on-chain current portfolio percentages if managing existing portfolio
Try managing existing portfolio and verify that the initial state of the slider matches on-chain percentages
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2290/6354759147/index.html) for [1d0f47cd](https://github.com/input-output-hk/lace/pull/590/commits/1d0f47cdf2feb3b95ab786408da635ac342c7cd0)
=> feat(staking: [LW-8510] init draft sliders to on chain percentages

packages/staking/src/features/delegation-card/DelegationCard.tsx
discussed on standup
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2347/6403774484/index.html) for [9230cf67](https://github.com/input-output-hk/lace/pull/602/commits/9230cf67c2d1cb4a90eb7974fc3e209a3e399aca)
=> fix(staking): fix floating point errors for Overview screen in DelegationCard

packages/staking/src/features/staking/Setup/Setup.tsx, packages/staking/src/features/store/delegationPortfolioStore/stateMachine/normalizePercentages.ts
---
Apparently sdk percentages not always add up to 100% which turned out to be caused by one of the wallet stake addresses not delegating anywhere. To prevent any such inconsistencies from causing a catastrophic failure (uncaught exception), this PR relaxes the `normalizePercentages` helper to fall back to naive rounding if the percentages happen to not add up to 100%
See screenshots to understand how this change manifests in UI
Test impacted portfolio, check that management drawer/staking overview is properly shown
Screenshot of the bug
After implementing this patch this is how the overview/management drawer look like:
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2363/64112350 …
=> fix(staking): [LW-8714] handle percentages from sdk delegation distribution not adding up to 100%

apps/browser-extension-wallet/src/assets/icons/exclamation-triangle-red.component.svg, apps/browser-extension-wallet/src/lib/translations/en.json, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionSummary.module.scss, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionSummary.tsx
---
This PR implements an information message about Trezor not supporting token decimals on Transaction summary screen, this message will be visible only with Trezor HW.
[LW-8502]: https://input-output.atlassian.net/browse/LW-8502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2377/6423564692/index.html) for [75a90f88](https://github.com/input-output-hk/lace/pull/613/commits/75a90f8829d9451d0627d96b41f92a1353931609)
| Total | 31     | 1      | 0       | 0     | 32 …
=> feat(extension): add warning banner for trezor transaction

apps/browser-extension-wallet/src/lib/translations/en.json, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/ErrorDialog.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx
---
This PR updates the copy of the failed to detect device drawer for Trezor user flow
https://github.com/input-output-hk/lace/assets/65184652/d9003da4-3b0c-4647-a84f-0568808ce180
[LW-8503]: https://input-output.atlassian.net/browse/LW-8503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2401/6435919008/index.html) for [442b4039](https://github.com/input-output-hk/lace/pull/620/commits/442b4039d592036dd8a013952d6514f8d29bcd66)
| Total | 31     | 1      | 0       | …
=> feat(extension): update copy for lock trezor device

apps/browser-extension-wallet/src/features/dapp/components/ConfirmTransaction.tsx, packages/core/src/ui/components/DappTransaction/DappTransaction.tsx
---
Lace performs and incorrect, and redundant check on the wallet balances when verifying DApp transactions.
Remove this check as it’s the responsibility of the DApp to not over-spend. In future we can hook into wallet signing to look for errors and present these in a different flow.
When creating a transaction via a DApp that tries to use more than the balance available. Assert that no warning is shown in Lace, and the transaction can be signed which will later be rejected by the node if submitted.
[LW-8590]: https://input-output.atlassian.net/browse/LW-8590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront …
=> fix(extension): remove insufficient balance check from dapp popup

packages/common/src/ui/components/Drawer/DrawerNavigation.module.scss
---
Remove z-index of -1 from drawer navigation title
[LW-7416]: https://input-output.atlassian.net/browse/LW-7416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2441/6468455769/index.html) for [139a0a4a](https://github.com/input-output-hk/lace/pull/586/commits/139a0a4ab9881e0399f28c8262f184b3b8903cca)
| Total | 27     | 5      | 0       | 0     | 32    | ❌     |
=> fix(common): lw-7416-make drawer navigation title visible

apps/browser-extension-wallet/manifest.json, apps/browser-extension-wallet/package.json, apps/browser-extension-wallet/src/release-notes/1_6_0.tsx
Bump version to 1.6 and add new release notes
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2440/6468415640/index.html) for [45188c9b](https://github.com/input-output-hk/lace/pull/628/commits/45188c9b90cb1b37bb9f2769f1559db4e8d8f7c0)
| Total | 27     | 5      | 0       | 0     | 32    | ❌     |
=> chore(extension): bump version to 1.6 and add new release notes

apps/browser-extension-wallet/src/hooks/useCollateral.ts, apps/browser-extension-wallet/src/views/browser-view/features/settings/components/Collateral/send/CollateralFooterSend.tsx, apps/browser-extension-wallet/src/views/browser-view/features/settings/components/Collateral/send/CollateralStepSend.tsx
---
`submitCollateralTx` in `useCollateral` hook was not throwing when an error, like invalid password, occurred and it was not a hardware wallet
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2493/6484142187/index.html) for [17a20515](https://github.com/input-output-hk/lace/pull/577/commits/17a205159ba2a84444cb702e57cd573d87727102)
=> fix/LW-8337 - Collateral settings wrong password message

apps/browser-extension-wallet/src/views/browser-view/features/settings/components/GeneralSettingsDrawer.tsx
---
This PR removes an extra `settings | your keys | show public key | x | click`
[LW-8769]: https://input-output.atlassian.net/browse/LW-8769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2470/6473526573/index.html) for [eb86b2c6](https://github.com/input-output-hk/lace/pull/633/commits/eb86b2c683c2a70bf74c22568f8bc1efb8c2e378)
| Total | 31     | 1      | 0       | 0     | 32    | ❌     |
=> fix(extension): remove extra close your keys section event

.github/shared/build/action.yml, .github/workflows/ci.yml, apps/browser-extension-wallet/.env.defaults, apps/browser-extension-wallet/.env.example, apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts, apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/config.ts, apps/browser-extension-wallet/test/__mocks__/set-env-vars.js
---
This PR moves the Post Hog api tokens to .env file
[LW-8508]: https://input-output.atlassian.net/browse/LW-8508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2548/6508610469/index.html) for [18eb81bc](https://github.com/input-output-hk/lace/pull/631/commits/18eb81bcc5955e5e5f1a595120ec984838fe3dad)
=> refactor(extension): add posthog api tokens as env variables

packages/common/src/ui/components/Search/Search.module.scss
---
Minor CSS issue.
Go to send screen in popup mode. All input placeholders should be vertically aligned.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2576/6547494451/index.html) for [3e400a52](https://github.com/input-output-hk/lace/pull/649/commits/3e400a5241bd64c22d3f59a5f13d69bd885b5bef)
=> fix(extension): [LW-8498] send input field alignment

apps/browser-extension-wallet/src/lib/scripts/background/config.ts, apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts, apps/browser-extension-wallet/src/lib/scripts/types/userIdService.ts, apps/browser-extension-wallet/src/utils/mocks/test-helpers.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetup.tsx
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2646/6613776362/index.html) for [cd4fd480](https://github.com/input-output-hk/lace/pull/656/commits/cd4fd48037ee5345cf1aa8d8b4eec30bfc377d7c)
| Total | 29     | 3      | 0       | 0     | 32    | ❌     |
=> fix(extension): reset user id service values

packages/ui/src/design-system/index.ts, packages/ui/src/design-system/text-link/index.ts, packages/ui/src/design-system/text-link/text-link.component.tsx, packages/ui/src/design-system/text-link/text-link.css.ts, packages/ui/src/design-system/text-link/text-link.stories.tsx, packages/ui/src/design-tokens/colors.data.ts, packages/ui/src/design-tokens/theme/dark-theme.css.ts, packages/ui/src/design-tokens/theme/light-theme.css.ts
The text link component is required by the voting pop-up screens.
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2611/6578351817/index.html) for [bbf0f70c](https://github.com/input-output-hk/lace/pull/653/commits/bbf0f70cae01bfb1954036782075c8c59231bcf8)
=> feat(ui): text link component

packages/staking/src/features/modals/StakingModal.module.scss
---
Use media query on the popup screen.
- The management and stake pool details drawer distorts on viewport <= 360px because of [this](https://github.com/input-output-hk/lace/blob/85c590bf0cec2633c6eb7918e057aadcc6d04b3f/packages/ui/src/design-tokens/sx.css.ts#L7). When that line is removed everything works.  I don't know if there is value in resolving this since our minimum supported screen size on extended view is 668px.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2523/6499035384/index.html) for …
=> fix(staking): lw-8573 make staking modal buttons responsive

packages/staking/src/features/drawer/StakePoolConfirmation.tsx, packages/staking/src/features/i18n/translations/en.ts, packages/staking/src/features/i18n/types.ts, packages/staking/src/features/modals/PoolsManagementModal.tsx, packages/staking/src/features/modals/index.ts
---
This PR adds a confirmation modal when reducing or adjust pools
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2677/6632862459/index.html) for [8c604029](https://github.com/input-output-hk/lace/pull/652/commits/8c604029eb38e2ce12e7250e3872386029b364c2)
| Total | 29     | 3      | 0       | 0     | 32    | ❌     |
=> feat(staking): lw-7931-add confirmation modal to pool management drawer

packages/staking/src/features/delegation-card/DelegationCard.tsx, packages/staking/src/features/delegation-card/DelegationTooltip.css.ts, packages/staking/src/features/delegation-card/DelegationTooltip.tsx, packages/staking/src/features/delegation-card/types.ts, packages/staking/src/features/drawer/preferences/StepPreferencesContent.tsx, packages/staking/src/features/overview/Overview.tsx, packages/staking/src/features/overview/OverviewPopup.tsx, packages/staking/src/features/theme/colors.ts, packages/ui/src/design-system/index.ts, packages/ui/src/design-system/pie-chart/index.ts, packages/ui/src/design-system/pie-chart/pie-chart.component.tsx, packages/ui/src/design-system/pie-chart/pie-chart.stories.tsx, packages/ui/src/design-system/tooltip/rich-tooltip-content-inner.component.tsx, packages/ui/src/design-tokens/elevation.data.ts
---
Add tooltip to delegation card pie chart
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2394/6432110307/index.html) for [2d50b2e2](https://github.com/input-output-hk/lace/pull/616/commits/2d50b2e2a49b73cb783bf6bb6f538c9a444edcb4)
=> feat(staking): [LW-8684] add tooltip to piechart

apps/browser-extension-wallet/src/features/delegation/components/MultiDelegationStakingPopup.tsx, apps/browser-extension-wallet/src/types/local-storage.ts, apps/browser-extension-wallet/src/utils/constants.ts, apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx, packages/staking/src/features/i18n/translations/en.ts, packages/staking/src/features/i18n/types.ts, packages/staking/src/features/modals/PortfolioPersistenceModal.tsx, packages/staking/src/features/modals/index.ts, packages/staking/src/features/outside-handles-provider/types.ts, packages/staking/src/features/staking/StakingView.tsx
---
Add a one-time announcement modal that shows on the staking view when the user has an active multi-delegation portfolio.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2793/6706378497/index.html) for [19dc1871](https://github.com/input-output-hk/lace/pull/671/commits/19dc187146df27175eef44ee9529840d1299e9d7)
| Total | 31     | 0      | 0       | 0     | 31    | ✅     |
=> feat(staking): [LW-8837] add portfolio persistence one-time message

apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmDRepUpdateContainer.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmTransactionContent.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/utils.ts, apps/browser-extension-wallet/src/lib/translations/en.json, packages/core/src/index.ts, packages/core/src/ui/components/ConfirmDRepUpdate/ConfirmDRepUpdate.stories.ts, packages/core/src/ui/components/ConfirmDRepUpdate/ConfirmDRepUpdate.tsx, packages/core/src/ui/components/ConfirmDRepUpdate/index.ts
---
Add drep update confirmation screen.
|<img width="472" alt="image" src="https://github.com/input-output-hk/lace/assets/11845759/47e20684-38d2-45a6-ad12-ddfd28682dcb">| <img width="472" alt="image" src="https://github.com/input-output-hk/lace/assets/11845759/ea36a3ed-710d-45b6-b14b-aeb9cfba5c54">|
|--|--|
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2721/6657332960/index.html) for [8ead0498](https://github.com/input-output-hk/lace/pull/664/commits/8ead0498fdb626d9dc88ffd5e932f265ac65d084)
|       | passed | failed | skipped | flaky | …
=> feat: drep update

apps/browser-extension-wallet/manifest.json, apps/browser-extension-wallet/package.json, apps/browser-extension-wallet/src/release-notes/1_6_1.tsx
Cherry picked manifest update + release note to merge to `main`
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2810/6730612421/index.html) for [179a57ef](https://github.com/input-output-hk/lace/pull/695/commits/179a57ef039c9b4335159fb5969700af5eea7a06)
| Total | 30     | 1      | 0       | 0     | 31    | ❌     |
=> chore: main branch with 1.6.1 manifest and release note

apps/browser-extension-wallet/src/features/delegation/components/MultiDelegationStakingPopup.tsx, apps/browser-extension-wallet/src/stores/slices/activity-detail-slice.ts, apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx, packages/staking/src/features/activity/Activity.tsx, packages/staking/src/features/activity/NoStakingActivity.css.ts, packages/staking/src/features/activity/NoStakingActivity.tsx, packages/staking/src/features/activity/RewardsHistory.tsx, packages/staking/src/features/activity/helpers/getGroupedRewardsHistory.ts, packages/staking/src/features/i18n/translations/en.ts, packages/staking/src/features/i18n/types.ts, packages/staking/src/features/outside-handles-provider/types.ts, packages/staking/src/features/staking/StakingView.tsx, packages/staking/src/features/theme/colors.ts
---
Add new tab to Staking section called "Activities" and add there the "History" section as shown in designs
This PR also adds the screen for the scenario where the user has no staking activity yet
see figma designs in JIRA issue
Go to `Staking` -> `Activity`, check that the events are properly shown and that correct details appear when you click on an event.
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2753/6672456998/index.html) for [7fea2909](https://github.com/input-output-hk/lace/pull/684/commits/7fea2909444edfff770bec9a71f9e2171f3d5279)
| Total | …
=> feat(staking): [LW-8877] Add activity tab to staking, show rewards list

.github/workflows/smoke-tests.yml
There is an issue with long living branch that smoke test results are not being updated. 
Change method to comment to minimalize chance that someone affect report and it will stop being updated.
=> test(extension): [LW-9004] change smoke test report updatePR method to comment

apps/browser-extension-wallet/src/features/dapp/components/ConfirmData.tsx, apps/browser-extension-wallet/src/features/dapp/components/ConfirmTransaction.tsx, apps/browser-extension-wallet/src/features/dapp/components/DappTransactionFail.tsx, apps/browser-extension-wallet/src/features/dapp/components/DappTransactionSuccess.tsx, apps/browser-extension-wallet/src/features/dapp/components/SignTransaction.tsx, apps/browser-extension-wallet/src/features/dapp/components/__tests__/ConfirmTransaction.test.tsx, apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/HeaderView.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/TransactionFail.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/TransactionSuccessView.tsx
---
Added new property to posthog events to differentiate between normal and dapp transactions.
```
export enum TxCreationType {
Internal = 'internal',
External = 'external'
}
```
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2837/6749131473/index.html) for [a45ea30a](https://github.com/input-output-hk/lace/pull/701/commits/a45ea30ab17551e4d2816d53723e1898921be43b)
| Total | 30     | 1      | 0       | 0     | 31    | ❌     |
=> [LW-8998] Add missing tracking points around dApp connector submission in Lace

apps/browser-extension-wallet/src/hooks/useWalletManager.ts
---
Fix ensuring the order of operations within the `deleteWallet()` matches the original one before #674 as it apparently has impact in case of automation tests which started crashing
Check that automation tests pass. Try also manually removing a wallet and restoring a new one and check that it still works as intended. Check that no additional leftovers are in local/background storage
=> fix(all): [LW-8723] make order of delete operations 1:1 match original code

apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/common-tx-transformer.ts
---
Turns out ticket LW-8912 actually reported two issues and in #696 we fixed only one of them (pending txs being wrongly at the bottom of the activity list). This PR fixes the other issue which got overlooked, namely that delegation transactions without any stake key (de)registrations were incorrectly transformed to empty events
Make a delegation that just changes the pools, without changing their amount and check that the respective tx correctly appears in wallet activity
Before
After
=> fix(staking): [LW-8912] fix delegations with stake key (de)registrations being omitted from activity

packages/staking/src/features/i18n/translations/en.ts, packages/staking/src/features/i18n/types.ts, packages/staking/src/features/overview/StakingNotificationBanners/StakingNotificationBanners.tsx, packages/staking/src/features/overview/StakingNotificationBanners/getCurrentStakingNotifications.ts, packages/staking/src/features/overview/StakingNotificationBanners/types.ts, packages/staking/src/features/overview/types.ts
---
This PR just changes the wording of the message but the main bug reported unfortunately remains, explanation below
When changing the delegation portfolio, the `distribution$` observable is apparently updates as soon as the delegation tx is submitted, not waiting for its confirmation (interestingly, only re-delegations seem to be impacted, not first delegations). This results in the bug reported in the ticket, i.e. that user sees the new portfolio even while the delegation tx is pending.
I made a follow-up ticket LW-9025 to fix the `distribution$` observable in the SDK
I heavily considered making a workaround in the frontend - basically "caching" the old distribution while a delegation transaction is pending but I concluded this can do more harm than good. First, it would "work" only …
=> fix(staking): [LW-8689] change wording/name of pool migration banner

apps/browser-extension-wallet/src/lib/translations/en.json, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransaction.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/HeaderView.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/UnauthorizedTransaction.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/types.ts
- [x ] JIRA - \<link>
- [x ] Screenshots added.
---
Lace now captures and displays an appropriate error when the user rejects the transaction on the Trezor device, or when the approval flow is interrupted on the device side (I.E connection lost).
Caveats:
The Trezor device throws the same 'Authentication failure' error when the device is disconnected or when the transaction is rejected, so there is no way to disambiguate these two events.
Initialize a new lace wallet with a Trezor device. Start a transaction and then:
- Rejects the transaction on the Trezor device.
- Unplug the Trezor device in the middle of the confirmation process.
- Close the Trezor interaction web page before completing the confirmation process.
[![unauth.png](https://i.postimg.cc/X7bghhpT/unauth.png)](https://postimg. …
=> fix(extension): an appropriate error is now shown when a trezor user rejects a transaction

apps/browser-extension-wallet/src/features/dapp/components/ConfirmTransaction.tsx, apps/browser-extension-wallet/src/providers/AnalyticsProvider/context.tsx, apps/browser-extension-wallet/src/providers/AnalyticsProvider/onChain.test.tsx, apps/browser-extension-wallet/src/providers/AnalyticsProvider/onChain.ts, apps/browser-extension-wallet/src/types/local-storage.ts, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx, packages/common/src/analytics/types.ts
---
Added new analytics event "Transaction confirmed".
New local storage property `unconfirmedTransactions` added to store transactions that have been submitted and have not been confirmed yet. Once new `ObservableWallet.transactions.outgoing.onChain$` event is emitted the entry from local storage is removed. 
For the edge case where the user closes the application before the transaction is confirmed, `ObservableWallet.transactions.history$` is used on start up and matched against `unconfirmedTransactions`.
For the edge case where the user has more than one window opened (browser view, popup or dapp connector) the `Lock API` is used to allow only one event to be processed at the same time.
Lock API support: https://caniuse.com/mdn-api_lock
Test submitting transaction from browser view, …
=> [LW-9000] Add confirmed transaction metric

apps/browser-extension-wallet/.env.defaults, apps/browser-extension-wallet/src/features/ada-handle/config.ts, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmVoteDelegationContainer.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/VotingProceduresContainer.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/VotingProceduresContainer.test.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/hooks.ts, apps/browser-extension-wallet/src/lib/translations/en.json, packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
=> chore(extension): resolve pr comments

apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/ConfirmDRepRegistrationContainer.test.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/ConfirmDRepRetirementContainer.test.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/ConfirmDRepUpdateContainer.test.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/ConfirmVoteDelegationContainer.test.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/VotingProceduresContainer.test.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/utils.test.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/utils.ts
Fix the usage of translation keys in components / unit tests.
=> fix(extension): translation keys casing and unit tests

apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsWalletBase.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx, packages/common/src/analytics/types.ts
---
Track three new events:
1. user triggered manual hd wallet re-sync from settings (click on "Sync" button)
2. the manual re-sync triggered above resulted in the discovery of new (hd wallet) addresses 
3. when user in the onboarding flow recovers a wallet/connects hw wallet and a hd wallet is discovered (i.e. at least one address with index > 0)
Note that, as noted in the task description, we are looking for hd addresses, i.e. addresses with index > 0, not the addresses with staking index > 0 used for multidelegation
Enable posthog in env and check that the events outlined above are fired. The easiest way to create an hd wallet and add new hd addresses I know of is to use https://preprod.adalite.io, log in with the Lace mnemonic there and send funds to any of the addresses shown in the …
=> feat(extension): [LW-7417] track manual re-sync and hd wallet discovery

packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolsTable.tsx
---
Not ideal, but the best for now imho:
```
/**
* If there's a search value, filter selected pools if they are in the search results.
* A disadvantage of this approach is that if a current pool is not yet in the search results (it's further down in results),
*   it will not be shown in the list. The confusing part about this is that if the user scrolls down long enough,
*   the pool will appear in the upper selected list.
* Alternative solutions include increasing the search limit / not show selected pools when searching at all,
*   but this seems like the best solution for now.
*/
```
The only consistent solution IMHO would be to hide selected pools upon search, and when adding a pool, re-set the search and show all selected pools. Other solutions, such as increasing search limit from …
=> feat(staking): [LW-8929, LW-8777] apply pool search also to selected pools

apps/browser-extension-wallet/src/api/mock.ts, apps/browser-extension-wallet/src/utils/mocks/test-helpers.tsx, apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolsTable/StakePoolsTable.tsx, packages/cardano/src/wallet/test/mocks/StakepoolSearchProviderStub.ts, packages/cardano/src/wallet/test/mocks/mock.ts, packages/cardano/src/wallet/util/__tests__/stake-pool-transformer.test.ts, packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolsTable.tsx
Reverts input-output-hk/lace#734
Reason: missing updates for the SDK packages results in broken build & tests.
=> Revert "Chore/update for sdk conway era"

packages/core/src/ui/components/ConfirmDRepRegistration/ConfirmDRepRegistration.tsx, packages/core/src/ui/components/ConfirmDRepRetirement/ConfirmDRepRetirement.tsx, packages/core/src/ui/components/ConfirmDRepUpdate/ConfirmDRepUpdate.tsx, packages/core/src/ui/components/ConfirmVoteDelegation/ConfirmVoteDelegation.tsx, packages/ui/src/design-system/transaction-summary/transaction-summary-address.component.tsx, packages/ui/src/design-system/transaction-summary/transaction-summary-metadata.component.tsx
=> test(extension): add test ids for governance actions

apps/browser-extension-wallet/src/features/dapp/components/DappTransactionSuccess.tsx, apps/browser-extension-wallet/src/hooks/useWalletManager.ts
---
We clear the password field after a successful confirmation of a transaction. 
- Try to send a transaction after a successful confirmation without having closed the confirmation screen in dapp connector
=> fix: clears password after successful confirmation

.github/CODEOWNERS
Re-assign `/packages/staking/` and `/packages/ui` to `@input-output-hk/lace-core` as we do not have dedicated squads / teams for those packages any longer.
=> chore: remove lace-ui and lace-staking team from CODEOWNERS

apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingInfo/StakingInfo.tsx, packages/staking/src/features/overview/StakingInfoCard/StakingInfoCard.tsx
---
Remove duplication of currency
With HW and mnemonic, check total staked, total rewards, last reward tooltips for pool overview
[LW-9616]: https://input-output.atlassian.net/browse/LW-9616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(staking): currency tooltip duplication removed

.github/workflows/e2e-tests-linux.yml
Latest chrome version 121 introduced a bug (?) when running multiple tests:
`WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance","source":"javascript","timestamp":1706755040366}
`
This PR downgrades Chrome and chromedriver to version 120. It is a temporary solution and should be removed when problem above is fixed in Chrome.
=> test(extension): e2e - set specific chrome/chromedriver version

packages/core/src/ui/components/ConfirmDRepRegistration/ConfirmDRepRegistration.stories.tsx, packages/core/src/ui/components/ConfirmDRepRetirement/ConfirmDRepRetirement.stories.tsx, packages/core/src/ui/components/ConfirmDRepUpdate/ConfirmDRepUpdate.stories.tsx, packages/core/src/ui/components/ConfirmStakeRegistrationDelegation/ConfirmStakeRegistrationDelegation.stories.tsx, packages/core/src/ui/components/ConfirmStakeVoteDelegation/ConfirmStakeVoteDelegation.stories.tsx, packages/core/src/ui/components/ConfirmStakeVoteRegistrationDelegation/ConfirmStakeVoteRegistrationDelegation.stories.tsx, packages/core/src/ui/components/ConfirmVoteDelegation/ConfirmVoteDelegation.stories.tsx, packages/core/src/ui/components/ConfirmVoteRegistrationDelegation/ConfirmVoteRegistrationDelegation.stories.tsx, packages/core/src/ui/components/ProposalProcedures/HardForkInitiationAction/HardForkInitiationAction.stories.tsx, packages/core/src/ui/components/ProposalProcedures/InfoAction/InfoAction.stories.tsx, packages/core/src/ui/components/ProposalProcedures/NewConstitutionAction/NewConstitutionAction.stories.tsx, packages/core/src/ui/components/ProposalProcedures/NoConfidenceAction/NoConfidenceAction.stories.tsx, packages/core/src/ui/components/ProposalProcedures/ParameterChangeAction/ParameterChangeAction.stories.tsx, packages/core/src/ui/components/ProposalProcedures/TreasuryWithdrawalsAction/TreasuryWithdrawalsAction.stories.tsx, packages/core/src/ui/components/ProposalProcedures/UpdateCommitteeAction/UpdateCommitteeActionAction.stories.tsx, packages/core/src/ui/components/ProposalProcedures/components/Card.tsx, packages/core/src/ui/components/VotingProcedures/VotingProcedures.stories.tsx
---
Resolve some of the errors and structural problems in Sanchonet's Storybook files placed in `packages/core`.
Note: the core fix was done in [f624a9d](https://github.com/input-output-hk/lace/commit/f624a9d2d026780576c507271a14870541b5f863)
Run `packages/core` Storybook and see if all Sanchonet stories are rendered and see the new structure.
=> fix(core): sanchonet-related storybook errors [LW-9721]

apps/browser-extension-wallet/.env.developerpreview
We are migrating clusters for cost and reliability reasons, this change updates URLs to point to the new dev cluster
=> chore: update dev-{preview,preprod} urls

packages/ui/src/design-system/typography/create-text.util.tsx
---
Use `forwardRef` for `createText` utility, used for typography. This removes the errors coming from `radix` when a `<Text.*>` component is wrapped with a `Tooltip` (that uses `asChild`).
Context: [Radix Composition](https://www.radix-ui.com/primitives/docs/guides/composition)
Please double-check typography usage. This should be mostly covered by Chromatic and TypeScript.
There should be no UI changes.
=> feat(ui): handle forward refs for typography components

packages/staking/src/features/activity/PastEpochsRewards/RewardsChartTooltip.tsx
---
Added fallback value `-` for Stake Pools that are missing `metadata` or `metadata.name` field.
Prerequisite: Mnemonics from @ljagiela.
1. Recover the wallet
2. Enter the Staking Activity tab
3. Move your cursor over the bar chart
Before the fix this would crash the app.
After fix:
=> fix(staking): staking activity Tooltip crashes for pools without name [LW-9781]

packages/cardano/src/ui/components/StakePoolSearch/StakePoolSearch.tsx
---
With the introduction of `react-virtuoso` that leverages infinite scroll / lazy loading for Stake Pools, the data shape of Stake Pools in our store has changed from an array containing only fetched Stake Pools to e.g. `[pool, pool, undefined, undefined]` to render the skeletons (placeholders) in place of pools that are about to be fetched.
This PR filters out the `undefined` values from that array and enables correct rendering of Stake Pools Search for HW (old flow).
Note: In future I suggest bringing back the old data shape and modifying the data only in the components that are using `react-virtuoso` to avoid coupling with particular lazy-loading / virtualisation libraries.
Please open the Staking tab in the Popup view using HW.
=> fix(cardano): handle undefined StakePools (caused by react-virtuoso data shape) [LW-9768]

packages/staking/.storybook/__mocks__/cardano.ts, packages/staking/.storybook/main.ts, packages/staking/src/features/DelegationCard/DelegationCard.stories.tsx, packages/staking/src/features/Drawer/preferences/PoolDetailsCard/PoolDetailsCard.stories.tsx
---
Mock the relevant parts of `@lace/cardano` in Staking Storybook.
Please check if all stories are rendered. Previously `DelegationCard` and `PoolDetailsCard` were disabled.
=> chore(staking): mock @lace/cardano for storybook in Staking

.github/workflows/staking-chromatic.yml
Add chromatic workflow for staking package ui elements
=> chore: add staking chromatic

apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx, packages/core/src/ui/components/WalletSetup/WalletSetupWalletNameStep.tsx
---
Use workaround with full app reload when SDK allows to connect Hardware Wallet for the 2nd time.
Follow steps described in the ticket
[LW-8720]: https://input-output.atlassian.net/browse/LW-8720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(extension): reload app on ledger disconnect during onboarding

apps/browser-extension-wallet/src/lib/translations/en.json, apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolsTable/StakePoolsTable.tsx, packages/staking/src/features/BrowsePools/BrowsePools.tsx, packages/staking/src/features/DelegationCard/DelegationTooltip.tsx, packages/staking/src/features/i18n/translations/en.ts, packages/staking/src/features/i18n/types.ts
---
Update translations.
enable USE_ROS_STAKING_COLUMN feature toggle, hove over ROS column to see the updated tooltip.
[LW-9827]: https://input-output.atlassian.net/browse/LW-9827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(extension): add missing ros tooltip for stake pools table

apps/browser-extension-wallet/src/types/local-storage.ts, apps/browser-extension-wallet/src/views/browser-view/components/Layout/Layout.module.scss, apps/browser-extension-wallet/src/views/browser-view/components/Layout/Layout.tsx, apps/browser-extension-wallet/src/views/browser-view/features/dapp/components/DappBetaModal/DappBetaModal.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/PinExtension.module.scss, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
---
move the pin extension notification from the final onboarding step to the main screen
=> feat: move pin extension notification to main screen

apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmTransaction.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/NonRegisteredUserModal/NonRegisteredUserModal.module.scss, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/NonRegisteredUserModal/NonRegisteredUserModal.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/VotingProceduresContainer.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/VotingProceduresContainer.test.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/utils.test.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/hooks.ts, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/utils.ts, apps/browser-extension-wallet/src/lib/translations/en.json
---
Add proper util to calculate if current user is non registered drep.
Add modal.
You'll need to have proper certificates in your tx history (RegisterDelegateRepresentative)
[LW-9202]: https://input-output.atlassian.net/browse/LW-9202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(extension): handle requests from non registered users

packages/core/src/ui/components/Activity/AssetActivityItem.module.scss, packages/core/src/ui/components/Activity/AssetActivityItem.tsx, packages/core/src/ui/components/Activity/__tests__/AssetActivityItem.test.tsx
=> feat(core): LW-9037 add new styling for outgoing txs

apps/browser-extension-wallet/src/lib/scripts/background/config.ts, apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts, apps/browser-extension-wallet/src/lib/scripts/types/userIdService.ts, apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts, apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts, apps/browser-extension-wallet/src/utils/mocks/test-helpers.tsx, apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/MultiWallet.tsx, apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/CreateWallet.test.tsx, apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/NewRecoveryPhrase.tsx, apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/RestoreWallet.test.tsx, apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/steps/RestoreRecoveryPhrase.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx, packages/core/src/ui/components/WalletSetup/WalletSetupMnemonicVerificationStep.tsx, packages/core/src/ui/components/WalletSetup/WalletSetupStepLayout.tsx
---
- Merges posthog users with multiple wallets installed.
- Fixes issues with hardware wallet not aliasing posthog user id due to window reloading
Posthog user aliasing
- Create/restore wallet A in one lace installation
- Create/restore wallet B in another lace installation
- Restore wallet B in wallet A installation with multi wallet feature
- Verify wallet B posthog user is merged with wallet A posthog user
- Repeat step with wallet B being a hardware wallet
Hardware wallet operations immediately after onboarding
- Import hardware wallet with user onboarding
- Immediately test hardware wallet operations (staking, sending, etc...)
=> [LW-9813] Create posthog alias after new wallet is restored

apps/browser-extension-wallet/src/lib/translations/en.json, apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/Setup.tsx, apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/steps/Setup.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetup.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx, packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx, packages/core/src/ui/components/WalletSetup/WalletSetupStepLayout.tsx, packages/core/src/ui/components/WalletSetup/wallet-steps.ts, packages/core/src/ui/components/WalletSetupRevamp/WalletSetupMnemonicStepRevamp/WalletSetupMnemonicStepRevamp.tsx, packages/core/src/ui/components/WalletSetupRevamp/WalletSetupMnemonicStepRevamp/WalletSetupMnemonicVerificationStepRevamp.tsx, packages/core/src/ui/components/WalletSetupRevamp/WalletSetupStepLayoutRevamp.tsx, packages/core/src/ui/lib/translations/en.json
---
This PR moves the register screen after the mnemonic screen on the  create and restore onboarding flow
Follow the normal onboarding flow
=> feat: move the register screen after the mnemonic screen for create and restore flow

.github/workflows/build-dev-preview.yml, .github/workflows/ci.yml, .github/workflows/post-integration.yml, apps/browser-extension-wallet/test/jest.config.js, package.json, packages/cardano/package.json, packages/cardano/test/jest.config.js, packages/common/package.json, packages/common/test/jest.config.js, packages/core/package.json, packages/core/test/jest.config.js, packages/staking/package.json, packages/ui/package.json, yarn.lock
In this PR I'm improving unit test run by:
- updating `ts-jest` from v28.0.7 to v29.1.2
- updating browserslist's db
- fixing local test command for cardano package
=> chore: update ts-jest

apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx, packages/core/src/ui/components/WalletSetupRevamp/WalletSetupMnemonicStepRevamp/WalletSetupMnemonicStepRevamp.tsx
---
On the registration screen, pressing back should take you to the input screen during create wallet
=> feat: handle back from next step in wallet setup step

apps/browser-extension-wallet/src/hooks/useWalletManager.ts, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/helpers.ts, packages/cardano/src/wallet/lib/hardware-wallet.ts
---
In the scope of this task, we are reducing the number of interactions with 3rd party Trezor Connect popup
1. Set feature flag `USE_TREZOR_HW=true`
2. Restore your wallet using a Trezor device ( onboarding flow )
=> chore: LW-9969 make single device connection during Trezor onboarding

apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/DappTransactionContainer.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/DappTransactionContainer.test.tsx, packages/core/src/ui/components/ActivityDetail/TransactionFee.tsx, packages/core/src/ui/components/DappAddressSections/DappAddressSections.module.scss, packages/core/src/ui/components/DappAddressSections/DappAddressSections.tsx, packages/core/src/ui/components/DappTransaction/DappTransaction.module.scss, packages/core/src/ui/components/DappTransaction/DappTransaction.stories.tsx, packages/core/src/ui/components/DappTransaction/DappTransaction.tsx, packages/ui/src/design-system/dapp-transaction-summary/dapp-transaction-assets.component.tsx, packages/ui/src/design-system/dapp-transaction-summary/dapp-transaction-summary.component.tsx, packages/ui/src/design-system/dapp-transaction-summary/dapp-transaction-summary.css.ts, packages/ui/src/design-system/dapp-transaction-summary/dapp-transaction-summary.stories.tsx, packages/ui/src/design-system/transaction-summary/transaction-summary-amount.component.tsx, packages/ui/src/design-system/transaction-summary/transaction-summary.css.ts, packages/ui/src/design-system/transaction-summary/transaction-summary.stories.tsx, packages/ui/src/design-tokens/colors.data.ts, packages/ui/src/design-tokens/theme/dark-theme.css.ts, packages/ui/src/design-tokens/theme/light-theme.css.ts
---
There has been a small style change in the wallet activity to differentiate operations that are negative or positive so users don’t have any doubt about the balance change in their wallet. This task is about bringing the same styling to the dapp bridge.
Try various DApp transactions and check that:
- All positive amounts are rendered in green (without a + sign) - except for collateral which is always displayed in default style
- Items that are not present in the Tx, or with value 0, should not be displayed (collateral, deposit)
- font sizes are unified for all tx summary amounts
=> feat(core, extension): add balance style to the dapp bridge [LW-9887]

.github/shared/build/action.yml, .github/workflows/build-dev-preview.yml, .github/workflows/ci.yml, .github/workflows/core-chromatic.yml, .github/workflows/e2e-tests-linux.yml, .github/workflows/e2e-tests-win.yml, .github/workflows/git-checks.yml, .github/workflows/labeler.yml, .github/workflows/packages-staking.yml, .github/workflows/post-integration.yml, .github/workflows/release.yml, .github/workflows/safari-ci.yml, .github/workflows/smoke-tests.yml, .github/workflows/staking-chromatic.yml, .github/workflows/ui-toolkit-chromatic.yml, apps/browser-extension-wallet/test/jest.config.js, packages/cardano/test/jest.config.js, packages/common/src/.eslintrc.js, packages/common/test/jest.config.js, packages/core/src/.eslintrc.js, packages/core/test/jest.config.js, test/createJestConfig.js
Improve code coverage and clean-up output log for cardano package.
With this change we eliminate from outpu errors like this one :point_down:
```
Failed to collect coverage from /Users/piotrczeglik/Work/PROJECTS/LACE/lace/packages/cardano/src/wallet/util/calculate-deposit-reclaim.ts
ERROR: Invalid file coverage object, missing keys, found:data
STACK: Error: Invalid file coverage object, missing keys, found:data
at assertValidObject (/Users/piotrczeglik/Work/PROJECTS/LACE/lace/node_modules/istanbul-lib-coverage/lib/file-coverage.js:36:15)
at new FileCoverage (/Users/piotrczeglik/Work/PROJECTS/LACE/lace/node_modules/istanbul-lib-coverage/lib/file-coverage.js:78:9)
at CoverageMap.addFileCoverage (/Users/piotrczeglik/Work/PROJECTS/LACE/lace/node_modules/istanbul-lib-coverage/lib/coverage-map.j …
```
=> Github Actions workflow improvements

apps/browser-extension-wallet/package.json, packages/icons/package.json, packages/ui/package.json
Improve post integration action to get rid of test run Fatal Error:
```
<--- Last few GCs --->
[5519:0x5766980]   289914 ms: Scavenge (reduce) 3913.7 (4142.6) -> 3913.2 (4142.6) MB, 6.6 / 0.0 ms  (average mu = 0.207, current mu = 0.220) allocation failure; 
[5519:0x5766980]   289929 ms: Scavenge (reduce) 3913.9 (4142.6) -> 3913.4 (4142.8) MB, 6.5 / 0.0 ms  (average mu = 0.207, current mu = 0.220) allocation failure; 
[5519:0x5766980]   289943 ms: Scavenge (reduce) 3914.2 (4142.8) -> 3913.7 (4143.1) MB, 6.4 / 0.0 ms  (average mu = 0.207, current mu = 0.220) allocation failure; 
<--- JS stacktrace --->
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
1: 0xb6e500 node::Abort() [/opt/hostedtoolcache/node/18.12.1/x64/bin/node]
2: 0xa7e632 …
```
=> chore: improve post integration action

packages/core/src/ui/components/DappAddressSections/DappAddressSections.tsx
---
As a user reviewing a Tx in the dapp bridge,
I want to be able to see and copy the full address of the recipients displayed in the screen,
So I can verify addresses are correct before signing
This PR adds a tooltip over shortened addresses in the from/to section which shows the full address which can be checked and copied.
=> feat(ui): show full address on hover in dapp bridge [LW-100056]

.github/workflows/ci.yml
Remove step from CI which builds lace artifact with all features enabled which is not used anywhere.
With this change we can save 5 minutes per each CI run.
=> Remove build lace artifact with all features enabled

apps/browser-extension-wallet/src/views/browser-view/features/staking/helpers.ts, apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx, packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationFooter.tsx
---
This PR introduces an additional check where we enabled single pool delegation in multi-delegation view. This check will allow users with older Ledger Cardano App and Trezor Firmware ( multi-delegation not supported ) to delegate in a single pool even in multi-delegation view.
Also, this PR fixes HW multi-delegation tx signing.
-  Check if single and multi delegation works when you are using devices with the latest Ledger Cardano App and Trezor Firmware
-  Check if single pool delegation works when you are using devices with older Ledger Cardano App and Trezor Firmware
=> chore: LW-9786 enable single pool delegation in multi-delegation view

packages/core/src/ui/components/WalletSetupRevamp/WalletSetupMnemonicStepRevamp/WalletSetupMnemonicStepRevamp.tsx
---
Check that the entered password matches the created password in the create wallet onboarding flow
=> fix: improve mnemonic check on create flow

apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingContainer.tsx, apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingSkeleton.tsx
---
Do not render `BrowsePoolsPreferencesCard` for hardware wallets (unless multi-delegation staking is enabled for the HW wallet).
`BrowsePoolsPreferencesCard` should not be visible when using HW (unless a feature flag for multi-delegation with HW is enabled).
=> fix(extension): do not render BrowsePoolsPreferencesCard for hardware wallets [LW-10202]

.github/workflows/core-chromatic.yml, .github/workflows/git-checks.yml, .github/workflows/staking-chromatic.yml, .github/workflows/ui-toolkit-chromatic.yml
In this PR I skip Chromatic and Github checks run for draft PRs.
Motivation for this change is to reduce a number of Chromatic runs in CI, which affects our Chromatic monthly limits and speed up pipeline check for drafts.
Credits to @przemyslaw-wlodek for an idea and participation
=> Skip chromatic run for draft PRs

apps/browser-extension-wallet/src/components/Layout/MainLayout.module.scss
---
I'm removing a CSS line, introduced by [PR 833](https://github.com/input-output-hk/lace/pull/883/files)
The issue was that InfiniteScroll doesn't detect scroll event.
I'm not sure if this will break any other screen, so some regression testing is needed.
[LW-10211]: https://input-output.atlassian.net/browse/LW-10211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LW-10212]: https://input-output.atlassian.net/browse/LW-10212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(extension): fix infinite scroll on PopupView

.github/workflows/sonar-cloud.yml
In my past PR I used a wrong pattern for release branch name and after reviewing this workflow it looks it's not needed to track feat, fix, etc branches as the same information we get from PRs in SonarCloud.
=> Update Sonar Cloud workflow configuration

apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmTransaction.module.scss
---
Fixes the width of the Dapp connector action buttons
before:
after:
=> fix(extension): incorrect action button width in dapp connector LW-10232

yarn.lock
---
It seems like we ended up having multiple (apparently not fully compatible) Webpack versions and `yarn dedupe webpack` fixed it.
chromatic step should pass on ci.
=> chore(extension): fix storybook for core package

apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/DappTransactionContainer.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/DappTransactionContainer.test.tsx, apps/browser-extension-wallet/src/lib/translations/en.json, apps/browser-extension-wallet/src/utils/mocks/tx.ts, apps/browser-extension-wallet/src/views/browser-view/features/activity/components/TransactionDetailsProxy.tsx, packages/core/src/ui/components/ActivityDetail/TransactionDetails.module.scss, packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx, packages/core/src/ui/components/ActivityDetail/TransactionInputOutput.tsx, packages/core/src/ui/components/ActivityDetail/__tests__/TransactionDetails.test.tsx, packages/core/src/ui/components/DappAddressSections/DappAddressSections.tsx, packages/core/src/ui/components/DappTransaction/DappTransaction.stories.tsx, packages/core/src/ui/components/DappTransaction/DappTransaction.tsx, packages/core/src/ui/hooks/useTranslate.tsx, packages/core/src/ui/utils/__tests__/render-address-tag.test.ts, packages/core/src/ui/utils/index.ts, packages/core/src/ui/utils/render-address-tag.tsx, packages/core/wallaby.js, packages/ui/src/design-system/address-tags/address-tag.component.tsx, packages/ui/src/design-system/address-tags/address-tag.css.ts, packages/ui/src/design-system/address-tags/address-tags.stories.tsx, packages/ui/src/design-system/address-tags/index.ts, packages/ui/src/design-system/address-tags/types.ts, packages/ui/src/design-system/index.ts, packages/ui/src/design-tokens/colors.data.ts, packages/ui/src/design-tokens/theme/dark-theme.css.ts, packages/ui/src/design-tokens/theme/light-theme.css.ts
---
adds a new `AddressTag` component to the `@lace/ui` toolkit with variants:
- tagging _own_ addresses of the active wallet
- tagging _address book_ contacts (by address) with the contact name
- tagging all other addresses as _foreign_
Integrates the logic + address tag component in DApp tx summary (from/to section) and activity feed details
DApp tx summary:
Tx Activity details:
=> feat(ui): Flag addresses as own or foreign [LW-10061]

apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/DappTransactionContainer.tsx, apps/browser-extension-wallet/src/lib/scripts/background/__tests__/cache-wallets-address.test.ts, apps/browser-extension-wallet/src/lib/scripts/background/cache-wallets-address.ts, apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts, apps/browser-extension-wallet/src/utils/__tests__/get-all-wallets-addresses.test.ts, apps/browser-extension-wallet/src/utils/get-all-wallets-addresses.ts, apps/browser-extension-wallet/src/views/browser-view/features/activity/components/TransactionDetailsProxy.tsx, packages/cardano/src/wallet/lib/cardano-wallet.ts, packages/core/src/ui/components/ActivityDetail/TransactionDetails.stories.tsx, packages/core/src/ui/components/DappAddressSections/DappAddressSections.tsx
---
Store all wallets addresses in each wallet repository metadata
Account or wallet needs to be activated at least once before making a transaction.
Make transactions between different accounts or wallets and see that receiving addresses is correctly tagged as "own".
=> [LW 10170] Store own addresses from all wallets and accounts

apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
---
improve when mnemonic reset warning popup modal is shown when moving back from next step in create flow
=> fix: improve mnemonic reset warning popup modal

packages/common/src/ui/components/Form/Input/Input.tsx, packages/core/src/ui/components/WalletSetupRevamp/WalletSetupSelectAccountsStepRevamp.module.scss, packages/core/src/ui/components/WalletSetupRevamp/WalletSetupSelectAccountsStepRevamp.tsx
=> fix: input field overlap

packages/core/src/ui/components/ActivityDetail/ActivityTypeIcon.tsx, packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx, packages/core/src/ui/components/DappTransaction/DappTransaction.tsx, packages/staking/src/features/overview/StakePoolSearch/StakePoolSearch.tsx
---
In order to have placeholder rendered value passed into the `search` component imported from `antd` lib should be either `undefined` or `null` 
Connect your hw device and proceed to the staking page
[LW-10237]: https://input-output.atlassian.net/browse/LW-10237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(extension): fix placeholder visibility in search pool input

apps/browser-extension-wallet/src/views/browser-view/features/activity/components/ActivityDetail.tsx, packages/core/src/ui/components/ActivityDetail/TransactionDetailAsset.ts, packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
---
The current code resulted in a bug due to just comparing a translated string to a
string literal 'sent' to determine if the transaction was going in or out which failed for the "sending" state (and wouldnt work for other languages anyway)
Pass the `TransactionActivityType` to the transaction details to determine the correct state of the transaction.
Send a transaction and quickly switch to the activity tab while it is in "sending" state. Make sure that the summary says "to" instead of "from" for the target address.
=> fix(extension): "From" instead of "To" label for Sending transaction [LW-9741]

packages/common/src/analytics/types.ts, packages/core/src/ui/components/WalletSetupRevamp/WalletSetupMnemonicStepRevamp/WalletSetupMnemonicStepRevamp.module.scss, packages/core/src/ui/components/WalletSetupRevamp/WalletSetupMnemonicStepRevamp/WalletSetupMnemonicStepRevamp.tsx, packages/core/src/ui/components/WalletSetupRevamp/WalletSetupMnemonicStepRevamp/WalletSetupMnemonicVerificationStepRevamp.tsx, packages/core/src/ui/lib/translations/en.json
=> feat(extension): update copy of copy/paste tooltip

apps/browser-extension-wallet/.env.defaults, apps/browser-extension-wallet/.env.developerpreview, apps/browser-extension-wallet/.env.example, apps/browser-extension-wallet/package.json, apps/browser-extension-wallet/src/features/ada-handle/config.ts, apps/browser-extension-wallet/src/hooks/useHandleResolver.ts, apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts, apps/browser-extension-wallet/src/utils/validators/address-book.ts, yarn.lock
---
We want to start using `handleHttpProvider` instead of Koralabs, therefore we replace all instances and clean up imports. 
- Try to test handles, try to send to a handle, add a handle to address book, try to send to wrong handle and see it's not found. 
- Try to test subhandles as well in the same way.
=> [LW-10289] replace Koralabs handleProvider with SDK handleHttpProvider

packages/core/src/ui/components/OutputSummary/OutputSummary.module.scss, packages/core/src/ui/components/OutputSummary/OutputSummary.stories.tsx, packages/core/src/ui/components/OutputSummary/OutputSummaryUtils.tsx
---
Re add removed style and create story for automated UI snapshot test.
Create transaction with more than one asset
=> [LW-10533] Assets list on the transaction summary page is broken

apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/MultiWallet.module.scss, packages/core/src/ui/components/WalletSetupRevamp/WalletSetupStepLayoutRevamp.module.scss
---
fix multi-wallet timeline container on small screen
=> fix: multi-wallet timeline container on small screen

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/AddressInput.tsx
---
The `exists` property gets updated whenever the user is typing, thus, blocking the input field when the handle matches any existing address. The `DestinationAddressInput` component has an internal logic to disable the input when `handle === HandleVerificationState.VERIFYING`
[LW-10446]: https://input-output.atlassian.net/browse/LW-10446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(extension): [LW-10446] remove handle from getExistingAddress check 

apps/browser-extension-wallet/src/components/DropdownMenu/DropdownMenu.tsx, apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserAvatar.tsx, apps/browser-extension-wallet/src/hooks/useCollateral.ts, apps/browser-extension-wallet/src/hooks/useDelegationDetails.ts, apps/browser-extension-wallet/src/hooks/useGetHandles.ts, apps/browser-extension-wallet/src/hooks/useMaxAda.ts, apps/browser-extension-wallet/src/hooks/useSyncingTheFirstTime.ts, apps/browser-extension-wallet/src/hooks/useWalletAvatar.ts, apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsWalletBase.tsx
---
Get rid of the errors that appear after wallet removal in the manifest in chorme extensions. 
- Remove wallet in Lace and check the chrome extensions tab for erros. 
- There should be no errors for staking addresses, handles, and balance. 
=> [Lw-10372] set up defensive code for when inMemoryWallet or CardanoWallet does not exist

apps/browser-extension-wallet/src/features/delegation/components/MultiDelegationStakingPopup.tsx, apps/browser-extension-wallet/src/hooks/__tests__/useWalletManager.test.tsx, apps/browser-extension-wallet/src/hooks/useWalletManager.ts, apps/browser-extension-wallet/src/types/local-storage.ts, apps/browser-extension-wallet/src/utils/constants.ts, apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingContainer.tsx, packages/e2e-tests/src/elements/staking/MultidelegationDAppIssueModal.ts, packages/e2e-tests/src/features/e2e/StakingInitialFundsE2E.feature, packages/e2e-tests/src/fixture/localStorageInitializer.ts, packages/e2e-tests/src/hooks/beforeTagHooks.ts, packages/e2e-tests/src/steps/commonSteps.ts, packages/e2e-tests/src/steps/multidelegationSteps.ts, packages/staking/.storybook/StakingStorybookProvider.tsx, packages/staking/src/features/BrowsePools/StakePoolsList/StakePoolsListRow.tsx, packages/staking/src/features/Drawer/Drawer.tsx, packages/staking/src/features/Drawer/StakePoolDetail.tsx, packages/staking/src/features/Drawer/preferences/StepPreferencesContent.tsx, packages/staking/src/features/i18n/translations/en.ts, packages/staking/src/features/i18n/types.ts, packages/staking/src/features/modals/MultidelegationDAppCompatibilityModal.tsx, packages/staking/src/features/outside-handles-provider/types.ts, packages/staking/src/features/staking/OneTimeModals.tsx
---
Make use of existing pattern from staking package based on `useOutsideHandles` hook to pass proper state.
Check `Scenario` section from the description of ticket.
[LW-9230]: https://input-output.atlassian.net/browse/LW-9230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(extension): [LW-9230] add multi delegation and dapp issues modal

packages/core/.storybook/preview.js, packages/core/.storybook/theme.scss, packages/core/src/ui/components/DestinationAddressInput/DestinationAddressInput.module.scss, packages/core/src/ui/components/DestinationAddressInput/DestinationAddressInput.stories.tsx, packages/ui/src/design-system/decorators/color-schema/color-schema.css.ts, packages/ui/src/design-system/decorators/color-schema/color-schema.decorator.tsx
---
- Prevent line break on white spaces
- Add story to include scenario on snapshot test
Create an address book entry with a white space such as "My address" and verify that the name is displayed correctly in send flow.
=> [LW-10451] Address book name broken on address input

packages/staking/src/features/BrowsePools/StakePoolsSearchEmpty.css.ts, packages/staking/src/features/BrowsePools/StakePoolsSearchEmpty.tsx
---
Remove unnecessary class added to the empty placeholder wrapper during LW-10502.
1. Open Lace.
2. Go to Staking page.
3. Switch to grid view.
4. Enter search query that does not return any results.
Verify page UI.
=> fix(staking): [LW-10669] remove unnecessary wrapper class for empty placeholder

packages/core/src/ui/components/WalletSetupRevamp/WalletSetupSelectAccountsStepRevamp.module.scss, packages/core/src/ui/components/WalletSetupRevamp/WalletSetupSelectAccountsStepRevamp.tsx, packages/ui/src/design-system/select/select-root.component.tsx
---
1. Add new `zIndex` prop to the Select component
2. Use `zIndex` in `WalletSetupSelectAccountsStepRevamp` (Select)
1. Open Lace.
3. Open user menu.
4. Click on Add new wallet button.
5. Connect HW wallet via USB cable, unlock it and run Cardano app (Ledger).
6. Click on Connect button.
7. Select your device from HID window and click Connect button.
8. Reveal accounts list.
=> fix(ui,core): [LW-10671] add z-index for account select in HW setup flow

packages/staking/src/features/theme/colors.ts
---
Replace incorrect color for the oversaturated state in the Stake Pools Table view.
1. Open Lace (please use Mainnet due to better stake pools availability).
2. Go to Staking page.
3. Open Browse pools tab.
4. Switch to list view.
5. Click on Saturation column header.
6. Take a look at saturation indicators (saturation >= 95%).
=> fix(staking): [LW-10659] oversaturated dot color in StakePoolsTable view

packages/e2e-tests/src/assert/tokensPageAssert.ts, packages/e2e-tests/src/features/e2e/SendTransactionBundlesE2E.feature
Bug from [LW-8958](https://input-output.atlassian.net/browse/LW-8958) seems to have been fixed now, cannot reproduce. Unblocking test LW-4121.
[LW-8958]: https://input-output.atlassian.net/browse/LW-8958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(extension): unblocking and fixing LW-4121

apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/WalletAccounts.tsx
[Jira Ticket]: https://input-output.atlassian.net/browse/LW-10672
This PR introduces a fix for the broken "Try Again" button while enabling an account with **_Ledger HW._**
---
While trying to enable an account when the dive is locked, the component loses the selected account index in an error state. This fix ensures that the index is passed to the error state so the user can click on "Try again" and re-try the procedure 
Check the steps to reproduce described in the ticket https://input-output.atlassian.net/browse/LW-10672:
1. Open Lace with Ledger wallet restored and connected.
2. Open user menu.
3. Open account menu for connected wallet.
4. Lock Ledger device.
5. Click on Enable button for any of disabled accounts.
6. Select your device from HID window and click Connect button.
7. …
=> fix(extension): [LW-10672] fix broken try again button while enabling account

.github/workflows/e2e-tests-linux-split.yml, packages/e2e-tests/src/features/TransactionsExtended.feature
When triggered by push, required 'runner' param was undefined.
=> Add default runner param to e2e split workflow

apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/WalletAccounts.tsx, package.json
---
This PR configures the CI to fail if one or more warnings are thrown in the linting job.
1. Go to the actions tab here: https://github.com/input-output-hk/lace/actions/workflows/build-dev-preview.yml
2. Click on the `Run workflow` button and select `fail-linter-on-warning` from the branch selector dropdown
3. Click on `Run workflow` and wait for a few seconds while the workflow gets scheduled
4. Go into the workflow run and see the logs to confirm that the job would fail if any warnings are detected during linting
=> Update lint script to not tolerate warnings during linter runs

apps/browser-extension-wallet/src/stores/slices/activity-detail-slice.ts, apps/browser-extension-wallet/src/stores/slices/wallet-activities-slice.ts, packages/core/src/ui/components/Activity/AssetActivityItem.tsx, packages/staking/src/features/overview/helpers/hasPendingDelegationTransaction.ts
---
[LW-10789]: https://input-output.atlassian.net/browse/LW-10789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(extension): [lw-10789] fix delegation tx summary

apps/browser-extension-wallet/src/hooks/useWalletActivities.ts, apps/browser-extension-wallet/src/stores/slices/activity-detail-slice.ts, apps/browser-extension-wallet/src/stores/slices/wallet-activities-slice.ts, apps/browser-extension-wallet/src/utils/tx-inspection.ts, apps/browser-extension-wallet/src/views/browser-view/features/activity/components/ActivityDetail.tsx, apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/common-tx-transformer.ts, packages/core/src/ui/components/Activity/AssetActivityItem.tsx, packages/core/src/ui/components/ActivityDetail/ActivityTypeIcon.tsx, packages/core/src/ui/components/ActivityDetail/types.ts, packages/staking/src/features/overview/helpers/hasPendingDelegationTransaction.ts, packages/translation/src/lib/translations/core/en.json
add proper mappers for missed conway era certs
---
Extend tx inspection related mappers with missed conway era certs.
Follow the steps in the description of the ticket.
[LW-10789]: https://input-output.atlassian.net/browse/LW-10789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LW-10782]: https://input-output.atlassian.net/browse/LW-10782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(extension): [lw-10782] add proper mappers for missed conway era certs

apps/browser-extension-wallet/src/features/ada-handle/config.ts, apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts, apps/browser-extension-wallet/webpack-utils.js
---
Using "Sanchonet" as placeholder for the custom networks.
Developer preview option should be used to build with the custom network.
Use the `.env` file to override the sanchonet URLs that Lace connects to, for configuring custom networks.
```
CARDANO_SERVICES_URL_SANCHONET=https://custom-network-url.domain
BUILD_DEV_PREVIEW=true
```
See `.env` example above.
=> LW-10620: prepare Lace to support custom network

.github/shared/build/action.yml
In this PR I'm checking if npmScope exists in ~/.yarnrc.yml before adding it.
This is the case for self hosted runners which are not terminated after each run, so multiple workflow runs add multiple entries to `~/.yarnrc.yaml` file which produce errors like this:
```
YAMLException: duplicated mapping key at line 5, column -142:
npmScopes:
^
at generateError (/usr/lib/node_modules/yarn/lib/cli.js:126542:10)
at throwError (/usr/lib/node_modules/yarn/lib/cli.js:126548:9)
at storeMappingPair (/usr/lib/node_modules/yarn/lib/cli.js:126710:7)
at readBlockMapping (/usr/lib/node_modules/yarn/lib/cli.js:127473:9)
at composeNode (/usr/lib/node_modules/yarn/lib/cli.js:127734:12)
at readDocument (/usr/lib/node_modules/yarn/lib/cli.js:127894:3)
at loadDocuments …
```
=> ci: do not add multiple npmScope entry in .yarnrc.yamla

packages/e2e-tests/wdio.conf.base.ts
[LW-10859](https://input-output.atlassian.net/browse/LW-10859)
Adding 'noStrictFlaky' flag to cucumber options. This will not fail a suite which had a failed test that passed on retry.
Works as advertised, test on cucumber report is marked as failed but not failing whole runner results as it passed on retry:
[LW-10859]: https://input-output.atlassian.net/browse/LW-10859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(extension): e2e add noStrictFlaky option

.github/workflows/e2e-tests-linux-split.yml, .github/workflows/e2e-tests-linux.yml
After shared build refactoring, install deps step is needed for long running e2e workflow.
=> Old regression quick fix

apps/browser-extension-wallet/src/hooks/useMaxAda.ts
---
Fix max ADA calculation to account for wallets with too many assets
=> fix: max ada is now computed correctly when the wallet has too many assets

.github/workflows/e2e-tests-linux-split.yml
Provide `github-token` for `actions/download-artifact@v4` to authenticate with GitHub API.
```
github-token:
```
https://github.com/actions/download-artifact
=> test: authenticate to fetch artifacts from diff workflow run

packages/core/src/ui/components/ActivityDetail/components/TxDetailsProposalProcedures/ProposalProcedureAction.tsx, packages/core/src/ui/utils/governance-action.ts
=> fix(core): display reward account and deposit for info action proposal procedures

.github/workflows/e2e-tests-linux-split.yml
Fix default preprod network url for e2e regression workflow
=> test(extension): fix default preprod network url

apps/browser-extension-wallet/.env.defaults, apps/browser-extension-wallet/.env.developerpreview, apps/browser-extension-wallet/.env.example, apps/browser-extension-wallet/manifest.json, apps/browser-extension-wallet/src/features/ada-handle/config.ts, apps/browser-extension-wallet/src/hooks/useHandleResolver.ts, apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts, apps/browser-extension-wallet/webpack-utils.js
There's no need to manage a separate set of configuration for this provider, given we're now using the same backend.
- Remove `ADA_HANDLE_URL_*` from `.env`
- Set `CARDANO_SERVICES_URL_PREPROD` to `https://live-preprod.lw.iog.io`
- Create dev build
- Load extension and observe expected behaviour
- Check to see that handle requests on _preprod_ are being resolved by the `live-` server from the send form and address book.
=> LW-11277 refactor: simplify Ada Handle provider configuration

apps/browser-extension-wallet/src/lib/scripts/background/cache-wallets-address.ts
The `updateWalletMetadata` method was losing its context (this) when used as a callback, resulting in a `TypeError` because `this` on  the `this.#logger` call was undefined.
---
Changed the function call within the subscription to use an arrow function. This modification ensures that the context of this is preserved.
=> fix(extension): fix bind context to updateWalletMetadata for subscriptions

apps/browser-extension-wallet/src/features/dapp/components/SignTransaction.tsx
DApp auth confirm crash on 'enter' key
---
Manage onSubmit to avoid reload on Password form.
=> fix(extension): signTransaction component no longer crash when enter is pressed on password input

apps/browser-extension-wallet/.env.defaults, apps/browser-extension-wallet/.env.developerpreview, apps/browser-extension-wallet/.env.example, apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts
---
Sanchonet does not support handle provider. Use dummy provider in Lace when on Sanchonet
`BUILD_DEV_PREVIEW=true yarn build`
Manual testing against sanchonet network using [gov tool](https://sanchogov.tools/) and [ryun's dapp](https://ryun1.github.io/cip95-cardano-wallet-connector/)
=> feat(extension): use noop handle provider when on sanchonet

apps/browser-extension-wallet/src/hooks/useChainHistoryProvider.ts, packages/cardano/src/wallet/lib/providers.ts
This reverts commit 822ed979b62c200e00be7761f44d5b630788f820.
---
No need to support two versions of chain-history provider.
=> chore: revert temporary override chain-history version to support pre-p2p back-end

packages/cardano/src/wallet/util/asset-balance.ts
---
The assetBalanceToBigInt function was crashing when a big number and many decimals were passed to it, this is because  BigNumber toString compacts the number notation with big numbers to something like **2.222222222222222e+21** which cant be parsed by BigInt.
Add toFixed(0) to it, so we force the string representation to always display all digits correctly.
=> fix: balance to BigInt convertion no longer crash with big numbers

.github/actions/chromatic/action.yml, packages/staking/src/features/Drawer/SignConfirmation.tsx
Password confirmation on Staking drawer gets stuck if you press confirm with empty password
---
Component was not checking against the password component value. This is now fixed
=> fix: confirm button is now disabled if password is empty on staking confirmation screen

apps/browser-extension-wallet/src/features/dapp/components/SignData.tsx
Sign Data confirm crash on 'enter' key
JIRA - <[link](https://input-output.atlassian.net/browse/LW-11650)>
Manage onSubmit to avoid reload on Password form.
=> fix(extension): signData component no longer crash when enter is pressed on password input

apps/browser-extension-wallet/src/hooks/useWalletManager.ts, apps/browser-extension-wallet/src/views/nami-mode/NamiView.tsx, packages/nami/src/adapters/wallet.test.ts, packages/nami/src/adapters/wallet.ts, packages/nami/src/features/outside-handles-provider/types.ts, packages/nami/src/types/wallet.ts, packages/nami/src/ui/indexMain.tsx
=> fix: change password flow

apps/browser-extension-wallet/src/views/browser-view/features/shared-wallet/SharedWallet.tsx
---
Use the existing wallet data to select the chain, not a hardcoded value
[LW-11766]: https://input-output.atlassian.net/browse/LW-11766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(extension): shared wallet creation uses currently selected environment

packages/nami/src/adapters/transactions.ts
implement try/catch with undefined fallback
prevents nami crashing if bech32 or base8 decode fails, or throws due to:
- invalid string length
- mixed formatting
- any other issue related to encoding
- companion PR to https://github.com/input-output-hk/nami/pull/962
---
Added try/catch with additional attempt to cast as byron address, with appropriate error fallback
Use same wallet addr provided in the companion PR before and after applying these changes
[LW-11769]: https://input-output.atlassian.net/browse/LW-11769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(nami): add bech32 encoding fallback for nami mode

packages/nami/src/ui/app/components/changePasswordModal.tsx
---
[LW-11748]: https://input-output.atlassian.net/browse/LW-11748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-11748] show empty pass error on input in change password modal

apps/browser-extension-wallet/src/lib/scripts/background/cip30.ts, apps/browser-extension-wallet/src/lib/scripts/background/requestAccess.ts, apps/browser-extension-wallet/src/lib/scripts/background/util.ts, apps/browser-extension-wallet/src/utils/constants.ts
---
Hardware wallets dApp connector were displayed wider because it required displaying an extra popup for device selection. This is no longer required.
Both hardware wallets and in memory wallet dApp connector use the same popup and size
=> fix: hardware wallet dApp connector now uses the same window size as regular wallets

.github/workflows/ci.yml
This config was missed in the original implementation
=> ci: add missing Sentry config to release package build

packages/nami/src/ui/app/components/transactionBuilder.tsx
---
First attempt to unstake using Ledger HW wallet does not work properly dues to incorrect handling of modals
Close the correct modal after undelegation
=> fix: handle modal closure after stake deregistration

apps/browser-extension-wallet/src/components/DropdownMenu/DropdownMenu.tsx, apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
---
[LW-11846]: https://input-output.atlassian.net/browse/LW-11846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-11846]: shorted wallet name and account in the user dropdown

apps/browser-extension-wallet/src/hooks/useWalletManager.ts, packages/core/src/shared-wallets/add-shared-wallet/generate-key-flow/generate-shared-wallet-key.ts, packages/core/src/shared-wallets/flow-stories/AddSharedWalletStorybookHelper.tsx
---
Previously, we created a keyAgent just to get the xpub key of the wallet. There is no need for that, Since there's already [functionality to generate xpub key](https://github.com/input-output-hk/lace/blob/main/apps/browser-extension-wallet/src/hooks/useWalletManager.ts#L154-L183) from an encrypted passphrase, I extended it to be able to generate CIP-1854 xpub keys too.
I tested manually and works as expected.
=> fix: improve shared wallet xpub key generation

apps/browser-extension-wallet/src/lib/scripts/background/__tests__/cache-nami-metadata.test.ts, apps/browser-extension-wallet/src/lib/scripts/background/cache-nami-metadata.ts
---
Nami mode balance is cached only once per wallet/account activation. This is because it is using zip operator, which waits for all the combined observables to emit before emitting a value itself. Once it emits, it doesn't react to subsequent changes in individual observables unless all observables emit again.
Use combineLatest instead of zip. combineLatest emits whenever any of the input observables emit a new value. I alsoa dded a 50 ms debounce to make sure multiple emissions of several observables do not trigger an account update.
=> fix: account balance in account preview is now updated upon account activation

apps/browser-extension-wallet/src/features/nami-migration/Activating.tsx, apps/browser-extension-wallet/src/features/nami-migration/NamiMigrationGuard.tsx, apps/browser-extension-wallet/src/lib/scripts/background/nami-migration.ts, apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts, apps/browser-extension-wallet/src/lib/scripts/types/index.ts, apps/browser-extension-wallet/src/lib/scripts/types/nami-migration-channels.ts
---
Lace wallet is importing from background script in the UI script, which is causing the wallet to be instantiated in the UI script every time a new tab or popup is opened.
=> LW-11892 fix: base wallet is now only loaded in background script

apps/browser-extension-wallet/src/views/nami-mode/NamiView.tsx, packages/nami/src/features/outside-handles-provider/types.ts, packages/nami/src/ui/app/components/transactionBuilder.tsx
---
This PR fixes the collateral check in Nami by introducing the same check as used for Lace.
- Setup a wallet with 5.5 ADA which should fail the collateral check in Lace (but not in Nami mode on `main` branch)
- For this PR test that the collateral check fails for both Lace and Nami mode (as expected)
=> fix(nami): use same collateral check as in Lace [LW-11900]

apps/browser-extension-wallet/src/views/nami-mode/NamiView.tsx, packages/nami/src/adapters/transactions.ts, packages/nami/src/features/outside-handles-provider/types.ts
---
Use custom input resolver to avoid additional calls to chain-history.
[LW-11938]: https://input-output.atlassian.net/browse/LW-11938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [LW-11938] remove inputs resolver that relies on chain history provider

apps/browser-extension-wallet/src/views/browser-view/features/activity/components/ActivityDetail.tsx, packages/core/src/ui/components/ActivityDetail/RewardsDetails.tsx, packages/core/src/ui/components/ActivityDetail/__tests__/RewardsDetails.test.tsx, packages/e2e-tests/src/assert/transactionDetailsAssert.ts, packages/e2e-tests/src/elements/transactionDetails.ts
---
[LW-11875]: https://input-output.atlassian.net/browse/LW-11875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-11875] remove status info from reward activity details

apps/browser-extension-wallet/src/hooks/__tests__/useCollateral.test.tsx, apps/browser-extension-wallet/src/hooks/index.ts, apps/browser-extension-wallet/src/hooks/useCollateral.ts, apps/browser-extension-wallet/src/hooks/useHasEnoughCollateral.ts, apps/browser-extension-wallet/src/utils/constants.ts, apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsWalletBase.tsx, apps/browser-extension-wallet/src/views/browser-view/features/settings/components/__tests__/SettingsWallet.test.tsx, packages/e2e-tests/src/steps/analyticsSteps.ts
---
Instead of using maxAda value, build a transaction with only the collateral. If the transaction succeed, the wallet has enough ada for collateral.
=> fix: improve hasEnoughAda check when setting collateral

apps/browser-extension-wallet/src/views/browser-view/features/settings/components/Collateral/send/CollateralFooterSend.tsx, packages/core/src/shared-wallets/add-shared-wallet/generate-key-flow/EnterPassword/EnterPassword.tsx, packages/core/src/ui/components/WalletSetup/WalletSetupPasswordStep.tsx
---
Adjusted the flow to submit transaction before clearing password
=> fix: collateral password issue [LW-11953]

apps/browser-extension-wallet/src/hooks/useWalletManager.ts, apps/browser-extension-wallet/src/lib/scripts/background/storage/extension-document-store.ts, apps/browser-extension-wallet/src/lib/scripts/background/storage/extension-store.ts, packages/e2e-tests/src/fixture/walletRepositoryInitializer.ts
---
deleting a wallet does:
1. delete it from repository
2. check remaining wallets, activate if some wallet exists
there was a bug where step 2. would find the wallet that was just deleted and try to activate it, because extension storage 'observeAll' emits slightly later
953d5507d066ea149bc92381488a105657eb7046
set()/get() applies toSerializableObject/fromSerializableObject respectively
storageChange$ did not, resulting in emitting slightly different objects
that were not processed by fromSerializableObject util this broke disabling accounts that were just enabled
and possibly some other functionality
487502c4b8b1c4340d1808f38b754ebb9bd21592
[LW-11986]: https://input-output.atlassian.net/browse/LW-11986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
=> fix: align extension storage 'set' and 'observeAll' with pouchdb storage behavior

apps/browser-extension-wallet/src/lib/scripts/background/config.ts, apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts, apps/browser-extension-wallet/src/providers/ExperimentsProvider/config.ts, apps/browser-extension-wallet/src/providers/ExperimentsProvider/types.ts, packages/cardano/src/wallet/index.ts, packages/cardano/src/wallet/lib/__tests__/blockfrost-address-discovery.test.ts, packages/cardano/src/wallet/lib/__tests__/blockfrost-input-resolver.test.ts, packages/cardano/src/wallet/lib/blockfrost-address-discovery.ts, packages/cardano/src/wallet/lib/blockfrost-input-resolver.ts, packages/cardano/src/wallet/lib/cardano-wallet.ts, packages/cardano/src/wallet/lib/providers.ts
---
Lace currently consumes takes a long time to resolve wallet addresses.
This PR introduces a new BlockfrostAddressDiscovery which uses accounts to fetch all relevant addresses. This PR also introduces a new BlockfrostInputResolver
=> feat: add blockfrost input resolver and address discovery

apps/browser-extension-wallet/src/views/browser-view/features/settings/components/PaperWalletSettingsDrawer.tsx, apps/browser-extension-wallet/src/views/browser-view/features/sign-message/SignMessageDrawer.tsx, packages/e2e-tests/src/assert/settings/EnterYourPasswordDrawerAssert.ts
---
Fix regression introduced in #1614 + unify the approach to handling password refs.
1. Open Lace.
2. Open user menu.
3. Click on Settings.
4. Click on Generate paper wallet
5. Click on Next button 
6. Provide the password and click "Generate paper wallet"
=> fix(extension): footer rendering in PaperWalletSettingsDrawer [LW-12080]

apps/browser-extension-wallet/src/dapp-connector.tsx, apps/browser-extension-wallet/src/features/dapp/components/Connect.module.scss, apps/browser-extension-wallet/src/routes/DappConnectorView.tsx
---
Popup is not opened with the correct side on windows.
Set popup size automatically.
- check extension popup (nami/lace on win/non win)
- check dapp popup (nami/lace on win/non win)
- check hw related popups (there is separate hw tab for nami mode)
[LW-12050]: https://input-output.atlassian.net/browse/LW-12050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-12050] fix dapp popup related stylings on win platform

apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/context.tsx, apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/useHotWalletCreation.ts, packages/e2e-tests/src/features/analytics/AnalyticsOnboardingEvents.feature
---
Alias uses the hash of the `extendedAccountPublicKey` as wallet ID to tag events and make them less anonymous. Currently we don't wait for wallet creation to complete before sending events which does not allow an alias to be created since the wallet ID is unavailable.
This PR waits for the wallet creation to complete and the wallet ID to be available before sending analytics and creating alias.
=> fix: ensure wallet creation completes before creating alias

apps/browser-extension-wallet/src/hooks/useNftSearch.ts, apps/browser-extension-wallet/src/utils/get-token-list.ts, apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetPortfolioContent.tsx, apps/browser-extension-wallet/src/views/browser-view/features/assets/types.ts, apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/CreateFolder/AssetPicker.tsx, apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/utils.ts, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/AssetPicker.tsx, packages/core/src/ui/components/AssetSelector/AssetSelectorOverlay.tsx, packages/core/src/ui/components/Nft/NftItem.tsx
---
Existing (assets picker) behaviour allows searching nfts by `name` and tokens by `name`, `description` and `id` fields.
Allow searching nfts by `name`, `assetId ` and `policyId`, allow searching tokens by `name`, `policyId`, `fingerprint`, `ticker`, so the behaviour is aligned with main search functionality on "Nfts" and "Tokens" tab respectively.
[LW-12125]: https://input-output.atlassian.net/browse/LW-12125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LW-12131]: https://input-output.atlassian.net/browse/LW-12131?atlOrigin=eyJpIjoiN …
=> fix: [lw-12125] align assets search in assets picker

apps/browser-extension-wallet/package.json, apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts, apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/featureFlagPayloadsSchema.ts, apps/browser-extension-wallet/src/utils/mocks/test-helpers.tsx, apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/services/api/d-app/index.ts, package.json, yarn.lock
---
- introduce Feature Flag payload validation
- allow defining types for custom payloads
- improve error handling
- add new method PostHogClient.getFeatureFlagPayload()
Change the `dapp-explorer` feature flag config and see how/if Dapps are rendered
=> feat(extension): allow hiding dapps based on feature flag config [LW-11883]

apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/services/api/categories/index.ts, apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/services/api/d-app/index.ts, apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/services/cache.test.ts, apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/services/cache.ts
---
- storing DApp Radar API responses in a local storage entry
- each entry has a timestamp of insertion
- if the timestamp is older than one day the entry is considered expired
- if no cache entry then DApp Radar API request is performed
- Ensure requests are performed only once
- Modify timestamp of particular cache entry (the one with `dapp-explorer-data-cache` name) to make it older than 1 day and ensure the request is made.
=> feat: add caching for dapp radar api requests

apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/index.ts, apps/browser-extension-wallet/src/providers/PostHogClientProvider/index.ts
---
This PR fixes warnings about the exported and re-exported types name discrepancies in posthog client.
=> fix: resolve export warnings on posthog provider

apps/browser-extension-wallet/src/hooks/useWalletManager.ts, packages/nami/src/adapters/account.test.ts, packages/nami/src/adapters/account.ts, packages/nami/src/ui/app/pages/wallet.tsx, packages/nami/src/ui/indexMain.tsx
---
`deleteWallet` is called when there is no accounts left in active wallet. Current in nami `remove account` implementation would try to switch to the next available account/wallet before calling remove wallet, but `deleteWallet` util operates with currently active wallet, as result, wrong wallet is deleted.
As a solution we need to provide `deleteWallet` util from in `useWalletManager` hook with the next wallet to restore as param.
[LW-12156]: https://input-output.atlassian.net/browse/LW-12156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
=> fix: [lw-12156] fix remove wallet account functionality in nami mode

packages/e2e-tests/src/assert/multidelegation/MultidelegationPageAssert.ts, packages/e2e-tests/src/elements/multidelegation/MultidelegationPage.ts, packages/e2e-tests/src/features/MultidelegationDelegatedFundsMultiplePoolsExtended.feature, packages/e2e-tests/src/features/MultidelegationDelegatedFundsMultiplePoolsPopup.feature, packages/e2e-tests/src/features/MultidelegationDelegatedFundsSinglePoolExtended.part1.feature, packages/e2e-tests/src/features/MultidelegationDelegatedFundsSinglePoolPopup.feature, packages/e2e-tests/src/steps/multidelegationSteps.ts
=> test(extension): update and block tests due to LW-12193

apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/hardware-wallet/context.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx
---
Investigation summary.
Lace crashes.
**Scope:** Signing step is affected in the send flow. (extension is not usable, recovers after refreshing).
**Affects:** Chrome browser, Android and Linux (screen size from the recordings suggests it is some kind of mobile os) platform.
**Reason:** Lace is trying to listen for 'disconnect' event on navigator.hid property, that is undefined.
**Browser compatibility:** hid is compatible with Chrome, Edge (v89 and higher), Opera (v75 and higher). Also [it seems like](https://issues.chromium.org/issues/40628009) only desktop versions of such browsers are supported.
**Proposed solution:** we could check for navigator.hid availability (and do nothing in case it is not there).
**Implications:** in case we cannot listed for disconnect event, user might be …
=> fix: [lw-12138] handle not available navigator.hid in send flow

apps/browser-extension-wallet/src/features/dapp/components/ConfirmData.tsx, apps/browser-extension-wallet/src/features/dapp/components/SignData.tsx, apps/browser-extension-wallet/src/features/dapp/components/SignTransaction.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmTransaction.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/ConfirmTransaction.test.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/hooks.test.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/hooks.ts, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/utils.ts, apps/browser-extension-wallet/src/lib/scripts/types/feature-flags.ts, apps/browser-extension-wallet/src/views/nami-mode/NamiDappConnectorView.tsx, packages/nami/src/features/dapp-outside-handles-provider/types.ts, packages/nami/src/ui/app/pages/dapp-connector/signData.tsx, packages/nami/src/ui/app/pages/dapp-connector/signTx.tsx
---
- cannot `await` inside the callback
- `window.close()` doesn't work  inside the callback
- default confirmation modal is displayed if `true` is returned in the callback, with no ability to provide custom messaging (deprecated in chrome starting from version 51 …)
- cannot `await` inside the callback
- `window.close()` works inside the callback
- Sign/ Confirm transaction (lace + nami mode)
- Sign/ Confirm data  (lace + nami mode)
> [!IMPORTANT]  
> Since we cannot `await` in the callback, please make sure the `tx` was properly rejected before dapp window is closed.*
[LW-12115]: https://input-output.atlassian.net/browse/LW-12115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> fix: [lw-12155] handle page refresh in dapp connector

apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts, apps/browser-extension-wallet/src/stores/slices/wallet-activities-slice.ts, apps/browser-extension-wallet/src/utils/constants.ts
---
Limit stored tx history size.
1. Restore wallet using Lace version >= 1.18.2
2. Update Lace to version in `main` branch
3. Call `await chrome.storage.local.get()` and see how many transactions are stored
4. Update Lace to version in this branch
5. Redo step 3 and see only 10 transactions
=> fix(extension): limit stored tx history size [LW-12227]

apps/browser-extension-wallet/src/lib/scripts/background/config.ts, apps/browser-extension-wallet/src/lib/scripts/background/onUpdate.ts, apps/browser-extension-wallet/src/lib/scripts/background/services/utilityServices.ts, apps/browser-extension-wallet/src/lib/scripts/types/background-service.ts, apps/browser-extension-wallet/src/popup.tsx, apps/browser-extension-wallet/src/utils/AppVersionGuard/AppVersionGuard.tsx, apps/browser-extension-wallet/src/utils/AppVersionGuard/index.ts, apps/browser-extension-wallet/src/views/browser-view/index.tsx
---
- Add console logs for all runtime.on* events in [onUpdate.ts](https://github.com/input-output-hk/lace/blob/main/apps/browser-extension-wallet/src/lib/scripts/background/onUpdate.ts)
- On each UI load, compare application version with the one from the service worker
- Expose new background api method to get application version
- Log sentry error if version doesn’t match with the one from UI process
[LW-12102]: https://input-output.atlassian.net/browse/LW-12102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [lw-12102] log runtime extension events and version mismatch

packages/common/src/AppLogger.ts
---
Logger can receive arbitrary objects as parameters. If it has BigInt properties within some unexpected shape, JSON.strinfify can throw and crash the application
=> fix: fail log instead of potentially crashing [LW-12263]

packages/common/package.json, packages/common/src/AppLogger.ts, packages/common/src/ui/lib/index.ts, packages/common/src/ui/lib/stringify-with-fallback.ts, yarn.lock
---
Fix `AppLogger.convertParams` to stringify all the params, capture stringify errors in Sentry.
N/A
=> feat(common): capture AppLogger stringify error using Sentry [LW-12263]

.github/workflows/sonar-cloud.yml
Sonarcloud's action `SonarSource/sonarcloud-github-action@master` has been deprecated and sonarcloud scans started to fail: https://github.com/input-output-hk/lace/actions/runs/13267269440/job/37037775502?pr=1704
Check deprecation warning here: https://github.com/SonarSource/sonarcloud-github-action
=> chore: update sonarcloud action

.github/workflows/build-dev-preview.yml, .github/workflows/chromatic-core.yml, .github/workflows/chromatic-staking.yml, .github/workflows/ci.yml, .github/workflows/e2e-tests-linux-split.yml, .github/workflows/sonar-cloud.yml
The Ubuntu 20.04 Actions runner image will begin deprecation on 2025-02-01 and will be fully unsupported by 2025-04-01
https://github.com/actions/runner-images/issues/11101
=> ci: update ubuntu action runner image to 22.04

apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/RenameFolderDrawer.tsx
---
[LW-7632]: https://input-output.atlassian.net/browse/LW-7632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-7632] fix rename nft folder feat

packages/nami/src/ui/app/components/historyViewer.tsx, packages/translation/src/lib/translations/browser-extension-wallet/en.json
---
Previously activities feed was limited to 10 txs, but since https://input-output.atlassian.net/browse/LW-12099 brings full activities feed back (but now paginated), we can now tell for sure that we've reached the end of the list and show previously replaceded `... nothing more` message.
[LW-12338]: https://input-output.atlassian.net/browse/LW-12338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-12338] remove end message from activities tab in nami mode

apps/browser-extension-wallet/src/hooks/useWalletActivities.ts, apps/browser-extension-wallet/src/views/browser-view/features/assets/components/Assets.tsx, packages/core/src/ui/components/Activity/GroupedAssetActivityList.tsx, packages/staking/src/features/activity/RewardsHistory.tsx
---
Initial page chunk has been hardcoded for tokens page. Use custom hook to get proper initial page size based on height of the window (is not recalculated on resize*).
[LW-12345]: https://input-output.atlassian.net/browse/LW-12345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-12345] adjust initial page size for tokens tab

packages/core/src/ui/components/Activity/GroupedAssetActivityList.tsx, packages/core/src/ui/components/Activity/__tests__/GroupedAssetActivityList.test.tsx, packages/staking/src/features/activity/RewardsHistory.tsx
---
`dataLength` prop should be explicitly provided for `GroupedAssetActivityList` component.
[LW-12354]: https://input-output.atlassian.net/browse/LW-12354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-12354] fix reward history pagination on staking tab

apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetPortfolioContent.tsx
---
By default search bar is hidden if number of `assets < 10` (hardcoded on the ui). Since assets list is paginated now, we need to adjust that logic to check for total amount of assets instead.
[LW-12355]: https://input-output.atlassian.net/browse/LW-12355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-12355] fix search bar visibility in assets page

apps/browser-extension-wallet/src/stores/slices/wallet-activities-slice.ts
---
We do not track `submittedAt` property in the `resolver` of the `lodash.memoize` utility. Combining it with `id` resolves an issues.
[LW-12314]: https://input-output.atlassian.net/browse/LW-12314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-12314] fix pending transaction time on activities page

apps/browser-extension-wallet/src/hooks/__tests__/useAsyncSwitchMap.test.ts, apps/browser-extension-wallet/src/hooks/useAsyncSwitchMap.ts, apps/browser-extension-wallet/src/hooks/useWalletActivities.ts, packages/e2e-tests/src/features/e2e/MultidelegationSwitchingPoolsExtendedE2E.feature
---
This PR removes possible race conditions from Activity List mappers.
See [LW-12226](https://input-output.atlassian.net/browse/LW-12226)
[LW-12226]: https://input-output.atlassian.net/browse/LW-12226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(extension): race condition in activity list [LW-12226]

apps/browser-extension-wallet/src/components/Layout/MainLayout.tsx, apps/browser-extension-wallet/src/features/dapp/components/ConfirmData.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmTransaction.tsx, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/hooks.ts, apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/utils.ts, apps/browser-extension-wallet/src/features/nami-migration/migration-tool/cross-extension-messaging/lace-migration-client.extension.ts, apps/browser-extension-wallet/src/features/nami-migration/migration-tool/cross-extension-messaging/lace/create-lace-migration-open-listener.ts, apps/browser-extension-wallet/src/lib/scripts/background/cip30.ts, apps/browser-extension-wallet/src/lib/scripts/background/requestAccess.ts, apps/browser-extension-wallet/src/lib/scripts/background/services/utilityServices.ts, apps/browser-extension-wallet/src/lib/scripts/background/session/is-lace-tab-active.ts, apps/browser-extension-wallet/src/lib/scripts/background/util.ts, apps/browser-extension-wallet/src/lib/scripts/trezor/trezor-usb-permissions.ts, apps/browser-extension-wallet/src/utils/catch-and-brand-extension-api-error.ts, apps/browser-extension-wallet/src/utils/senderToDappInfo.ts, apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWalletButton.tsx, apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWalletDialog.tsx, apps/browser-extension-wallet/src/views/browser-view/routes/index.tsx, packages/nami/src/ui/app/pages/dapp-connector/signData.tsx, packages/nami/src/ui/app/pages/dapp-connector/signTx.tsx
---
- created a helper that 
- catch extension API errors
- log them
- re-throw as `ExtensionApiError` with a localised message - Sentry will categorise those errors separately
- wrapped all relevant `tabs` API usages with that helper + some other APIs
- improved error handling in
- DApp connector's sign data flow - it shows an error screen when e.g. requesting DApp closed
- DApp connector's transaction flow - it shows an error screen when e.g. requesting DApp closed
- Full automated e2e
- sanity testing of:
- dapp connector
- requesting access + ensure no "only once" regression
- transaction
- sign data
- discarding other open lace tabs when the active wallet is a HW
- discarded tab disappears from task manager and when activated it shows spinner
- logging an error message to the console …
=> refactor: improve error handling of extension tab api interactions

apps/browser-extension-wallet/src/lib/scripts/types/feature-flags.ts, apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts, apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/config.ts, apps/browser-extension-wallet/src/providers/PostHogClientProvider/schema.ts, apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/components/SimpleView/SimpleViewFilters/CategoryChip/mapper.tsx
---
- Removed allowed categories to be provided by the `disallowedCategories` property of the `dapp-explorer` FF payload
- Slightly reorganised code by moving schema validation logic to the PostHogClient space where it is actually used
=> fix: relax validation of disallowedCategories of dapp-explorer feature flag payload [LW-12163]

packages/core/src/ui/components/Activity/AssetActivityItem.tsx
---
Current implementation would treat next type of activities: `delegationRegistration` | `RegistrationCertificate` | `RegisterDelegateRepresentativeCertificate` | `self` | `delegation` | `awaitingCosignatures` and `outgoing` as an activity with negative balance, thus they would have their total amount coloured in black. Changing this behaviour into `positive numbers are green, negative numbers are black, zero is black` would be more accurate.
[LW-11911]: https://input-output.atlassian.net/browse/LW-11911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …
=> fix: [lw-11911] fix negative vs positive activity amount styling

apps/browser-extension-wallet/src/components/ResultMessage/ResultMessage.module.scss, apps/browser-extension-wallet/src/components/ResultMessage/ResultMessage.tsx, apps/browser-extension-wallet/src/features/delegation/components/MultiDelegationStakingPopup.tsx, apps/browser-extension-wallet/src/utils/parse-error.ts, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/CoinInput/useSelectedCoins.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/TransactionFail.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/TransactionSuccessView.module.scss, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/UnauthorizedTransaction.tsx, apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/types.ts, apps/browser-extension-wallet/src/views/browser-view/features/sign-message/SignMessageDrawer.tsx, apps/browser-extension-wallet/src/views/browser-view/features/sign-message/useSignMessageState.tsx, apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingContainer.tsx, packages/staking/src/features/Drawer/HwDeviceFail.tsx, packages/staking/src/features/Drawer/ResultMessage.module.scss, packages/staking/src/features/Drawer/ResultMessage.tsx, packages/staking/src/features/Drawer/SignConfirmation.tsx, packages/staking/src/features/Drawer/TransactionFail.tsx, packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationFooter.tsx, packages/staking/src/features/outside-handles-provider/types.ts, packages/staking/src/features/store/delegationPortfolioStore/stateMachine/commands.ts, packages/staking/src/features/store/delegationPortfolioStore/stateMachine/processExpandedViewCases.ts, packages/staking/src/features/store/delegationPortfolioStore/stateMachine/types.ts, packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts, packages/translation/src/lib/translations/browser-extension-wallet/en.json
---
Store errors thrown during tx submission in the related hooks/utils and reuse them later in the errors screen.
- send flow
- staking flow
[LW-12046]: https://input-output.atlassian.net/browse/LW-12046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-12046] show detailed tx submit errors

packages/core/src/ui/components/DappAddressSections/DappAddressSection.tsx, packages/core/src/ui/components/DappTransactionHeader/DappTransactionHeader.tsx
---
SummaryExpander expects open prop to be passed in order to define the direction of the chevron it renders.
check DoD section in the jira ticket.
[LW-12396]: https://input-output.atlassian.net/browse/LW-12396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-12396] make all summary expanders controlled in dapp connector

apps/browser-extension-wallet/src/features/activity/components/Activity.tsx, apps/browser-extension-wallet/src/hooks/useTxHistoryLoader.ts, apps/browser-extension-wallet/src/hooks/useWalletActivities.ts, apps/browser-extension-wallet/src/views/browser-view/features/activity/components/ActivityLayout.tsx, packages/cardano/src/wallet/lib/tx-history-loader.ts, packages/core/src/ui/assets/icons/refresh.component.svg, packages/core/src/ui/components/Activity/AssetActivityList.module.scss, packages/core/src/ui/components/Activity/GroupedAssetActivityList.tsx, packages/translation/src/lib/translations/core/en.json
---
- catching error in the observable responsible for fetching data
- displaying a message and retry button in place of skeleton if an error occured
Try different ways of switching to offline vs loading activity. Switch to offline:
- before loading lace
- before entering activity
- after initial load of activity
- after a few scrolls
- after switching back to online
=> feat: add error handling to the activity infinite scroll [LW-12392]

.github/actions/install/action.yml
Make sure that we do not add to .yarnrc.yml npmScopes if already exists, otherwise we observe YAMLException like this one:
```
YAMLException: duplicated mapping key at line 5, column -142:
npmScopes:
^
at generateError (/home/runner/_work/_tool/node/20.12.2/x64/lib/node_modules/yarn/lib/cli.js:126542:10)
at throwError (/home/runner/_work/_tool/node/20.12.2/x64/lib/node_modules/yarn/lib/cli.js:126548:9)
at storeMappingPair (/home/runner/_work/_tool/node/20.12.2/x64/lib/node_modules/yarn/lib/cli.js:126710:7)
at readBlockMapping (/home/runner/_work/_tool/node/20.12.2/x64/lib/node_modules/yarn/lib/cli.js:127473:9)
at composeNode (/home/runner/_work/_tool/node/20.12.2/x64/lib/node_modules/yarn/lib/cli.js:127734:12)
at readDocument (/home/runner/_work/_tool/node/20.12.2/x64/lib/node_modules/yarn …
```
=> ci: check npmScope in yarnrc before file update

apps/browser-extension-wallet/src/hooks/useWalletManager.ts, apps/browser-extension-wallet/src/views/browser-view/features/shared-wallet/SharedWallet.tsx, packages/core/src/shared-wallets/add-shared-wallet/creation-flow/ShareWalletDetails/utils.ts, packages/core/src/shared-wallets/add-shared-wallet/creation-flow/validateCoSigners.test.ts, packages/core/src/shared-wallets/add-shared-wallet/creation-flow/validateCoSigners.ts, packages/core/src/shared-wallets/add-shared-wallet/generate-key-flow/Store/machine.ts, packages/core/src/shared-wallets/add-shared-wallet/generate-key-flow/Store/state.ts, packages/core/src/shared-wallets/add-shared-wallet/generate-key-flow/generate-shared-wallet-key.ts, packages/core/src/shared-wallets/add-shared-wallet/restore-flow/validateJson.ts, packages/core/src/shared-wallets/flow-stories/AddSharedWalletStorybookHelper.tsx, packages/core/src/shared-wallets/transaction/CosignersList.tsx
---
Currently, shared wallet keys are displayed as Bip32 Hex string. This PR updates keys to be display in [CIP 5](https://cips.cardano.org/cip/CIP-5) bech32 formats
=> fix: make shared wallet key cip 5 compliant

apps/browser-extension-wallet/src/lib/scripts/background/onStorageChange.ts
---
Address the situation when the `BACKGROUND_STORAGE` key has not yet been created. This went uncaptured due to strict mode issues.
The error should no longer appear in the console.
=> fix(extension): reading background storage when it does not exist yet [LW-12498]

apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/SendStepOne.tsx
---
Prevent negative and non-numeric inputs in BTC custom fee field and disable wheel action on btc custom fees input
=> fix: prevent negative and non-numeric inputs in BTC custom fee field

packages/nami/src/ui/app/pages/dapp-connector/signData.tsx, packages/nami/src/ui/app/pages/dapp-connector/signTx.tsx
---
Sign btn is blocked in case error is thrown while signing the tx. We could:
- either still allow user to sign the tx in case there is an error
- or clear error states when confirmation popup is closed (**wend with this approach for now**)
[LW-12705]: https://input-output.atlassian.net/browse/LW-12705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-12705] clear error states on confirm modal close in dapp popup

apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/SendStepOne.tsx, packages/common/src/ui/components/Form/Input/Input.tsx
---
We do not have specific number input implemented in lace. There is a way to achieve proper behaviour by specifying input type as `number`.
Default behaviour implemented in `antd` lib would pass empty value into the `onChange` event handler in case user enter not valid decimal number, eg: `0.`. As a result, label would cover entered value.
Always set label to be filled (on top) in case input is focused, and reset to 0 on blur.
Please recheck other inputs focus/blur states.
[LW-12562]: https://input-output.atlassian.net/browse/LW-12562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [lw-12562] fix label position for invalid number input

apps/browser-extension-wallet/src/components/DropdownMenu/DropdownMenu.module.scss, apps/browser-extension-wallet/src/components/DropdownMenu/DropdownMenu.tsx, apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/DropdownMenuOverlay.module.scss, apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx, apps/browser-extension-wallet/src/hooks/useWalletAvatar.ts
---
Colour Bitcoin wallets icon in a different (orange!) visual identifier as per designs.
Adjust useWalletAvatar to detect proper active wallet id.
[LW-12558]: https://input-output.atlassian.net/browse/LW-12558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LW-12723]: https://input-output.atlassian.net/browse/LW-12723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [lw-12558] change btc wallet icon option to orange in dropdown

apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/ReviewTransaction.tsx
---
Ensure BTC fee is displayed without exponential notation
=> fix: ensure BTC fee is displayed without exponential notation [LW-12718]

apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWalletButton.tsx, apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/utils.ts
---
As stated in the title, this PR adds new utility `getBanxaUrl` which prepopulates `walletAddress` and `coinType` - can be easily extended.
Please test banxa integration for both blockchains.
**Note**: It's not possible to change `walletAddress` once it was prepopulated.
=> feat(extension): prepopulate banxa form fields with coinType and walletAddress [LW-12629]

apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx, apps/browser-extension-wallet/src/hooks/useAppInit.ts, apps/browser-extension-wallet/src/hooks/useWalletManager.ts, apps/browser-extension-wallet/src/stores/slices/wallet-info-slice.ts, apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsRemoveWallet.tsx
---
- fix `loadWallet` implementation
- ensure we are using proper `activeWalletProps` depending on blockchain
- remove dead code
- **bonus**: add toast when wallet is switched after removal
Please run full regression tests on switching wallets, especially bitcoin wallets and ensure that [LW-12781](https://input-output.atlassian.net/browse/LW-12781) is still working fine.
[LW-12781]: https://input-output.atlassian.net/browse/LW-12781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(extension): loading wallet during app init + switching [LW-13016]

apps/browser-extension-wallet/src/hooks/useWalletManager.ts
---
Issue does not happen for cardano wallet because of the way we construct `isLoaded` state in `/apps/browser-extension-wallet/src/views/browser-view/routes/index.tsx`, where we actually check for some state properties. Instead we display blank page with loader, and once all the data is there, we switch to the actual activities page, which is rendered with a fresh state of local variables.
Proper fix would be:
-  to align `/apps/browser-extension-wallet/src/views/browser-view/routes/index.tsx` and `apps/browser-extension-wallet/src/views/bitcoin-mode/BitcoinBrowserViewRoutes.tsx` in terms of the way we calculate loading state.
- potentially to refactor btc wallet to have observable properties in place of some methods we use to retrieve wallet state data.
- use `window.location.reload()` …
=> fix: reload activities on network switch [lw-13103 ]

apps/browser-extension-wallet/src/assets/html/load-app.js, apps/browser-extension-wallet/src/assets/html/load-dapp-connector.js, apps/browser-extension-wallet/src/assets/html/load-popup.js
We got user report where Lace appears to be loading indefinitely. User shared console logs that indicate a potential cause being https://developer.mozilla.org/en-US/docs/Glossary/bfcache
bfcache appears to break extension messaging
---
fix: add unload handler to prevent bfcache
🤷
=> fix: add unload handler to prevent bfcache

.github/actions/build/app/action.yml
For Edge Web Store submission we need to remove the `key` property from the manifest.json file.
=> Remove key from manifest for Edge Web Store publish

packages/e2e-tests/src/elements/newTransaction/coinConfigure.ts, packages/e2e-tests/src/features/SendTransactionBundlesExtended.part2.feature, packages/e2e-tests/src/features/SendTransactionBundlesExtendedMainnet.feature, packages/e2e-tests/src/features/SendTransactionSimpleExtended.part1.feature, packages/e2e-tests/src/features/SendTransactionSimpleExtended.part3.feature, packages/e2e-tests/src/features/SendTransactionSimpleExtended.part4.feature, packages/e2e-tests/src/features/SendTransactionSimplePopup.part1.feature, packages/e2e-tests/src/features/SendTransactionSimplePopup.part2.feature, packages/e2e-tests/src/features/SendTransactionSimplePopup.part4.feature, packages/e2e-tests/src/steps/sendTransactionSimpleSteps.ts
=> test: remove unnecessary step

packages/staking/src/features/overview/StakingNotificationBanners/StakingNotificationBanners.tsx, packages/staking/src/features/overview/StakingNotificationBanners/getCurrentStakingNotifications.ts, packages/staking/src/features/overview/StakingNotificationBanners/types.ts, packages/staking/src/features/overview/helpers/hasPledgeNotMet.ts, packages/staking/src/features/overview/helpers/index.ts, packages/translation/src/lib/translations/staking/en.json
---
To mitigate the feature gap of BF bulk stake pools API missing the live pledge, added a banner to warn the user in case they are delegating to pools not meeting the pledge.
This covers a missing feature anyway.
Manually tested. Probably needs QA and product validation.
=> LW-13248 Add not met pledge banner

packages/cardano/package.json, packages/cardano/src/wallet/lib/__tests__/stakePoolService.test.ts, packages/cardano/src/wallet/lib/providers.ts, packages/cardano/src/wallet/lib/stakePoolService.ts, packages/staking/src/features/BrowsePools/BrowsePools.tsx, packages/staking/src/features/BrowsePools/hooks/useQueryStakePools.tsx, packages/staking/src/features/Drawer/StakePoolDetail.tsx, yarn.lock
---
- Implemented client side stake pools services which fetches partial stake pools from BF bulk stake pools API and caches them for 1 day.
- Implemented client side `StakePoolProvider`.
- Refactored `useQueryStakePools` custom hook to take advantage of the new performances: removed the use of the paginator.
Manual testing
=> LW-13062 Stake pool service

packages/cardano/src/wallet/lib/__tests__/stakePoolService.ros.test.ts, packages/cardano/src/wallet/lib/__tests__/stakePoolService.test.ts, packages/cardano/src/wallet/lib/providers.ts, packages/cardano/src/wallet/lib/stakePoolService.ts
---
Since Lace shows the ROS only when showing stake pools details, enriching the `enrichStakePool` function with the ROS estimation is enough to compute the estimated ROS when needed.
The ROS computation is based on Shelley ledger specifications (with Conway amendment); the main difference is that ledger specifications uses data from the snapshot on epoch rollovers while here live data is used.
The computation requires some data from the network, the genesis parameter and protocol parameters, so the `StakePoolService` now fetches this data from a `NetworkInfoProvider` or BF directly.
About the stake pool data, almost all data are already fetched; the only exception is the distinction between member stake and operator stake and BF doesn't offer an API to get it... strictly required to …
=> LW-13053 Add estimated ROS

packages/e2e-tests/src/elements/multidelegation/MultidelegationPage.ts, packages/e2e-tests/src/features/MultiDelegationPageExtended.part1.feature, packages/e2e-tests/src/features/MultiDelegationPageExtended.part2.feature, packages/e2e-tests/src/features/MultiDelegationPageExtended.part3.feature, packages/e2e-tests/src/features/MultidelegationDelegatedFundsSinglePoolExtended.part2.feature, packages/e2e-tests/src/steps/multidelegationSteps.ts
=> test: fix multidelegation tests

apps/browser-extension-wallet/src/components/NotificationsCenter/NotificationsBellContainer.tsx, apps/browser-extension-wallet/src/components/NotificationsCenter/NotificationsCenter.module.scss, apps/browser-extension-wallet/src/components/NotificationsCenter/NotificationsCenter.tsx, apps/browser-extension-wallet/src/components/NotificationsCenter/NotificationsCenterContainer.tsx, apps/browser-extension-wallet/src/components/NotificationsCenter/NotificationsCenterLayout.tsx, apps/browser-extension-wallet/src/components/NotificationsCenter/index.ts, apps/browser-extension-wallet/src/hooks/useNotificationsCenterConfig.ts, apps/browser-extension-wallet/src/routes/ExtensionRoutes.tsx, apps/browser-extension-wallet/src/routes/wallet-paths.ts, apps/browser-extension-wallet/src/views/browser-view/routes/index.tsx, packages/translation/src/lib/translations/browser-extension-wallet/en.json
---
Adds the Notifications Center component
=> LW-13590 Add the notifications center
