.markdownlint.json
CONTRIBUTING.md
apps/browser-extension-wallet/CONTRIBUTING.md

**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/58/5144339906/index.html) for [5086d983](https://github.com/input-output-hk/lace/pull/42/commits/5086d98336513a22ab4596787aea8efef3fc395a)

fix: contribution guide

---

apps/browser-extension-wallet/src/lib/scripts/background/onUpdate.ts

---
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/219/5188823665/index.html) for [67c42c39](https://github.com/input-output-hk/lace/pull/51/commits/67c42c39c16b789b3365024eb6e82cbc17c533aa)
| Total | …

feat(extension): force an extension to autoupdate

---

packages/ui/src/design-system/scroll-area/scroll-area.stories.tsx

---
One place was missing the new page decorator and it was causing storybook tests to fail.

fix(ui): use new page decorator in scroll area stories

---

.github/workflows/ci.yml

---
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/253/5190949293/index.html) for [63926d6c](https://github.com/input-output-hk/lace/pull/83/commits/63926d6c575d90ce4346bc836d9bdd532031003f)
| Total | …

Build an artifact enabling all feature flags

---

apps/browser-extension-wallet/src/features/nfts/components/Nfts.tsx
apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/NftsLayout.module.scss
apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/NftsLayout.tsx

---
Apply proper css styling
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/318/5210656867/index.html) for [852a5cf9](https://github.com/input-output-hk/lace/pull/101/commits/852a5cf979caf74181d3fd1c2b96fd6a2edf711b)

fix(extension): align title with create nfts folder button on the nfts page

---

apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx

---
update the url for 'Find out more' link on mnemonic writedown page to point to the `what-happens-if-i-lose-my-recovery-phrase` section
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/308/5208666092/index.html) for [3f7fadfb](https://github.com/input-output-hk/lace/pull/96/commits/3f7fadfb7c011381cb909d1434ded056997533fa)
| Total | 19     | 0      | …

fix(extension): updated find out more link on mnemonic writedown page

---

packages/cardano/src/wallet/lib/hardware-wallet.ts

Added feature flag around Trezor support
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/341/5222056776/index.html) for [db572287](https://github.com/input-output-hk/lace/pull/110/commits/db572287634d58893cb952825fc7dd5334b50234)

feat: add feature flag around trezor support

---

apps/browser-extension-wallet/src/views/browser-view/features/assets/components/Assets.tsx

---
When a wallet had rewards available to claim but no UTxO with ADA, the portfolio balance would display the rewards amount but the "no funds" banner would also be displayed instead of the token table
- Add the rewards to the condition that shows the token table or the no funds banner
- Use the wallet provided in Jira ticket in **PREPROD** and compare this branch with `main`. The token table with Cardano token should appear in this branch.
Note: **DON'T MAKE ANY TRANSACTIONS** so we don't mess up the UTxO distribution and don't claim the rewards
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/324/5214394074/index.html) for …

fix(extension): add rewards to total balance in asset table condition

---

apps/browser-extension-wallet/src/components/Layout/ContentLayout.module.scss
apps/browser-extension-wallet/src/components/Layout/ContentLayout.tsx
apps/browser-extension-wallet/src/features/activity/components/Activity.tsx
apps/browser-extension-wallet/src/views/browser-view/features/activity/components/ActivityLayout.tsx
packages/common/src/ui/components/Table/InfiniteScrollableTable.module.scss
packages/common/src/ui/components/Table/InfiniteScrollableTable.tsx
packages/core/src/ui/components/Activity/GroupedAssetActivityList.tsx
packages/core/src/ui/components/AssetTable/AssetTable.module.scss
packages/core/src/ui/components/AssetTable/AssetTable.tsx

---
apply proper stylings (**_width would be a bit different in case the scrollbar is there*_**)
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/383/5259927156/index.html) for [56c7e970](https://github.com/input-output-hk/lace/pull/120/commits/56c7e970f7cd767aaa83501af59a869bf18df362)
| Total | 14     | 5      | 0       | 0     | 19    | ❌     |

fix(extension): fix asset item sizings

---

.github/workflows/post-integration.yml

---
Builds from [post-integration.yml](https://github.com/input-output-hk/lace/actions/workflows/post-integration.yml) have CORS issues
Unfortunately, only after the merge to `main`
n/a
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/440/5288695469/index.html) for [34ab0187](https://github.com/input-output-hk/lace/pull/134/commits/34ab0187de6ad4a33ade8e563e804b7a348d1176)

ci: set `LACE_EXTENSION_KEY` in `post-integration.yml`

---

apps/browser-extension-wallet/src/features/address-book/context/AddressBookProvider.tsx

---
Disallow duplicates when updating the address book
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/510/5320757147/index.html) for [c3b2b4ec](https://github.com/input-output-hk/lace/pull/141/commits/c3b2b4ec41139a6cb13e2df02f50511410094cc6)
| Total | 13     | 6      | 0       | 0     | 19    | ❌     |

fix: disallow duplicates when updating address book

---

packages/core/src/ui/components/DestinationAddressInput/DestinationAddressInput.module.scss
packages/core/src/ui/components/DestinationAddressInput/DestinationAddressInput.tsx

---
update icon on send flow for ada handle not found
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/630/5379164547/index.html) for [e9db3672](https://github.com/input-output-hk/lace/pull/178/commits/e9db3672d3e4ff56ef134d70dabe6ee0e5afa8e0)
| Total | 33     | 3      | 0       | 0     | 36    | ❌     |

fix: update icon on send flow for ada handle not found

---

apps/browser-extension-wallet/src/components/Banner/Banner.module.scss
apps/browser-extension-wallet/src/components/Banner/Banner.tsx
apps/browser-extension-wallet/src/features/dapp/components/Connect.module.scss
apps/browser-extension-wallet/src/features/dapp/components/Connect.tsx

---
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/634/5380864923/index.html) for [b2ee7c04](https://github.com/input-output-hk/lace/pull/175/commits/b2ee7c04cb81637571514fc72acc22f03dd9ea1d)
| Total …

fix(extension): add test id into the banner icon, fix popup mode styling

---

packages/ui/src/design-system/box/box.component.tsx
packages/ui/src/design-system/grid/grid.component.tsx
packages/ui/src/design-system/grid/grid.css.ts
packages/ui/src/design-system/index.ts
packages/ui/src/design-system/pie-chart/pie-chart.stories.tsx
packages/ui/src/design-system/transaction-summary/index.ts
packages/ui/src/design-system/transaction-summary/transaction-summary-address.component.tsx
packages/ui/src/design-system/transaction-summary/transaction-summary-amount.component.tsx
packages/ui/src/design-system/transaction-summary/transaction-summary-metadata.component.tsx
packages/ui/src/design-system/transaction-summary/transaction-summary-other.component.tsx
packages/ui/src/design-system/transaction-summary/transaction-summary.css.ts
packages/ui/src/design-system/transaction-summary/transaction-summary.stories.tsx
packages/ui/src/design-tokens/colors.data.ts
packages/ui/src/design-tokens/theme/dark-theme.css.ts
packages/ui/src/design-tokens/theme/light-theme.css.ts

---
```jsx
import { TransactionSummary } from '@lace/ui';
<TransactionSummary.Address 
label="Address"         
address="addr1q998xresx3rr0d...65uqvzlalu" />
<TransactionSummary.Amount label="Sent" amount="102.00 ADA" fiatPrice="84.45 USD" />
<TransactionSummary.Metadata
label="Metadata"
text="Ut condimentum enim pulvinar, consequat nunc vitae, feugiat nisl. Vestibulum elementum condiment congue et nam quis ipsum diam."
/>
<TransactionSummary.Other label="Label" text="Text" />
```
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/658/5393721754/index.html) for [4c042090](https://github.com/input-output-hk/lace/pull/185/commits/4c04209008c09768f490e1a20943b354a4b37e97)
|       | …

feat(ui): create <TransactionSummary /> component

---

packages/cardano/src/wallet/lib/build-transaction-props.ts

---
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/779/5448276562/index.html) for [bb24e3ea](https://github.com/input-output-hk/lace/pull/214/commits/bb24e3ea0d5f0bf4cf2d15d410219617fa70cc17)
| Total …

fix: remove handle sign when building transaction

---

packages/core/src/ui/components/WalletAddresses/WalletAddressItem.module.scss

---
Fix address overflow in the address book
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/815/5464060277/index.html) for [8c378ba1](https://github.com/input-output-hk/lace/pull/225/commits/8c378ba1b7095ba2b12c69890c31aa8c91b1067d)

fix: address overflow in address book

---

packages/core/src/ui/components/AddressCard/AddressCard.module.scss

---
This PR adds ellipsis to text overflow on wallet name.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/826/5468410333/index.html) for [ba2b81ee](https://github.com/input-output-hk/lace/pull/229/commits/ba2b81ee218fab074d1b3aa3ec0194d10c399786)

fix: add css for text overflow

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json
apps/browser-extension-wallet/src/release-notes/1_3_0.tsx

Post-release cherry-pick 1/3
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/913/5521581229/index.html) for [05840aca](https://github.com/input-output-hk/lace/pull/249/commits/05840aca1cff898f71dfa9e45f7f436dc7f918b3)
| Total | 34     | 2      | 0       | 0     | 36    | ❌     |

chore(extension): bump to 1.3.0

---

apps/browser-extension-wallet/src/release-notes/1_3_0.tsx

Post-release cherry-pick 2/2
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/927/5523997117/index.html) for [202b42c8](https://github.com/input-output-hk/lace/pull/255/commits/202b42c849d7d3e1176618da049cc0177ebd192e)
| Total | 32     | 4      | 0       | 0     | 36    | ❌     |

chore(extension): updated release notes

---

apps/browser-extension-wallet/src/lib/scripts/background/requestAccess.ts
apps/browser-extension-wallet/src/lib/scripts/background/services/dappService.ts

Allows DApps to be removed from settings
[LW-7504]: https://input-output.atlassian.net/browse/LW-7504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/989/5554174757/index.html) for [8e4ed98e](https://github.com/input-output-hk/lace/pull/275/commits/8e4ed98ecb9440d469a161da38a5013f92c5d6e8)

fix: remove authorized dapp

---

packages/staking/src/features/drawer/StakePoolConfirmation.tsx
packages/staking/src/features/i18n/translations/en.ts
packages/staking/src/features/overview/DelegationCard.tsx
packages/staking/src/features/overview/Overview.tsx
packages/staking/src/features/staking/Navigation.tsx

Add tags to elements for e2e tests
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1112/5653321043/index.html) for [2d9b3641](https://github.com/input-output-hk/lace/pull/309/commits/2d9b3641c6242784bb9c5f16bc35cd47ad02957b)

LW-7654 add tags for 2e tests

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json
apps/browser-extension-wallet/src/release-notes/1_3_1.tsx

Post release cherry-pick 1/3
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1118/5657550273/index.html) for [d2483821](https://github.com/input-output-hk/lace/pull/312/commits/d2483821bdfeea0e1bf9eee10a74960432b33710)

chore(extension): bump to 1.3.1

---

apps/browser-extension-wallet/src/lib/translations/en.json

Post release cherry-pick 2/3
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1119/5658465667/index.html) for [19bb9855](https://github.com/input-output-hk/lace/pull/313/commits/19bb98556d73e39df83caeb56826d1d7529dcf0a)

chore(extension): updated text in banner for multidelegation (#287)

---

packages/common/src/ui/components/Drawer/DrawerNavigation.module.scss

---
Simple fix enabled title visibility but blocked back button on modal, reversing change

test(extension): drawer title fix blocked back button, reversing

---

.github/workflows/e2e-tests-linux.yml
.github/workflows/e2e-tests-win.yml
.github/workflows/smoke-tests.yml

---
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1143/5668261062/index.html) for [2f35131e](https://github.com/input-output-hk/lace/pull/317/commits/2f35131ef54714f0348006aa08a03a3f41b9152f)
| Total …

test(extension): e2e - bump ubuntu version to 22.04 for gh runners

---

packages/staking/src/features/drawer/StakePoolDetail.tsx
packages/staking/src/features/drawer/StakePoolDetails.tsx
packages/staking/src/features/drawer/StakePoolPreferences.tsx
packages/staking/src/features/i18n/translations/en.ts
packages/staking/src/features/i18n/types.ts
packages/staking/src/features/modals/ChangingPreferencesModal.tsx
packages/staking/src/features/modals/StakingModal.module.scss
packages/staking/src/features/modals/StakingModal.tsx
packages/staking/src/features/modals/index.ts
packages/staking/src/features/staking/Navigation.tsx
packages/staking/src/features/staking/StakingView.tsx
packages/staking/src/features/store/stakingStore.ts
packages/staking/src/features/store/types.ts
packages/ui/src/design-system/sub-navigation/sub-navigation.component.tsx

- https://input-output.atlassian.net/browse/LW-7544
- https://input-output.atlassian.net/browse/LW-7638
- https://input-output.atlassian.net/browse/LW-7660
- https://input-output.atlassian.net/browse/LW-7661
- https://input-output.atlassian.net/browse/LW-7662
---
Scope described by linked tasks above.
Improved the Subnavigation component by enabling it to support controlled mode.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1158/5674099506/index.html) for [925a24bf](https://github.com/input-output-hk/lace/pull/305/commits/925a24bf40a99940ad272bd225a951692ef59e7d) …

feat(staking,ui): Preferences modal, bug fixes

---

apps/browser-extension-wallet/src/utils/validators/__tests__/address-book.test.ts
apps/browser-extension-wallet/src/utils/validators/address-book.ts
yarn.lock

---
Extract payment credentials and include it in verifying ownership of the user handles. 
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/1166/5678439075/index.html) for [4c185693](https://github.com/input-output-hk/lace/pull/298/commits/4c1856934b8fb390c5e123f52d4f92cb10c16bd5)

Feat: Adds payment keys comparison to handle owner verification

---

packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx

---
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1287/5748532220/index.html) for [c49e9229](https://github.com/input-output-hk/lace/pull/349/commits/c49e92290d32d2d10fc2f7f6085045bfc7e4a57a)
| Total …

feat: changes feature flag in core components

---

apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressBook/AddressBook.tsx
packages/common/src/index.ts
packages/common/src/ui/components/Timeline/Timeline.module.scss
packages/common/src/ui/components/Timeline/Timeline.tsx
packages/common/src/ui/components/Timeline/index.tsx
packages/core/src/ui/components/WalletAddresses/WalletAddressItem.tsx
packages/core/src/ui/components/WalletSetup/WalletSetupStepLayout.module.scss
packages/core/src/ui/components/WalletSetup/WalletSetupStepLayout.tsx

---
Move the Timeline component into the common package  and reuse
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1412/5813217202/index.html) for [1a0f0a1e](https://github.com/input-output-hk/lace/pull/357/commits/1a0f0a1e3ffed362d8eeb7da613bf346326dbfb8)
| Total | 34     | 2      | 0       | 0     | 36    | ❌     |

refactor: move timeline component to common package and reuse

---

packages/cardano/src/ui/components/StakePoolSearch/StakePoolSearch.tsx
packages/common/src/ui/components/Search/Search.tsx
packages/core/src/ui/components/MnemonicWordsAutoComplete/MnemonicWordsAutoComplete.tsx

---
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1407/5809938662/index.html) for [caafa7f6](https://github.com/input-output-hk/lace/pull/379/commits/caafa7f66815d1356a0f4122fd36eacbc6445b3c)
| Total …

refactor(all): change dropdownClassName to popupClassName

---

apps/browser-extension-wallet/src/lib/translations/en.json
packages/staking/src/features/i18n/translations/en.ts

[LW-7963]: https://input-output.atlassian.net/browse/LW-7963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1474/5858429818/index.html) for [6afd28c5](https://github.com/input-output-hk/lace/pull/399/commits/6afd28c5dc4865aaee089055e9c95a496c978653)
| Total | 33     | 2      | 0       | 0     | 35    | ❌     |

fix: update stakepool search placeholder

---

apps/browser-extension-wallet/manifest.json

- ✅ [JIRA](https://input-output.atlassian.net/browse/LW-8150)
- 🚧 Proper tests implemented:  only tested manually
- ✅ Screenshots added.
---
Set `all_frames` to `true` for the two scripts injected by Lace
I tested manually only.  I would need guidance to implement an automated test.
and calling CIP-30 from the iframe works
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1666/5956203485/index.html) for [d3de9c29](https://github.com/input-output-hk/lace/pull/443/commits/d3de9c292693123784dbef0c252a99c3907bcdaf)
| Total | 33     | 2      | 0       | 0     | 35 …

fix(extension): enable injection in all frames [LW-8150]

---

apps/browser-extension-wallet/src/features/address-book/components/AddressChangeDetail.module.scss
apps/browser-extension-wallet/src/features/address-book/components/AddressChangeDetail.tsx
packages/common/src/ui/components/Timeline/Timeline.module.scss

---
This PR fixes the broken margin in the timeline module.
Check both onboarding flow and address handle change flow.
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1676/5963390000/index.html) for [20d508fc](https://github.com/input-output-hk/lace/pull/445/commits/20d508fc3d92096c8e3ac80414fd0a630d54382e)

fix(extension): onboarding flow timeline style broken

---

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/MetadataInput.module.scss
packages/common/src/ui/components/Form/Input/Input.module.scss
packages/common/src/ui/components/Search/Search.module.scss
packages/core/src/ui/components/DestinationAddressInput/DestinationAddressInput.module.scss
packages/core/src/ui/components/DestinationAddressInput/DestinationAddressInput.tsx
packages/core/src/ui/components/EditAddressForm/EditAddressForm.module.scss
packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx

---
- Add the padding on the elements we can control and delete unused transforms. 
- Go to send flow, paste an existing address in the input for the destination address, make sure the padding is correct. 
- Try and test pasting and writing in different inputs. 
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1812/6034375270/index.html) for [8df55c7e](https://github.com/input-output-hk/lace/pull/450/commits/8df55c7ea0a96a46bb60d85e31d483e0a76432f0)

[LW-8175] Destination input alignment issues in sending flow

---

apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.test.ts
apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.test.ts
apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.ts
apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx

---
This PR resolves issues found in the PostHog pre-release regression test.
Re-run failing scenarios from PostHog regression.
n/a
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1858/6052503856/index.html) for [f4dfffea](https://github.com/input-output-hk/lace/pull/480/commits/f4dfffeae109d6492809436ba18fd37ef67560c1)
| Total | 33     | 2      | 0       | 0     | 35    | ❌     |

[LW-8221] PostHog regression fixes

---

apps/browser-extension-wallet/.env.defaults

---
Update development cardano-services urls to the latest recommended.
Tests to be done in #580 with new SDK (versioned endpoints).

chore(extension): update cardano-services dev env urls

---

packages/ui/src/design-system/message/message.css.ts
packages/ui/src/design-system/password-box/password-box-button.css.ts
packages/ui/src/design-system/password-box/password-box-input.css.ts

---
---
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2288/6353983728/index.html) for [a836b3b3](https://github.com/input-output-hk/lace/pull/591/commits/a836b3b33b65fe0cd0df89d22430e71bfd405db6)
| Total …

fix(ui): improve message and password components

---

apps/browser-extension-wallet/src/dapp-connector.tsx

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2451/6470342066/index.html) for [50530ffc](https://github.com/input-output-hk/lace/pull/630/commits/50530ffc1b4b58ba2a4b8f85967dc76e75d1cad9)

fix(extension): add missing posthog providers to dapp connector

---

packages/staking/src/features/browse-pools/PortfolioBar.tsx
packages/staking/src/features/drawer/StakePoolDetails.tsx
packages/staking/src/features/drawer/preferences/PoolDetailsCard/PoolDetailsCard.css.ts
packages/staking/src/features/drawer/preferences/PoolDetailsCard/PoolDetailsCard.stories.tsx
packages/staking/src/features/drawer/preferences/PoolDetailsCard/PoolDetailsCard.tsx
packages/staking/src/features/drawer/preferences/PoolDetailsCard/PoolDetailsCardData.css.ts
packages/staking/src/features/drawer/preferences/PoolDetailsCard/PoolDetailsCardData.tsx
packages/staking/src/features/drawer/preferences/StepPreferencesContent.tsx
packages/staking/src/features/i18n/translations/en.ts
packages/staking/src/features/i18n/types.ts
packages/staking/src/features/modals/ChangingPreferencesModal.tsx
packages/staking/src/features/staking/Navigation.tsx
packages/staking/src/features/store/delegationPortfolioStore/index.ts
packages/staking/src/features/store/delegationPortfolioStore/selectors.ts
packages/staking/src/features/store/delegationPortfolioStore/stateMachine/atomicStateMutators.ts
packages/staking/src/features/store/delegationPortfolioStore/stateMachine/index.ts
packages/staking/src/features/store/delegationPortfolioStore/stateMachine/processExpandedViewCases.ts
packages/staking/src/features/store/delegationPortfolioStore/stateMachine/processPopupViewCases.ts
packages/staking/src/features/store/delegationPortfolioStore/stateMachine/types.ts
packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
packages/staking/src/features/theme/colors.ts

---
Set of improvements and refactoring around PoolDetailsCard.
To be tested as a part of #589 
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2498/6484518285/index.html) for [59c95e1f](https://github.com/input-output-hk/lace/pull/638/commits/59c95e1f61e32875dfc42a4fbde952c7b5c38617)

feat(staking): improvements for the PoolDetailsCard

---

apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmTransaction.module.scss
apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmTransaction.tsx
apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmTransactionContent.tsx
apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/VotingProceduresContainer.tsx
apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/utils.ts
apps/browser-extension-wallet/src/lib/translations/en.json
packages/core/.storybook/preview.js
packages/core/src/index.ts
packages/core/src/ui/components/VotingProcedures/VotingProcedures.stories.ts
packages/core/src/ui/components/VotingProcedures/VotingProcedures.tsx
packages/core/src/ui/components/VotingProcedures/index.ts
packages/ui/package.json
packages/ui/src/design-system/index.ts
packages/ui/src/design-system/metadata/index.ts
packages/ui/src/design-system/metadata/metadata-link.component.tsx
packages/ui/src/design-system/metadata/metadata.component.tsx
packages/ui/src/design-system/metadata/metadata.css.ts
packages/ui/src/design-system/metadata/metadata.stories.tsx
packages/ui/src/design-system/text-link/index.ts
packages/ui/src/design-system/text-link/text-link.component.tsx
packages/ui/src/design-system/text-link/text-link.css.ts
packages/ui/src/design-system/text-link/text-link.stories.tsx
packages/ui/src/design-tokens/colors.data.ts
packages/ui/src/design-tokens/theme/dark-theme.css.ts
packages/ui/src/design-tokens/theme/light-theme.css.ts

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2632/6590452737/index.html) for [5b7cde84](https://github.com/input-output-hk/lace/pull/655/commits/5b7cde845e80be5ede125423301dcbf3d0570b80)

feat(extension): voting procedures

---

.github/workflows/e2e-tests-linux.yml
.github/workflows/smoke-tests.yml
apps/browser-extension-wallet/.env.defaults
apps/browser-extension-wallet/.env.example

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2700/6643005336/index.html) for [c36231de](https://github.com/input-output-hk/lace/pull/667/commits/c36231de8e045e925de282b1fd0523b7cee5093c)
| Total | 0      | 32     | 0       | 0     | 32    | ❌     |

chore: modify sanchonet urls

---

apps/browser-extension-wallet/src/components/AddressesDiscoveryOverlay/AddressesDiscoveryOverlay.tsx

---
---
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2831/6746556772/index.html) for [bcbb1a73](https://github.com/input-output-hk/lace/pull/700/commits/bcbb1a73374ce8e657693c75eb11b3487232f17f)
| Total …

fix(extension): hide addresses discovery modal

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json
apps/browser-extension-wallet/src/components/Announcement/Announcement.tsx
apps/browser-extension-wallet/src/lib/translations/en.json
apps/browser-extension-wallet/src/release-notes/default.tsx

Increasing lace version to support next release

feat(extension): update lace version and default release note

---

apps/browser-extension-wallet/src/lib/translations/en.json

https://input-output.atlassian.net/browse/LW-9023

feat(extension): [LW-9023] rename wallet sync to hd wallet sync

---

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/store/store.ts

---
Takes in account he rows. 
Scenario 1:
Restore wallet with ADA handle.
Click Send button.
Add 2 bundles.
Remove 1st bundle.
Scenario 2:
Restore wallet with ADA handle.
Click Send button.
Add 2 bundles (1st with tADA, 2nd with some token).
Remove 2nd bundle.

[LW-9082] fixes handle undefined in bundle deletion

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json

Increasing lace version to support next release

chore(extension): update lace version v1.8.0

---

apps/browser-extension-wallet/src/stores/slices/wallet-activities-slice.ts
apps/browser-extension-wallet/src/utils/__tests__/get-transaction-total-amount.test.ts
apps/browser-extension-wallet/src/utils/__tests__/own-input-resolver.test.ts
apps/browser-extension-wallet/src/utils/get-transaction-total-amount.ts
apps/browser-extension-wallet/src/utils/mocks/test-helpers.tsx
apps/browser-extension-wallet/src/utils/own-input-resolver.ts
apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/__tests__/pending-tx-transformer.test.ts
apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/__tests__/tx-history-transformer.test.ts
apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/common-tx-transformer.ts
apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/pending-tx-transformer.ts
apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/tx-history-transformer.ts

---
This PR changes how the total transaction amount is calculated to consider the difference of the wallet's own inputs and outputs, this way it will not account for foreign inputs.

[LW-9198]- Incorrect send amount in activity list

---

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx

---
Use `navigator.hid.addEventListener('disconnect')` listener to detected when HW is disconnected

fix(extension): [LW-9075] listen to HID disconnect event

---

apps/browser-extension-wallet/src/hooks/__tests__/useFetchCoinPrice.test.ts

chore(extension): add test for useFetchCoinPrice

---

packages/staking/.storybook/main.ts
packages/staking/package.json
yarn.lock

---
`yarn && yarn dev` from `packages/staking`, storybook should run and be accessible 
[LW-9618]: https://input-output.atlassian.net/browse/LW-9618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(staking): fix LW-9618 storybook

---

apps/browser-extension-wallet/.env.defaults
apps/browser-extension-wallet/.env.developerpreview

Update Lace to use `dev-mainnet` instead of `dev-perf-mainnet`

chore: update dev mainnet url

---

packages/core/src/ui/components/WalletSetup/WalletSetupConfirmationDialogProvider.tsx
packages/ui/src/design-tokens/theme/dark-theme.css.ts

---
Fix the zIndex of the backdrop of the modal. 
Trigger the modal and check the menu is behind the backdrop.

fix: dialogue title and description to be white on dark ui

---

apps/browser-extension-wallet/.env.defaults

---
Use e2e run from `main` nightly vs this to benchmark
Additional testing to come after, pending results
[LW-9568]: https://input-output.atlassian.net/browse/LW-9568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: implement new cluster

---

.github/workflows/smoke-tests.yml

test(extension): apply workaround for smoke tests

---

apps/browser-extension-wallet/src/lib/translations/en.json
apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolsTable/StakePoolsTable.tsx
packages/staking/src/features/BrowsePools/BrowsePools.tsx
packages/staking/src/features/i18n/translations/en.ts
packages/staking/src/features/i18n/types.ts

---
set proper translations on the app and package levels
[LW-9634]: https://input-output.atlassian.net/browse/LW-9634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(extension): add missing tooltips for new stake pool table headers

---

packages/core/src/ui/components/WalletSetup/WalletSetupRegisterStep.tsx
packages/ui/src/design-system/radio-button/radio-button.component.tsx
packages/ui/src/design-system/radio-button/radio-button.css.ts
packages/ui/src/design-system/radio-button/radio-button.stories.css.ts
packages/ui/src/design-system/radio-button/radio-button.stories.tsx
packages/ui/src/design-tokens/colors.data.ts
packages/ui/src/design-tokens/theme/dark-theme.css.ts
packages/ui/src/design-tokens/theme/light-theme.css.ts

---
could be tested by running storybook on the ui package level
[LW-9759]: https://input-output.atlassian.net/browse/LW-9759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(extension): fix focus and click on label for radio button

---

apps/browser-extension-wallet/src/hooks/useWalletManager.ts
apps/browser-extension-wallet/src/lib/wallet-api-ui.ts
packages/cardano/src/wallet/index.ts
packages/cardano/src/wallet/lib/hardware-wallet.ts

---
This PR fixes DApp transaction signing using a Trezor hardware wallet. Also it fixes Trezor connection / communication in general since it was broken in the latest `main`

fix(extension): fix trezor integration and DApp tx signing with Trezor

---

apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolDetails/TransactionSuccess.tsx

---
Use proper translation key.
Reproducible only for non multi-staking scenario (use proper HW device and `USE_MULTI_DELEGATION_STAKING_LEDGER` or `USE_MULTI_DELEGATION_STAKING_TREZOR`  should be set to `false`)
[LW-7488]: https://input-output.atlassian.net/browse/LW-7488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(extension): fix subtitle for staking success drawer

---

apps/browser-extension-wallet/src/components/DropdownMenu/DropdownMenu.tsx

- [ x] JIRA - LW-9902
---
- delete unused variable for the one that's require
Run lace and trigger the menu

[LW-9902] delete variable that does not exist with isDropdownMenuOpen

---

apps/browser-extension-wallet/.env.developerpreview

Align dev preview env file with latest from `main` branch

chore: align dev preview env with stable

---

apps/browser-extension-wallet/src/hooks/useWalletManager.ts
apps/browser-extension-wallet/src/views/browser-view/features/settings/components/ShowPassphraseDrawer.tsx

[LW-9891]: https://input-output.atlassian.net/browse/LW-9891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(extension): [LW-9891] show recovery phrase

---

apps/browser-extension-wallet/src/features/delegation/components/DelegationLayout.tsx
apps/browser-extension-wallet/src/features/delegation/components/Staking.tsx
packages/cardano/src/ui/components/StakePoolStatusLogo/StatusLogo.tsx
packages/staking/src/features/BrowsePools/StakePoolsList/StakePoolCellRenderer.css.ts

---
This pr addresses changes requested by SDET introduced in https://github.com/input-output-hk/lace/pull/931
[LW-9552]: https://input-output.atlassian.net/browse/LW-9552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(extension): resolve sdet comments

---

apps/browser-extension-wallet/src/components/DropdownMenu/DropdownMenu.tsx

---
This task ensures that the chevron icon in user menu is updated to reflect its state correctly.

fix(extension): update chevron icon in user menu [LW-100045]

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json

Update the browser extension's version for release v.1.9

chore(extension): update lace version v1.9.0

---

apps/browser-extension-wallet/src/lib/translations/en.json

---
Update save recovery phrase onboarding text

feat: update save recovery phrase onboarding text

---

apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
packages/core/src/ui/components/WalletSetup/WalletSetupStepLayout.tsx
packages/core/src/ui/components/WalletSetupRevamp/WalletSetupMnemonicStepRevamp/MnemonicWordsAutoCompleteRevamp.tsx
packages/core/src/ui/components/WalletSetupRevamp/WalletSetupMnemonicStepRevamp/MnemonicWordsConfirmInputRevamp.tsx
packages/core/src/ui/components/WalletSetupRevamp/WalletSetupMnemonicStepRevamp/index.ts
packages/core/src/ui/components/WalletSetupRevamp/WalletSetupNamePasswordStepRevamp.tsx
packages/core/src/ui/components/WalletSetupRevamp/index.ts

---
Revert changes to the multi-wallet onboarding flow

fix: revert changes to multi-wallet onboarding flow

---

apps/browser-extension-wallet/src/lib/translations/en.json
apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx
packages/core/src/ui/components/WalletSetupRevamp/WalletSetupConnectHardwareWalletStepRevamp.tsx
packages/core/src/ui/components/WalletSetupRevamp/WalletSetupSelectAccountsStepRevamp.tsx
packages/core/src/ui/components/WalletSetupRevamp/index.ts

---
- Remove legal and analytics from the timeline steps on hardware wallet flow.
- Remove the create loader and all done page from the hardware wallet flow to better match the revamped onboarding design.
Follow the hardware wallet onboarding flow

fix: update hardware wallet flow to better match revamped onboarding

---

apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingSkeleton.tsx

---
Padding added for right-hand side
N/A
[LW-10059]: https://input-output.atlassian.net/browse/LW-10059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LW-10067]: https://input-output.atlassian.net/browse/LW-10067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(extension,staking): fix right side bottom overlapping [LW-10067]

---

packages/staking/.storybook/main.ts
packages/staking/package.json
yarn.lock

Fix failing Chromatic deployment for Staking package

Fix Chromatic deployment for staking package

---

apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx

---
Checks if wallet is already activated.

[LW-10057] Account activated toast is displayed for already active account

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json

---
Update Lace browser extension version for the release v1.10
[LW-10198]: https://input-output.atlassian.net/browse/LW-10198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Lace browser extension version: v1.10

---

apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsRemoveWallet.tsx

---
Improve remove wallet analytics

fix: improve remove wallet analytics

---

.github/workflows/sonar-cloud.yml
sonar-project.properties

Setup SonarCloud analysis
This is what our current configuration in SonarCloud looks like 
I configure it the same way in sonar-project.properties file

Setup GitHub action for SonarCloud analysis

---

packages/core/src/ui/components/Account/EnableAccountPasswordPrompt/EnableAccountPasswordPrompt.tsx
packages/ui/src/design-system/password-box/password-box-button.component.tsx
packages/ui/src/design-system/password-box/password-box.component.tsx

---
Add button type to prevent enter from triggering onClick and adding onSubmit handler

[LW-10233] Revealing password during account unlocking using "enter" button.

---

apps/browser-extension-wallet/src/lib/translations/en.json
apps/browser-extension-wallet/src/views/browser-view/components/EmptySearch/EmptySearch.module.scss
apps/browser-extension-wallet/src/views/browser-view/components/EmptySearch/EmptySearch.tsx
apps/browser-extension-wallet/src/views/browser-view/components/EmptySearch/index.ts
apps/browser-extension-wallet/src/views/browser-view/components/index.ts
apps/browser-extension-wallet/src/views/browser-view/features/assets/components/Assets.tsx
apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetPortfolioContent.tsx
apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.module.scss
apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/__tests__/AssetsPortfolio.test.tsx

---
Add search text box to tokens page

feat: add search text box to tokens page

---

packages/core/src/ui/components/WalletSetupRevamp/WalletSetupOptionsStepRevamp.module.scss
packages/core/src/ui/components/WalletSetupRevamp/WalletSetupOptionsStepRevamp.tsx

This PR changes the text displayed in the onboarding flow

LW-10255 - update text for term and privacy policy

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json

---
Update Lace browser extension version for the release v1.10
[LW-10198]: https://input-output.atlassian.net/browse/LW-10198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(extension): update lace version v1.10.1

---

.eslintrc.js
apps/browser-extension-wallet/src/features/dapp/components/Connect.tsx
apps/browser-extension-wallet/src/hooks/__tests__/useBuildDelegation.test.ts
apps/browser-extension-wallet/src/lib/scripts/background/util.ts
apps/browser-extension-wallet/src/utils/__tests__/createQueue.test.ts
apps/browser-extension-wallet/src/utils/mocks/fake-api-request.ts
apps/browser-extension-wallet/src/utils/taskQueue.ts
packages/cardano/src/wallet/lib/__tests__/get-block-info-by-hash.test.ts
packages/cardano/src/wallet/lib/__tests__/get-inputs-value.test.ts
packages/cardano/src/wallet/test/mocks/AssetsProviderStub.ts
packages/cardano/src/wallet/test/mocks/TxSubmitProviderFake.ts
packages/common/src/ui/hooks/useFetchImage.ts
packages/core/src/ui/components/SharedWallet/AddCoSigners/AddCoSigners.stories.tsx

---
Disabling the `promise/avoid-new` eslint rule for the whole repo and removing all realted disable comments.

chore(all): disable promise/avoid-new eslint rule

---

apps/browser-extension-wallet/src/features/delegation/components/MultiDelegationStakingPopup.tsx
apps/browser-extension-wallet/src/lib/scripts/migrations/migrations.ts
apps/browser-extension-wallet/src/lib/scripts/migrations/versions/index.ts
apps/browser-extension-wallet/src/lib/scripts/migrations/versions/v1_10_2.ts
apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingContainer.tsx
packages/staking/src/features/BrowsePools/constants.ts
packages/staking/src/features/BrowsePools/index.ts
packages/staking/src/features/BrowsePools/types.ts
packages/staking/src/features/outside-handles-provider/types.ts
packages/staking/src/index.ts

---
[LW-10267]: https://input-output.atlassian.net/browse/LW-10267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [LW-10267] staking persistence local storage

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json

chore: bump version to 1.10.2

---

packages/staking/src/features/BrowsePools/BrowsePoolsPreferencesCard/BrowsePoolsPreferencesCard.stories.tsx
packages/staking/src/features/BrowsePools/constants.ts

---
[LW-10282]: https://input-output.atlassian.net/browse/LW-10282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(staking): [LW-10282] staking storybook build

---

apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/events.ts
apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts
apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/NewRecoveryPhrase.tsx
packages/common/src/analytics/types.ts

---
Adding events for PostHog multi wallet create mode.

feat: log posthog events for multi wallet create

---

apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/events.ts
apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/CreateWallet.test.tsx
apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/NewRecoveryPhrase.tsx
apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/RestoreWallet.test.tsx
apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/tests/utils.tsx
packages/core/src/ui/components/WalletSetupRevamp/WalletSetupStepLayoutRevamp.tsx

---
add toast to multiwallet copy and paste mnemonic

feat: add toast to multiwallet copy and paste

---

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionSummary.tsx
packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
packages/core/src/ui/components/ActivityDetail/TransactionInputOutput.module.scss
packages/core/src/ui/components/ActivityDetail/TransactionInputOutput.tsx
packages/core/src/ui/components/ActivityDetail/TxDetailsList.tsx
packages/core/src/ui/components/ActivityDetail/components/DetailRows.tsx
packages/core/src/ui/components/DappAddressSections/DappAddressSection.tsx
packages/core/src/ui/components/DappAddressSections/DappAddressSections.module.scss
packages/core/src/ui/components/OutputSummary/OutputSummary.module.scss
packages/core/src/ui/components/OutputSummary/OutputSummary.tsx
packages/core/src/ui/components/OutputSummary/OutputSummaryUtils.tsx
packages/core/src/ui/components/OutputSummaryList/OutputSummaryList.tsx
packages/core/src/ui/utils/__tests__/render-address-tag.test.ts
packages/core/src/ui/utils/render-address-tag.tsx
packages/ui/src/design-system/address-tags/address-tag.css.ts
packages/ui/src/design-system/address-tags/address-tags.stories.tsx
packages/ui/src/design-system/address-tags/types.ts
packages/ui/src/design-tokens/colors.data.ts
packages/ui/src/design-tokens/theme/dark-theme.css.ts
packages/ui/src/design-tokens/theme/light-theme.css.ts

---
- Address tag updated to no longer display address name
- Added own or foreign address tag to send flow
- Show address name/handle on transaction confirmation, dapp transaction confirmation and transaction details on activity
- Address tag for own/foreign is displayed in transaction confirmation
- Address tag for own/foreign is displayed in dapp transaction confirmation
- Address tag for own/foreign is displayed in transaction detail
- Address name from address book is displayed in dapp transaction confirmation
- Address name from address book is displayed in transaction detail
- Handle is displayed in transaction confirmation

[LW 10268] Flag addresses as own or foreign on send flow

---

apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/VotingProceduresContainer.tsx
apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/VotingProceduresContainer.test.tsx
apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/__tests__/utils.test.tsx
apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/utils.ts

---
use isRegisteredAsDrep observable available on observable wallet.
same as in https://input-output.atlassian.net/browse/LW-9202
[LW-10236]: https://input-output.atlassian.net/browse/LW-10236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(extension): use drep registration tracker

---

apps/browser-extension-wallet/src/features/dapp/components/SignTransaction.tsx
apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmTransaction.tsx
packages/common/src/analytics/types.ts

---
Add posthog actions on both confirm and cancel external transactions. 
For instance: 
Go to: https://app.preprod.wingriders.com/welcome
Try to create a transaction, and confirm it. 
Do it again and cancel it, you should see `send| confirm transaction | cancel | click`

[LW-10261] add posthog cancel dapp tx events 

---

apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx

---
Resolve missing analytics issue

fix: resolve missing analytics issue

---

packages/core/src/ui/components/ActivityDetail/RewardsDetails.tsx
packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx

---
add space to amount on activity details

fix: add space to amount on activity details

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json

chore: bump manifest and package version

---

apps/browser-extension-wallet/src/features/nfts/components/NftDetail.tsx

---
set wallet avatar on popup

fix: set wallet avatar on popup

---

packages/e2e-tests/src/assert/transactionsPageAssert.ts
packages/e2e-tests/src/elements/transactionsPage.ts
packages/e2e-tests/src/features/TransactionsExtended.feature
packages/e2e-tests/src/features/TransactionsPopup.feature
packages/e2e-tests/src/steps/transactionsSteps.ts
packages/e2e-tests/src/types/transactionStyle.ts
packages/e2e-tests/src/types/transactionType.ts

E2E test for https://input-output.atlassian.net/browse/LW-9914

test(extension): add e2e test for tx list styling

---

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/Form.tsx

---
[LW-10577]: https://input-output.atlassian.net/browse/LW-10577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(extension): remove check for empty assets on add bundle

---

apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/context.tsx
apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/hardware-wallet/context.tsx
apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/context.tsx
packages/core/src/ui/components/ListEmptyState/ListEmptyState.tsx

fix: eliminate lint warnings

---

.github/settings.yml
.github/workflows/chromatic-core.yml
.github/workflows/chromatic-staking.yml
.github/workflows/chromatic-ui.yml
.github/workflows/ci.yml
packages/staking/package.json
packages/staking/tsup.config.ts

Require Chromatic check if content of packages: core, staking, ui is modified in PR or merged to main branch

ci: require chromatic check

---

packages/e2e-tests/src/assert/multidelegation/MultidelegationPageAssert.ts
packages/e2e-tests/src/assert/multidelegation/StakingSuccessDrawerAssert.ts
packages/e2e-tests/src/assert/stakingPageAssert.ts
packages/e2e-tests/src/features/AdaHandleExtended.feature
packages/e2e-tests/src/features/AdaHandleSendExtended.feature
packages/e2e-tests/src/features/AdaHandleSendPopup.feature
packages/e2e-tests/src/features/MultiDelegationPageExtended.part1.feature
packages/e2e-tests/src/features/MultidelegationDelegatedFundsSinglePoolExtended.feature
packages/e2e-tests/src/features/NavigationTopExtended.feature
packages/e2e-tests/src/features/NavigationTopPopup.feature
packages/e2e-tests/src/features/SendTransactionSimpleExtended.part2.feature
packages/e2e-tests/src/features/TokensPageExtended.feature
packages/e2e-tests/src/features/TokensPagePopup.feature
packages/e2e-tests/src/features/TransactionsPopup.feature
packages/e2e-tests/src/features/analytics/AnalyticsEventProperitesExtended.feature
packages/e2e-tests/src/features/analytics/AnalyticsNavigationTopExtended.feature
packages/e2e-tests/src/features/analytics/AnalyticsNavigationTopPopup.feature

test(extension): re-enable some of blocked tests

---

packages/staking/tsup.config.ts
packages/ui/rollup.config.js

https://github.com/vanilla-extract-css/vanilla-extract/issues/771#issuecomment-1249524366

chore: use short identifier for vanilla-extract

---

packages/e2e-tests/src/features/FiatOnRampOffRampBanxaExtended.feature
packages/e2e-tests/src/features/FiatOnRampOffRampBanxaPopup.feature
packages/e2e-tests/src/features/analytics/AnalyticsFiatOnRampOffRamp.feature

test(extension): add test for LW-10638

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json

chore(extension): update lace version v1.12

---

packages/e2e-tests/src/assert/tokensPageAssert.ts
packages/e2e-tests/src/elements/tokensPage.ts
packages/e2e-tests/src/features/TokensPageExtended.feature
packages/e2e-tests/src/features/TokensPagePopup.feature
packages/e2e-tests/src/steps/tokensPageSteps.ts

---
Implement test for token search:
- https://input-output.atlassian.net/browse/LW-10653
- https://input-output.atlassian.net/browse/LW-10328
[LW-10637]: https://input-output.atlassian.net/browse/LW-10637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(extension): lw-10637 implement test for token search

---

packages/translation/src/lib/translations/browser-extension-wallet/cookie-policy.en.ts

---
Update translation files with the new cookie policy.
Open the Cookie Policy drawer from the Lace settings.

feat(extension): [LW-10681] update cookie policy (CookiePolicyDrawer)

---

packages/e2e-tests/src/assert/toastMessageAssert.ts
packages/e2e-tests/src/assert/transactionDetailsAssert.ts
packages/e2e-tests/src/elements/multidelegation/MultidelegationPage.ts
packages/e2e-tests/src/features/OnboardingCreateWallet.feature
packages/e2e-tests/src/features/OnboardingRestoreWallet.feature
packages/e2e-tests/src/features/TokensPageExtended.feature
packages/e2e-tests/src/features/TokensPagePopup.feature
packages/e2e-tests/src/hooks/afterTagHooks.ts
packages/ui/src/design-system/tooltip/tooltip-root.component.tsx

test(extension): maintenance 4th June 2024

---

packages/e2e-tests/src/assert/settings/cookiePolicy.txt
packages/e2e-tests/src/elements/settings/SettingsPage.ts
packages/e2e-tests/src/features/analytics/AnalyticsSettingsExtended.feature
packages/e2e-tests/src/steps/settingsSteps.ts

test(extension): add test for LW-9098

---

packages/core/src/ui/components/SharedWallet/Quorum/QuorumOption.component.tsx
packages/core/src/ui/components/SharedWallet/SharedWalletLayout/SharedWalletLayout.stories.tsx
packages/staking/src/features/BrowsePools/BrowsePoolsPreferencesCard/BrowsePoolsPreferencesCard.tsx
packages/ui/src/design-system/radio-button/radio-button.component.tsx
packages/ui/src/design-system/radio-button/radio-button.css.ts
packages/ui/src/design-system/radio-button/radio-button.stories.tsx

---
- Making it possible to have a custom UI for the radio button component options
- Updated QuorumOption component to use the new feature

feat: allow for custom option rendering in the RadioButtonGroup

---

packages/core/src/ui/components/DappTransaction/DappTransaction.tsx

---
[LW-10716]: https://input-output.atlassian.net/browse/LW-10716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(core): add graceful fallback for asset name decoding

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json

chore(extension): update lace version v1.12.1

---

packages/e2e-tests/src/features/analytics/AnalyticsSettingsExtended.feature
packages/e2e-tests/src/features/analytics/AnalyticsSettingsPopup.feature

test(extension): fix analytics tests for ToS

---

packages/e2e-tests/src/assert/multidelegation/MultidelegationPageAssert.ts
packages/e2e-tests/src/elements/multidelegation/MultidelegationPage.ts
packages/e2e-tests/src/elements/multidelegation/StakePoolGridCard.ts
packages/e2e-tests/src/elements/multidelegation/StakePoolListItem.ts
packages/e2e-tests/src/features/MultiDelegationPageExtended.part2.feature
packages/e2e-tests/src/utils/stakePoolGridContent.ts
packages/e2e-tests/src/utils/stakePoolListContent.ts

test(extension): add tests for LW-10284

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json

chore(extension): update lace version v1.13.0

---

packages/e2e-tests/src/assert/AddNewWalletAssert.ts
packages/e2e-tests/src/elements/MainLoader.ts
packages/e2e-tests/src/elements/addNewWallet/MainModal.ts
packages/e2e-tests/src/elements/menuHeader.ts
packages/e2e-tests/src/elements/onboarding/mainPage.ts
packages/e2e-tests/src/features/AddNewWalletCreate.feature
packages/e2e-tests/src/hooks/beforeTagHooks.ts
packages/e2e-tests/src/steps/AddNewWalletSteps.ts
packages/e2e-tests/src/steps/navigationTopSteps.ts
packages/e2e-tests/wdio.conf.base.ts

test(extension): add tests for LW-9334 and LW-9335

---

packages/core/src/ui/components/WalletSetupRevamp/WalletSetupStepLayoutRevamp.tsx
packages/e2e-tests/src/assert/AddNewWalletAssert.ts
packages/e2e-tests/src/assert/modalAssert.ts
packages/e2e-tests/src/assert/onboarding/onboardingCommonAssert.ts
packages/e2e-tests/src/assert/onboarding/onboardingWalletSetupPageAssert.ts
packages/e2e-tests/src/assert/topNavigationAssert.ts
packages/e2e-tests/src/elements/WalletOption.ts
packages/e2e-tests/src/elements/menuHeader.ts
packages/e2e-tests/src/elements/modal.ts
packages/e2e-tests/src/elements/onboarding/commonOnboardingElements.ts
packages/e2e-tests/src/elements/onboarding/mainPage.ts
packages/e2e-tests/src/elements/onboarding/recoveryPhrasePage.ts
packages/e2e-tests/src/elements/onboarding/walletSetupPage.ts
packages/e2e-tests/src/elements/passwordInput.ts
packages/e2e-tests/src/features/AddNewWalletCreate.feature
packages/e2e-tests/src/features/ForgotPassword.feature
packages/e2e-tests/src/features/OnboardingCreateWallet.feature
packages/e2e-tests/src/features/OnboardingRestoreWallet.feature
packages/e2e-tests/src/features/SettingsPageExtended.feature
packages/e2e-tests/src/features/analytics/AnalyticsOnboardingEvents.feature
packages/e2e-tests/src/hooks/afterTagHooks.ts
packages/e2e-tests/src/hooks/beforeTagHooks.ts
packages/e2e-tests/src/steps/AddNewWalletSteps.ts
packages/e2e-tests/src/steps/menuHeaderSteps.ts
packages/e2e-tests/src/steps/navigationTopSteps.ts
packages/e2e-tests/src/steps/onboardingSteps.ts
packages/e2e-tests/src/types/onboarding.ts
packages/e2e-tests/src/utils/browserPermissionsUtils.ts

test(extension): add tests for wallet creation flow via 'Add new wallet' feature (LW-10827)

---

packages/e2e-tests/package.json
yarn.lock

test(extension): [LW-10849] update Webdriver.io to v8.39.1

---

packages/core/src/docs/transaction-structure.md
packages/core/src/shared-wallets/docs/transaction-structure.md

---
Create documentation for the transaction JSON file structure

feat: create documentation for the transaction JSON file structure

---

.github/workflows/e2e-tests-linux-split.yml
packages/e2e-tests/wdio.conf.base.ts

[LW-10843](https://input-output.atlassian.net/browse/LW-10843)
Bumping regression to 16 runners and rebalancing load.
[LW-10843]: https://input-output.atlassian.net/browse/LW-10843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lw 10843 enhance e2e

---

packages/core/src/shared-wallets/docs/shared-wallet-schema.json
packages/core/src/shared-wallets/docs/shared-wallet-scriptAll-example.json
packages/core/src/shared-wallets/docs/shared-wallet-scriptAny-example.json
packages/core/src/shared-wallets/docs/shared-wallet-scriptNOfK-example.json

This pull request introduces a comprehensive JSON schema for the creation of shared wallets, along with relevant examples. The schema is designed to facilitate the coordination of transactions in a shared wallet environment by defining a clear structure for the JSON files exchanged between cosigners.
•	A new JSON schema has been defined to structure the creation of shared wallets.
•	The schema includes definitions for version, metadata, participants, and NativeScript.
•	Version: Specifies the schema version.
•	Metadata: Contains information such as the creation date, notes, the creator’s public key, and the target chain ID.
•	Participants: Lists the participants in the shared wallet, including their names and corresponding Ed25519KeyHash.
•	NativeScript: Defines the script structure, …

[LW-10833] - Shared wallet schema and examples

---

packages/e2e-tests/src/elements/multidelegation/StakePoolGridCard.ts
packages/e2e-tests/src/elements/multidelegation/StakingPasswordDrawer.ts
packages/e2e-tests/src/features/AddressBookExtended.feature
packages/e2e-tests/src/features/AddressBookPopup.feature
packages/e2e-tests/src/features/DAppConnector.feature
packages/e2e-tests/src/features/DAppConnectorLowFunds.feature
packages/e2e-tests/src/features/HdWalletExtended.feature
packages/e2e-tests/src/features/MultiDelegationPageExtended.part1.feature
packages/e2e-tests/src/features/MultidelegationDelegatedFundsMultiplePoolsExtended.feature
packages/e2e-tests/src/features/MultidelegationDelegatedFundsMultiplePoolsPopup.feature
packages/e2e-tests/src/features/MultidelegationDelegatedFundsSinglePoolExtended.feature
packages/e2e-tests/src/features/NavigationMainExtended.feature
packages/e2e-tests/src/features/NavigationTopExtended.feature
packages/e2e-tests/src/features/NetworkSwitchingExtended.feature
packages/e2e-tests/src/features/NetworkSwitchingPopup.feature
packages/e2e-tests/src/features/SendTransactionMultipleSelectionExtended.feature
packages/e2e-tests/src/features/SendTransactionMultipleSelectionPopup.feature
packages/e2e-tests/src/features/SendTransactionSimpleExtended.part2.feature
packages/e2e-tests/src/features/SendTransactionSimpleExtended.part3.feature
packages/e2e-tests/src/features/SendTransactionSimplePopup.part2.feature
packages/e2e-tests/src/features/SendTransactionSimplePopup.part3.feature
packages/e2e-tests/src/features/TokensPageExtended.feature
packages/e2e-tests/src/features/TokensPagePopup.feature
packages/e2e-tests/src/features/e2e/MultidelegationSwitchingPoolsExtendedE2E.feature

test(extension): test maintenance 5 July 2024

---

apps/browser-extension-wallet/package.json
package.json
packages/core/package.json
packages/staking/package.json
yarn.lock

---
Bumping version of lace ui toolkit to fix the storybook issue with a `colorSchemeDecorator`
No testing is needed.

chore: bump toolkit version

---

apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsWalletBase.tsx
apps/browser-extension-wallet/src/views/browser-view/features/settings/components/__tests__/SettingsWallet.test.tsx
packages/e2e-tests/src/assert/settings/SettingsPageAssert.ts
packages/e2e-tests/src/assert/topNavigationAssert.ts
packages/e2e-tests/src/elements/settings/SettingsPage.ts
packages/e2e-tests/src/elements/tokensPage.ts
packages/e2e-tests/src/elements/transactionsPage.ts
packages/e2e-tests/src/features/AddNewWalletCreate.part2.feature
packages/e2e-tests/src/features/DAppConnector.feature
packages/e2e-tests/src/features/SettingsPageExtended.part1.feature
packages/e2e-tests/src/pageobject/settingsExtendedPageObject.ts
packages/e2e-tests/src/steps/commonSteps.ts
packages/e2e-tests/src/steps/settingsSteps.ts

test(extension): perform test maintenance - 11 July 2024

---

packages/e2e-tests/src/assert/AddNewWalletAssert.ts
packages/e2e-tests/src/assert/onboarding/onboardingCommonAssert.ts
packages/e2e-tests/src/features/AddNewWalletConnect.feature
packages/e2e-tests/src/hooks/beforeTagHooks.ts
packages/e2e-tests/src/steps/AddNewWalletSteps.ts
packages/e2e-tests/src/steps/onboardingSteps.ts
packages/e2e-tests/src/types/onboarding.ts

test(extension): add tests for LW-10962

---

apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolsTable/StakePoolsTable.modules.scss
apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolsTable/StakePoolsTable.tsx
apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolsTable/StakePoolsTableEmpty.module.scss

---
apply same changes as for staking package
enable non multi delegation flow by setting `process.env.USE_MULTI_DELEGATION_STAKING_LEDGER` to be `true` for Ledger devices or `process.env.USE_MULTI_DELEGATION_STAKING_TREZOR` for Trezor

fix(extension): [LW-10865] fix fetching of stake pool for non multi delegation flow

---

.github/shared/build/action.yml
.github/workflows/ci.yml
.github/workflows/e2e-tests-linux-split.yml

[LW-10859](https://input-output.atlassian.net/browse/LW-10859)
Add credentials to Lace build artifact and build upload overwrite.
[LW-10859]: https://input-output.atlassian.net/browse/LW-10859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(extension): add credentials to build artifact check

---

.github/workflows/e2e-tests-linux-split.yml

test(extension): quick fix

---

apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
apps/browser-extension-wallet/src/hooks/useWalletManager.ts
apps/browser-extension-wallet/src/views/browser-view/features/shared-wallet/SharedWallet.tsx
packages/cardano/src/wallet/util/derive-ed25519-key-hash-from-bip32-public-key.ts
packages/cardano/src/wallet/util/index.ts
packages/core/src/shared-wallets/add-shared-wallet/creation-flow/index.ts
packages/core/src/shared-wallets/add-shared-wallet/index.ts
packages/core/src/shared-wallets/add-shared-wallet/main-page-flow/SharedWalletEntry/SharedWalletEntry.stories.tsx
packages/core/src/shared-wallets/index.ts
packages/core/src/shared-wallets/utils/build-shared-wallet-script.ts
packages/core/src/shared-wallets/utils/index.ts

---
This allows support for all quorum rules

feat: support all quorum rules

---

packages/core/src/ui/components/SharedWallet/StartOverDialog/StartOverDialog.tsx
packages/e2e-tests/src/assert/AddNewWalletAssert.ts
packages/e2e-tests/src/elements/addNewWallet/CancelAddingNewWalletDialog.ts
packages/e2e-tests/src/elements/addNewWallet/MainModal.ts
packages/e2e-tests/src/features/AddNewWalletRestore.feature
packages/e2e-tests/src/steps/AddNewWalletSteps.ts

test(extension): add test coverage for LW-10977

---

packages/e2e-tests/src/assert/switchingPoolsModalAssert.ts
packages/e2e-tests/src/features/MultidelegationDelegatedFundsMultiplePoolsExtended.feature
packages/e2e-tests/src/steps/multidelegationSteps.ts

[Jira LW-9642](https://input-output.atlassian.net/browse/LW-9642)
Switching to less pools modal tests

test(extension): Switching to less pools modal tests

---

apps/browser-extension-wallet/src/hooks/useWalletActivities.ts
apps/browser-extension-wallet/src/hooks/useWalletState.ts
apps/browser-extension-wallet/src/stores/selectors/sync-status-selector.ts
apps/browser-extension-wallet/src/stores/slices/wallet-activities-slice.ts
apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/common-tx-transformer.ts
apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/pending-tx-transformer.ts
packages/cardano/src/wallet/types.ts
packages/core/src/shared-wallets/transaction/InfoBar.tsx
packages/core/src/shared-wallets/transaction/types.ts
packages/core/src/shared-wallets/utils/get-shared-wallet-sign-policy.ts
packages/core/src/ui/components/Activity/AssetActivityItem.tsx
packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
packages/core/src/ui/components/Transaction/types.ts
packages/staking/src/features/Drawer/SignConfirmation.tsx
packages/staking/src/features/overview/helpers/hasPendingDelegationTransaction.ts
packages/translation/src/lib/translations/core/en.json

---
[LW-10580]: https://input-output.atlassian.net/browse/LW-10580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add new activity item that is awaiting co-signers

---

packages/e2e-tests/src/assert/multidelegation/MultidelegationDAppIssueModalAssert.ts
packages/e2e-tests/src/elements/multidelegation/MultidelegationDAppIssueModal.ts
packages/e2e-tests/src/elements/multidelegation/MultidelegationPage.ts
packages/e2e-tests/src/features/MultiDelegationPageExtended.part3.feature
packages/e2e-tests/src/fixture/localStorageInitializer.ts
packages/e2e-tests/src/steps/multidelegationSteps.ts
packages/e2e-tests/src/utils/localStorageManager.ts

test(extension): add tests for LW-10853, LW-10855, LW-10857

---

apps/browser-extension-wallet/src/features/delegation/components/MultiDelegationStakingPopup.tsx
apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingContainer.tsx
packages/core/src/shared-wallets/add-shared-wallet/creation-flow/ShareWalletDetails/utils.ts
packages/core/src/shared-wallets/docs/schema/shared-wallet-schema.json
packages/core/src/shared-wallets/docs/schema/shared-wallet-scriptAll-example.json
packages/core/src/shared-wallets/docs/schema/shared-wallet-scriptAny-example.json
packages/core/src/shared-wallets/docs/schema/shared-wallet-scriptNOfK-example.json
packages/core/src/shared-wallets/index.ts
packages/core/src/shared-wallets/transaction/CosignersList.tsx
packages/core/src/shared-wallets/transaction/InfoBar.tsx
packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
packages/core/src/shared-wallets/transaction/index.ts
packages/core/src/shared-wallets/transaction/transaction-details.stories.tsx
packages/staking/.storybook/StakingStorybookProvider.tsx
packages/staking/src/features/BrowsePools/StakePoolsList/StakePoolsList.tsx
packages/staking/src/features/Drawer/StakePoolDetail.tsx
packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationContent.tsx
packages/staking/src/features/outside-handles-provider/types.ts

chore: resolve pr comments for cosign staking tx pr

---

packages/staking/src/features/Drawer/StakePoolDetail.tsx
packages/staking/src/features/Drawer/preferences/StepPreferencesContent.tsx
packages/staking/src/features/staking/StakingPopupView.tsx
packages/staking/src/features/staking/StakingView.tsx

---
[LW-10990]: https://input-output.atlassian.net/browse/LW-10990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(staking): disable all multidelegation related modals

---

packages/core/src/ui/components/ActivityDetail/RewardsDetails.tsx
packages/core/src/ui/components/ActivityDetail/TransactionDetails.module.scss

---
[LW-10095]: https://input-output.atlassian.net/browse/LW-10095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(core): [lw-10095] shorted pool name on activity detail

---

packages/e2e-tests/src/features/MultidelegationDelegatedFundsMultiplePoolsExtended.feature
packages/e2e-tests/src/features/MultidelegationDelegatedFundsMultiplePoolsPopup.feature
packages/e2e-tests/src/features/MultidelegationDelegatedFundsSinglePoolExtended.part2.feature

test(extension): add tests for LW-10582, LW-10584, LW-10586, LW-10588

---

packages/staking/src/features/overview/helpers/hasPendingDelegationTransaction.ts

---
[LW-11067]: https://input-output.atlassian.net/browse/LW-11067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(staking): [lw-11067] fix has pending tx check on staking page

---

apps/browser-extension-wallet/src/views/browser-view/components/QRPublicKeyDrawer/QRPublicKeyDrawer.tsx

---
Fix shared wallet public key error

fix: shared wallet public key error

---

packages/core/src/shared-wallets/utils/has-signed.ts

---
[LW-11146]: https://input-output.atlassian.net/browse/LW-11146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(core): [lw-11146] fix circular deps in core package

---

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Transaction.tsx

---
[LW-11109]: https://input-output.atlassian.net/browse/LW-11109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(extension): [lw-11109] fix escape handler in send flow drawer

---

packages/core/src/ui/utils/__tests__/simple-cipher.test.ts
packages/core/src/ui/utils/secure-random.ts
packages/core/src/ui/utils/simple-cipher.ts

---
Implement a secure random number generation using ` window.crypto.getRandomValues` 
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues

fix(core): replaces Math.Random with window.crypto.getRandomValues implementation in simple-cipher

---

apps/browser-extension-wallet/.env.defaults

Set cardano services url to live

chore(extension): set live urls for cardano services

---

.github/actions/build/app/action.yml
.github/workflows/ci.yml

I'm fixing extension release build by reverting `build/app/action.yml` and creating `release-pkg` job using it.

chore: revert build app action (#1369)

---

.github/workflows/e2e-tests-linux-split.yml

E2e add site pick per env

---

packages/e2e-tests/src/features/analytics/AnalyticsOnboardingEvents.feature
packages/e2e-tests/src/features/e2e/MultidelegationSwitchingPoolsExtendedE2E.feature

Few small fixes:
- blocking LW-7365 because of bug  [LW-11298](https://input-output.atlassian.net/browse/LW-11298)
- small fix to switching modal closing
- fix for LW-7363
[LW-11298]: https://input-output.atlassian.net/browse/LW-11298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(extension): quick fixes

---

apps/browser-extension-wallet/.env.defaults
apps/browser-extension-wallet/.env.developerpreview
apps/browser-extension-wallet/.env.example
apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.test.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/config.ts
apps/browser-extension-wallet/test/__mocks__/set-env-vars.js
apps/browser-extension-wallet/webpack-utils.js
packages/e2e-tests/src/elements/onboarding/mainPage.ts
packages/e2e-tests/src/steps/analyticsSteps.ts
packages/e2e-tests/src/steps/onboardingSteps.ts

This PR is best reviewed as individual commits, since there's a refactor of the variable name first, then the value change.
Make a dev build then observe the HTTP requests to `https://e.lw.iog.io/` succeed, and find no requests going to `https://eu.posthog.com/`

LW-11276 Update configuration to use Lace PostHog proxy

---

.github/actions/test/e2e/action.yml
.github/workflows/e2e-tests-linux-split.yml

Adding optional tags param to our e2e regression flow:

E2e regression workflow add optional tags param

---

packages/e2e-tests/src/features/analytics/AnalyticsNavigationTopExtended.feature
packages/e2e-tests/src/features/analytics/AnalyticsNavigationTopPopup.feature
packages/e2e-tests/src/steps/multidelegationSteps.ts

[E2E tests job](https://github.com/input-output-hk/lace/actions/runs/10503409217)
---

test(extension): add minor fixes for tests

---

apps/browser-extension-wallet/package.json
packages/cardano/package.json
packages/cardano/src/wallet/lib/__tests__/get-auxiliary-data.test.ts
packages/cardano/src/wallet/lib/get-auxiliary-data.ts
packages/staking/package.json
yarn.lock

LW11301 fix: Transaction message is non-compliant with CIP-20

---

apps/browser-extension-wallet/src/views/browser-view/features/settings/components/CustomSubmitApiDrawer.tsx
packages/e2e-tests/src/assert/settings/CustomSubmitApiAssert.ts
packages/e2e-tests/src/assert/settings/SettingsPageAssert.ts
packages/e2e-tests/src/assert/toastMessageAssert.ts
packages/e2e-tests/src/elements/menuHeader.ts
packages/e2e-tests/src/elements/settings/CustomSubmitApiDrawer.ts
packages/e2e-tests/src/features/SettingsPageExtended.part2.feature
packages/e2e-tests/src/features/SettingsPagePopup.part2.feature
packages/e2e-tests/src/features/analytics/AnalyticsSettingsExtended.feature
packages/e2e-tests/src/features/analytics/AnalyticsSettingsPopup.feature
packages/e2e-tests/src/pageobject/settingsExtendedPageObject.ts
packages/e2e-tests/src/steps/commonSteps.ts
packages/e2e-tests/src/steps/settingsSteps.ts

test(extension): add basic tests for Custom Submit API

---

apps/browser-extension-wallet/src/lib/scripts/background/cache-wallets-address.ts

fix: lw-11406

---

packages/e2e-tests/src/features/DAppConnectorLowFunds.feature
packages/e2e-tests/src/features/DAppConnectorPopup.feature
packages/e2e-tests/src/features/e2e/SendTransactionDappE2E.feature

Fix wallet locking because of wrong tags in some DApp features.
Branch tests results [GH here](https://github.com/input-output-hk/lace/actions/runs/10718948268), [Allure here](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/all/linux/chrome/586/index.html#)

E2e fix locking wallets issue

---

apps/browser-extension-wallet/src/utils/format-string.ts

---
Make whitespace replacement global
Follow instruction listed in ticket
[LW-11478]: https://input-output.atlassian.net/browse/LW-11478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(extension): [LW-11478]

---

packages/core/src/ui/components/Nft/NftList.module.scss

---
revert numeric to numeric word css syntax
Open both popup + extended view, assert layout correct
[LW-11487]: https://input-output.atlassian.net/browse/LW-11487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(extension): lw-11487 broken nft list layout

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json

Version bump to v1.16.0 ahead of next release

chore: bump manifest version v1.16.0

---

packages/e2e-tests/src/features/analytics/AnalyticsOnboardingEvents.feature
packages/e2e-tests/src/hooks/beforeTagHooks.ts
packages/e2e-tests/src/steps/onboardingSteps.ts

test(extension): minor test fixes

---

apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/ChooseRecoveryMethod.tsx
apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/steps/ChooseRestoreMethod.tsx

---
Correct the color using ui-toolkit typography element
Check create + restore flow show correct colors

fix: [LW-11513] incorrect title color in onboarding recovery choices

---

apps/browser-extension-wallet/src/views/browser-view/features/settings/components/PaperWalletSettingsDrawer.tsx
packages/e2e-tests/src/assert/settings/EnterYourPasswordDrawerAssert.ts
packages/e2e-tests/src/assert/settings/SaveYourPaperWalletDrawerAssert.ts
packages/e2e-tests/src/assert/settings/SecureYourPaperWalletDrawerAssert.ts
packages/e2e-tests/src/elements/onboarding/SecureYourPaperWalletPage.ts
packages/e2e-tests/src/elements/settings/EnterYourPasswordDrawer.ts
packages/e2e-tests/src/elements/settings/SaveYourPaperWalletDrawer.ts
packages/e2e-tests/src/elements/settings/SecureYourPaperWalletDrawer.ts
packages/e2e-tests/src/elements/settings/SettingsPage.ts
packages/e2e-tests/src/features/SettingsGeneratePaperWallet.feature
packages/e2e-tests/src/hooks/beforeTagHooks.ts
packages/e2e-tests/src/pageobject/settingsExtendedPageObject.ts
packages/e2e-tests/src/steps/settingsSteps.ts
packages/e2e-tests/wdio.conf.base.ts

test(extension): add tests for Settings - Generate paper wallet

---

apps/browser-extension-wallet/package.json
yarn.lock

---
Bump posthog version to latest

chore: bump posthog version to latest

---

apps/browser-extension-wallet/src/views/browser-view/features/sign-message/SignMessageDrawer.tsx
apps/browser-extension-wallet/src/views/browser-view/features/sign-message/useDrawerConfiguration.tsx
packages/core/src/ui/components/WalletOwnAddressesDropdown/WalletOwnAddressDropdown.tsx
packages/e2e-tests/src/assert/settings/MessageSigningAllDoneDrawerAssert.ts
packages/e2e-tests/src/assert/settings/MessageSigningConfirmationDrawerAssert.ts
packages/e2e-tests/src/assert/settings/MessageSigningInputDrawerAssert.ts
packages/e2e-tests/src/elements/menuHeader.ts
packages/e2e-tests/src/elements/settings/MessageSigningAllDoneDrawer.ts
packages/e2e-tests/src/elements/settings/MessageSigningConfirmationDrawer.ts
packages/e2e-tests/src/elements/settings/MessageSigningInputDrawer.ts
packages/e2e-tests/src/features/SettingsGeneratePaperWallet.feature
packages/e2e-tests/src/features/SignMessage.feature
packages/e2e-tests/src/hooks/beforeTagHooks.ts
packages/e2e-tests/src/steps/AccountsSteps.ts
packages/e2e-tests/src/steps/MessageSigningSteps.ts
packages/e2e-tests/src/steps/navigationTopSteps.ts
packages/e2e-tests/wdio.conf.base.ts

test(extension): add tests for Sign Message feature

---

packages/e2e-tests/src/elements/onboarding/walletSetupPage.ts
packages/e2e-tests/src/steps/analyticsSteps.ts

test(extension): fix tests for analytics

---

apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/DropdownMenuOverlay.tsx
apps/browser-extension-wallet/src/components/MainMenu/MainFooter.tsx
apps/browser-extension-wallet/src/routes/ExtensionRoutes.tsx
apps/browser-extension-wallet/src/views/browser-view/components/SideMenu/SideMenu.tsx
apps/browser-extension-wallet/src/views/browser-view/routes/index.tsx

---
Hide staking and add shared wallet options when in shared wallet

fix: hide staking and add shared wallet options when in shared wallet

---

.github/workflows/ci.yml
.github/workflows/e2e-tests-linux-split.yml

test(extension): update allure publish action to v2.7.1

---

apps/browser-extension-wallet/.env.defaults
apps/browser-extension-wallet/.env.developerpreview
apps/browser-extension-wallet/.env.example
packages/e2e-tests/src/assert/commonAssert.ts

---
Update terms of use link
Check link still active
[LW-11597]: https://input-output.atlassian.net/browse/LW-11597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update terms of use link

---

apps/browser-extension-wallet/src/lib/scripts/types/storage.ts
apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.test.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
apps/browser-extension-wallet/src/utils/mocks/test-helpers.tsx
apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsPreferences/SettingsPreferences.tsx
packages/common/src/analytics/types.ts
packages/translation/src/lib/translations/browser-extension-wallet/en.json

- [W-11516] JIRA - \<[link](https://input-output.atlassian.net/browse/LW-11516)>
---
We need to identify a cohort of users who are willing to be receive have new features remotely enabled that require testing for us to gain confidence before rolling out to unsuspecting users. 
Add a toggle in settings which will set a person property 'opted_in_beta' which we can then filter on.

feat: add toggle on settings for beta program opt in

---

apps/browser-extension-wallet/src/lib/scripts/background/util.ts
apps/browser-extension-wallet/src/utils/constants.ts

---
Fix proportions on dApp connector for hardware wallet

fix: fix dApp connector proportions for hardware wallets

---

apps/browser-extension-wallet/src/views/nami-mode/NamiView.tsx
apps/browser-extension-wallet/src/views/nami-mode/index.tsx
packages/nami/src/adapters/account.test.ts
packages/nami/src/adapters/account.ts
packages/nami/src/features/outside-handles-provider/types.ts
packages/nami/src/ui/app/pages/wallet.tsx
packages/nami/src/ui/indexMain.tsx

fix: delete wallet from popup

---

packages/e2e-tests/src/utils/consoleManager.ts

LW-11706 Improve readabilty of service worker console log

---

apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts
packages/common/package.json
packages/common/src/index.ts
packages/common/src/stringifyLogger.ts
yarn.lock

LW-11724 Stringify objects in service worker console log

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json

chore(extension): update lace version v1.17.0

---

packages/nami/src/ui/app/hw/connect-hw.tsx

---
Accept both SatoshiLabs and "Trezor Company" as manufacturer name

feat(nami): accept trezor safe 5 device

---

packages/nami/src/adapters/wallet.test.ts
packages/nami/src/adapters/wallet.ts
packages/nami/src/config/config.ts
packages/nami/src/ui/app/pages/settings.tsx
packages/nami/src/ui/indexMain.tsx

LW-11751
---
Do not display change password button for HW wallets

feat(nami): disable password change for hw wallet

---

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx
packages/common/src/analytics/types.ts

JIRA - [LW-11737](https://input-output.atlassian.net/browse/LW-11737)
---
[LW-11737]: https://input-output.atlassian.net/browse/LW-11737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(extension): send shared wallets co-sign confirmation click

---

packages/nami/src/ui/app/pages/send.tsx

---
[LW-11749]: https://input-output.atlassian.net/browse/LW-11749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-11749] adjust width for send btn

---

packages/nami/src/ui/app/components/assetPopoverDiff.tsx
packages/nami/src/ui/app/pages/send.tsx

---
[LW-11750]: https://input-output.atlassian.net/browse/LW-11750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-11750] adjust max width for assets list

---

packages/nami/src/ui/app/pages/dapp-connector/signTx.tsx

---
[LW-11759]: https://input-output.atlassian.net/browse/LW-11759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-11759] handle invalid pass while signing dapp tx

---

packages/nami/src/ui/app/components/confirmModal.tsx

---
[LW-11763]: https://input-output.atlassian.net/browse/LW-11763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-11763] remove duplicated confirm tx event for hw

---

apps/browser-extension-wallet/src/lib/scripts/background/cip30.ts

---
Handle missing storage entry

fix(extension): some storage variables might not be available

---

apps/browser-extension-wallet/src/styles/index.scss

---
[LW-11746]: https://input-output.atlassian.net/browse/LW-11746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-11746] align main loader in nami mode

---

packages/nami/src/ui/app/pages/send.tsx

---
[LW-11755]: https://input-output.atlassian.net/browse/LW-11755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-11755] adjust height of assets list in send flow

---

packages/nami/src/ui/app/components/asset.tsx
packages/nami/src/ui/app/components/collectible.tsx
packages/nami/src/ui/app/components/collectiblesViewer.tsx
packages/nami/src/ui/app/components/styles.css

---
[LW-11747]: https://input-output.atlassian.net/browse/LW-11747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-11747] add line clamp styling for tokens and collectibles

---

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/HeaderView.tsx

---
[LW-11767]: https://input-output.atlassian.net/browse/LW-11767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-11767] close co sign drawer before resetting tx related states

---

apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/DropdownMenuOverlay.tsx

---
[LW-11783]: https://input-output.atlassian.net/browse/LW-11783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-11783] do not show add shared wallet btn for hw

---

apps/browser-extension-wallet/src/features/settings/components/Settings.tsx
apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsLayout.tsx
packages/nami/src/adapters/account.ts

---
[LW-11768]: https://input-output.atlassian.net/browse/LW-11768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-11768] hide switch to nami mode option when using shared wallet

---

apps/browser-extension-wallet/src/lib/wallet-api-ui.ts

---
Prevent wrong password entry from logging into the browser

fix: prevent wrong password entry from logging into the browser

---

packages/common/src/analytics/types.ts
packages/e2e-tests/src/assert/settings/SettingsPageAssert.ts
packages/e2e-tests/src/elements/settings/SettingsPage.ts
packages/e2e-tests/src/features/analytics/AnalyticsSettingsExtended.feature
packages/e2e-tests/src/features/analytics/AnalyticsSettingsPopup.feature
packages/e2e-tests/src/steps/settingsSteps.ts

test(extension): add tests for LW-11798 and LW-11799

---

packages/e2e-tests/src/steps/commonSteps.ts
packages/e2e-tests/src/utils/networkManager.ts

test(extension): fix network throttling

---

packages/cardano/src/wallet/lib/blockfrost/blockfrost-asset-provider.ts

---
- images and descriptions for FTs or NFTs can be either strings, arrays of strings, or undefined
- in these instances, convert all to either undefined, or as a single concatenated string
[LW-11789]: https://input-output.atlassian.net/browse/LW-11789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(cardano): add string array concatenation for blockfrost asset provider

---

apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/steps/EnterPgpPrivateKey.tsx
packages/core/src/ui/components/Password/Password.tsx

fix: prevent PasswordBox and UncontrolledPasswordBox from default submission [LW-11807]

---

apps/browser-extension-wallet/package.json
apps/browser-extension-wallet/webpack.common.js
apps/browser-extension-wallet/webpack.sw.prod.js
packages/nami/rollup.config.js
packages/staking/tsup.config.ts
rollup.config.js
yarn.lock

---
See commit
Smoke tests should be sufficient
UI script, error in `common` package
UI script, error in `staking` package
Service worker script, error in `cardano` package
[LW-11795]: https://input-output.atlassian.net/browse/LW-11795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: fix source maps

---

packages/e2e-tests/src/assert/multidelegation/MultidelegationPageAssert.ts
packages/e2e-tests/src/assert/transactionDetailsAssert.ts
packages/e2e-tests/src/steps/AccountsSteps.ts
packages/e2e-tests/src/steps/analyticsSteps.ts
packages/e2e-tests/src/utils/postHogAnalyticsUtils.ts

test(extension): minor fixes

---

apps/browser-extension-wallet/src/views/browser-view/routes/index.tsx

feat(extension): remove voting center from application build

---

apps/browser-extension-wallet/src/providers/AnalyticsProvider/onChain.ts

Handle error thrown while manually aborting lock request in analytics provider
---
[LW-11809]: https://input-output.atlassian.net/browse/LW-11809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-11809]: handle error thrown while switching between modes

---

packages/nami/src/ui/app/components/asset.tsx
packages/nami/src/ui/app/pages/send.tsx

---
[LW-11808]: https://input-output.atlassian.net/browse/LW-11808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-11808]: set min width for assets icons

---

packages/e2e-tests/src/features/AddNewWalletCreatePaperWallet.feature

test(extension): fix LW-11341

---

packages/nami/src/adapters/transactions.ts

---
[LW-11881]: https://input-output.atlassian.net/browse/LW-11881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [LW-11881] fix crashing tx history after account switch

---

apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/RenameFolderDrawer.tsx
packages/e2e-tests/src/assert/NftRenameFolderAsserts.ts

fix: [LW-7198] fix invalid title for NFT folder drawer

---

apps/browser-extension-wallet/src/hooks/useCollateral.ts

---
Undo the setting the tx to undefined during error.

fix: prevent modal from closing on collateral reconfirmation

---

packages/e2e-tests/src/data/EducationalArticles.ts
packages/e2e-tests/src/features/AddNewWalletRestore.feature

test(extension): fix unstable tests

---

apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/context.tsx
apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/context.tsx
apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsSecurity.tsx

[LW-11866](https://input-output.atlassian.net/browse/LW-11866)
[LW-11866]: https://input-output.atlassian.net/browse/LW-11866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [LW-11866]

---

apps/browser-extension-wallet/webpack.common.prod.js

chore: drop sourcemaps in production releases

---

apps/browser-extension-wallet/sentry.js

[LW-11934]: https://input-output.atlassian.net/browse/LW-11934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(extension): [LW-11934] populate sentry user field

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/src/lib/scripts/background/content.ts

---
Change the way we load the script injecting the Lace API.
Please test the extension across all reported Dexes.

fix(extension): improve Dapp API injection performance

---

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/CoinInput/useSelectedCoins.tsx

fix: prevent empty ada value in fiat conversion [LW-11970]

---

apps/browser-extension-wallet/.env.defaults
apps/browser-extension-wallet/.env.developerpreview
apps/browser-extension-wallet/.env.example

---
Prepare anchor url for Preprod GovTool instance.

chore: prepare for preprod govtools instance

---

packages/nami/src/ui/app/components/transactionBuilder.tsx

fix(nami): await submit collateral

---

apps/browser-extension-wallet/src/features/dapp/components/SignData.tsx
apps/browser-extension-wallet/src/features/dapp/components/SignTransaction.tsx
apps/browser-extension-wallet/src/lib/wallet-api-ui.ts

---
Ensure field is not undefined

fix(extension): avoid undefined form field passed to Buffer

---

packages/nami/src/ui/app/pages/send.tsx

---
Asset callbacks used state values but did not list them as dependency.
Another issue is that state was mutated directly before setting it.

fix(nami): missing value dependency in useCallback

---

packages/nami/src/ui/app/pages/dapp-connector/signTx.tsx

---
[LW-11996]: https://input-output.atlassian.net/browse/LW-11996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(nami): [lw-11996] remove duplicated imports

---

apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/CoinInput/__tests__/useSelectedCoins.test.ts
apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/CoinInput/useSelectedCoins.tsx
apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingInfo/StakingInfo.module.scss
apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingInfo/StakingInfo.tsx
apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingInfo/Stats.module.scss
packages/staking/src/features/overview/StakingInfoCard/StakingInfoCard.module.scss
packages/staking/src/features/overview/StakingInfoCard/StakingInfoCard.tsx
packages/staking/src/features/overview/StakingInfoCard/Stats.module.scss

---
[LW-12001]: https://input-output.atlassian.net/browse/LW-12001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LW-12005]: https://input-output.atlassian.net/browse/LW-12005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-12001, lw-12005] fix token input symbol

---

packages/staking/src/features/overview/RegisterAsDRepBanner/RegisterAsDRepBanner.tsx

---
Adjust the FAQ link now that the slug no longer focusses on sanchonet and broadly talks about all networks
Check link redirects to correct FAQ article
[LW-12002]: https://input-output.atlassian.net/browse/LW-12002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(extension): adjust govtool faq link

---

.github/workflows/ci.yml
.github/workflows/e2e-tests-linux-split.yml

Test/update GitHub actions versions

---

packages/e2e-tests/src/assert/addressBook/AddressFormAssert.ts
packages/e2e-tests/src/features/analytics/AnalyticsOnboardingEvents.feature

Test/maintenance 20 Dec 2024

---

packages/nami/src/ui/app/pages/settings.tsx

---
[LW-11879]: https://input-output.atlassian.net/browse/LW-11879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(nami): [lw-11879] dapp compatibility improvements

---

packages/e2e-tests/src/assert/multidelegation/DelegateYourVotingPowerBannerAssert.ts
packages/e2e-tests/src/data/EducationalArticles.ts
packages/e2e-tests/src/elements/multidelegation/DelegateYourVotingPowerBanner.ts
packages/e2e-tests/src/features/EmptyStatesExtended.feature
packages/e2e-tests/src/features/EmptyStatesPopup.feature
packages/e2e-tests/src/features/MultiDelegationPageExtended.part3.feature
packages/e2e-tests/src/features/MultiDelegationPagePopup.feature
packages/e2e-tests/src/features/MultidelegationDelegatedFundsMultiplePoolsExtended.feature
packages/e2e-tests/src/features/MultidelegationDelegatedFundsMultiplePoolsPopup.feature
packages/e2e-tests/src/steps/commonSteps.ts
packages/e2e-tests/src/steps/multidelegationSteps.ts
packages/staking/src/features/overview/RegisterAsDRepBanner/RegisterAsDRepBanner.tsx
packages/translation/src/lib/translations/browser-extension-wallet/en.json

test(extension): add tests for "Delegate your voting power" banner

---

apps/browser-extension-wallet/src/lib/scripts/background/config.ts
apps/browser-extension-wallet/src/providers/ExperimentsProvider/config.ts
apps/browser-extension-wallet/src/providers/ExperimentsProvider/types.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
packages/cardano/src/wallet/lib/providers.ts

Workaround for https://github.com/blockfrost/blockfrost-backend-ryo/issues/231
---

feat: use drep provider active status override proxy

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json

chore: bump manifest version v1.18.1

---

packages/cardano/src/wallet/lib/hardware-wallet.ts

---
Remove model filters, and keep only vendor ID.
Test using previously "supported" and "new" ledger devices.
[LW-12027]: https://input-output.atlassian.net/browse/LW-12027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [lw-12027] allow connecting any ledger device

---

packages/e2e-tests/src/assert/transactionDetailsAssert.ts
packages/e2e-tests/src/assert/walletAddressPageAssert.ts
packages/e2e-tests/src/features/analytics/AnalyticsOnboardingEvents.feature
packages/e2e-tests/src/steps/analyticsSteps.ts
packages/e2e-tests/src/steps/waletAddressPageSteps.ts
packages/e2e-tests/src/utils/postHogAnalyticsUtils.ts

test maintenance 8 Jan 2025

---

apps/browser-extension-wallet/src/lib/scripts/background/onError.ts

cherry-pick of single commit from #1641 targeting `main` instead of RC

fix: prevent displaying poor connection pill for 404 responses

---

packages/e2e-tests/src/assert/topNavigationAssert.ts
packages/e2e-tests/src/assert/transactionDetailsAssert.ts
packages/e2e-tests/src/features/DAppConnector.feature
packages/e2e-tests/src/features/TransactionsExtended.part2.feature
packages/e2e-tests/src/steps/sendTransactionSimpleSteps.ts

Test/maintenace 16 Jan 2025

---

apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/components/ProjectDetail/index.tsx
apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/components/SimpleView/SimpleViewContent/index.tsx
apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/components/SimpleView/SimpleViewFilters/index.tsx
packages/common/src/analytics/types.ts

---
Add analytics to dapp explorer

feat: [LW-11885] add analytics to dapp explorer

---

packages/e2e-tests/src/features/e2e/SendTransactionBundlesE2E.feature

test(extension): fix LW-4121

---

apps/browser-extension-wallet/src/lib/scripts/background/__tests__/nami-migration-runner.test.ts
apps/browser-extension-wallet/src/lib/scripts/background/nami-migration-runner.ts

When Nami has one mnemonic wallet and one hardware wallet, and Lace has a matching hardware wallet, the migration tool falsely detects this as an existing mnemonic wallet, and attempts to add the account to an existing wallet.
---
Refactor migration tool to consider mnemonic and hw wallets separately.
Check if at least one mnemonic account is overlapping and use the walletId.
If none overlapping, consider this a new mnemonic wallet.
Refactored hw wallet import to be uniform regardless if it's a new mnemonic
wallet or an existing one.
Added unit test for this scenario.

fix(extension): migration having one overlapping hw wallet - LW-12135

---

apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/featureFlagPayloadsSchema.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/index.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/index.ts
apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/components/SimpleView/SimpleViewFilters/CategoryChip/mapper.tsx
apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/services/api/categories/index.ts
apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/services/api/d-app/index.ts
packages/translation/src/lib/translations/browser-extension-wallet/en.json

---
- hide Dapps belonging to disallowed categories
- hide Dapp category from navigation if it belongs to disallowed categories
- update Dapp Radar tooltip copy
Play with feature flag configs and test all the categories.

feat(extension): allow hiding dapp categories based on feature flag config [LW-12147]

---

packages/e2e-tests/src/features/MultiDelegationPageExtended.part2.feature

test(extension): fix LW-9996

---

packages/nami/src/ui/app/components/historyViewer.tsx

feat: display end txs message in the activity tab in nami mode

---

packages/e2e-tests/src/elements/multidelegation/DelegateYourVotingPowerBanner.ts
packages/e2e-tests/src/features/DAppConnector.feature
packages/e2e-tests/src/features/MultidelegationDelegatedFundsSinglePoolExtended.part2.feature
packages/e2e-tests/src/features/TokensPagePopup.part1.feature

test(extension): test maintenance 27 Jan 2025

---

packages/e2e-tests/src/features/OwnTagsExtended.feature
packages/e2e-tests/src/features/OwnTagsPopup.feature
packages/e2e-tests/src/features/TransactionsExtended.part1.feature
packages/e2e-tests/src/features/TransactionsExtended.part2.feature
packages/e2e-tests/src/features/TransactionsPopup.part1.feature
packages/e2e-tests/src/features/TransactionsPopup.part2.feature
packages/e2e-tests/src/features/e2e/StakingInitialFundsE2E.feature

test(extension): block tests affected by LW-12099

---

apps/browser-extension-wallet/src/components/MainMenu/MainFooter.tsx
apps/browser-extension-wallet/src/lib/scripts/background/config.ts
apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts
apps/browser-extension-wallet/src/lib/scripts/types/feature-flags.ts
apps/browser-extension-wallet/src/lib/scripts/types/storage.ts
apps/browser-extension-wallet/src/providers/ExperimentsProvider/config.ts
apps/browser-extension-wallet/src/providers/ExperimentsProvider/context.tsx
apps/browser-extension-wallet/src/providers/ExperimentsProvider/types.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/index.ts
apps/browser-extension-wallet/src/views/browser-view/components/SideMenu/SideMenu.tsx
apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/components/DAppExplorer.tsx
apps/browser-extension-wallet/src/views/browser-view/features/dapp/explorer/components/SimpleView/SimpleViewFilters/CategoryChip/mapper.tsx

---
Turn on dapp explorer by default
- DApp Explorer should be visible in menu from the begining
- When refreshing DApp Explorer page it should appear without a delay (no empty page)

feat: initialize feature flag values and payloads from cache [LW-12191]

---

packages/e2e-tests/wdio.conf.chrome.ts

test(extension): set Chrome version to v132

---

apps/browser-extension-wallet/src/features/nami-migration/migration-tool/cross-extension-messaging/lace-migration-client.extension.ts
apps/browser-extension-wallet/src/features/nami-migration/migration-tool/cross-extension-messaging/lace/create-lace-migration-open-listener.ts
apps/browser-extension-wallet/src/features/nami-migration/migration-tool/cross-extension-messaging/lace/create-lace-migration-ping-listener.ts
apps/browser-extension-wallet/src/lib/scripts/background/content.ts
apps/browser-extension-wallet/src/lib/scripts/background/inject.ts
apps/browser-extension-wallet/src/lib/scripts/background/onUpdate.ts
apps/browser-extension-wallet/src/lib/scripts/background/services/expose.ts
apps/browser-extension-wallet/src/lib/scripts/background/storage/migrations.ts
apps/browser-extension-wallet/src/lib/scripts/migrations/migrations.ts
packages/cardano/src/wallet/lib/blockfrost-address-discovery.ts
packages/cardano/src/wallet/lib/providers.ts
packages/core/src/shared-wallets/add-shared-wallet/creation-flow/ShareWalletDetails/utils.ts

fix: [LW-12136] use debug log level instead of info

---

apps/browser-extension-wallet/src/features/nfts/components/Nfts.module.scss
apps/browser-extension-wallet/src/features/nfts/components/Nfts.tsx
packages/common/src/ui/components/VirtualisedGrid/VirtualisedGrid.tsx
packages/core/src/ui/components/Nft/NftGrid.tsx
packages/core/src/ui/components/Nft/NftItem.module.scss

---
[LW-12153]: https://input-output.atlassian.net/browse/LW-12153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-12153] style nft folder to maintain its height if empty

---

packages/e2e-tests/.eslintrc.cjs
packages/e2e-tests/src/assert/transaction/transactionAssetSelectionAssert.ts
packages/e2e-tests/src/elements/newTransaction/tokenSelectionPage.ts
packages/e2e-tests/src/features/SendTransactionMultipleSelectionExtended.feature
packages/e2e-tests/src/features/SendTransactionMultipleSelectionPopup.feature
packages/e2e-tests/src/steps/sendTransactionSimpleSteps.ts
packages/e2e-tests/src/utils/virtualizedListUtils.ts

Introduces generic and configurable utils to scan through virtualized lists and retrieve items as specific index.

chore: fix virtualized lists tests [LW-12151]

---

apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/RenameFolderDrawer.tsx

fix: [lw-7632] fix rename nft folder feat

---

apps/browser-extension-wallet/sentry.js
apps/browser-extension-wallet/src/hooks/useFatalError.ts

chore: add logging for fatal errors [LW-12187]

---

packages/e2e-tests/src/elements/NFTs/nftCreateFolderPage.ts
packages/e2e-tests/src/features/NFTsFoldersExtended.part1.feature
packages/e2e-tests/src/features/NFTsFoldersExtended.part3.feature
packages/e2e-tests/src/features/NFTsFoldersPopup.part1.feature
packages/e2e-tests/src/features/NFTsFoldersPopup.part2.feature

test(extension): unblock tests affected by LW-7632

---

apps/browser-extension-wallet/src/hooks/useTxHistoryLoader.ts
apps/browser-extension-wallet/src/hooks/useWalletActivities.ts
packages/cardano/src/wallet/lib/tx-history-loader.ts
packages/nami/src/adapters/transactions.ts
packages/nami/src/features/outside-handles-provider/types.ts

---
[LW-12326]: https://input-output.atlassian.net/browse/LW-12326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-12326] fix permanent loader on activities page

---

packages/core/src/ui/utils/voting-procedures-mock.ts

---
[LW-12325]: https://input-output.atlassian.net/browse/LW-12325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-12325] fix code duplications reported by sonarcloud

---

apps/browser-extension-wallet/src/views/browser-view/features/voting-beta/components/VotingCenterBanner/VotingCenterBanner.tsx
packages/e2e-tests/src/assert/VotingCenterPageAssert.ts
packages/e2e-tests/src/assert/commonAssert.ts
packages/e2e-tests/src/assert/educationalListAssert.ts
packages/e2e-tests/src/assert/menuMainAssert.ts
packages/e2e-tests/src/elements/VotingCenterPage.ts
packages/e2e-tests/src/elements/menuMainExtended.ts
packages/e2e-tests/src/elements/menuMainPopup.ts
packages/e2e-tests/src/features/VotingCenterExtended.feature
packages/e2e-tests/src/features/VotingCenterPopup.feature
packages/e2e-tests/src/features/analytics/AnalyticsVotingCenterExtended.feature
packages/e2e-tests/src/features/analytics/AnalyticsVotingCenterPopup.feature
packages/e2e-tests/src/hooks/beforeTagHooks.ts
packages/e2e-tests/src/page/extendedView.ts
packages/e2e-tests/src/page/popupView.ts
packages/e2e-tests/src/steps/VotingCenterSteps.ts
packages/e2e-tests/src/steps/commonSteps.ts
packages/e2e-tests/src/utils/pageUtils.ts
packages/e2e-tests/wdio.conf.base.ts

test(extension): add tests for Voting Center [LW-12336]

---

packages/e2e-tests/src/features/NavigationTopExtended.feature

test(extension): fix-LW-2319

---

apps/browser-extension-wallet/sentry.js
apps/browser-extension-wallet/src/lib/scripts/background/onError.ts
apps/browser-extension-wallet/src/lib/scripts/background/services/utilityServices.ts

- don't catch console errors in production
Partial implementation of [LW-12377](https://input-output.atlassian.net/browse/LW-12377)
[LW-12377]: https://input-output.atlassian.net/browse/LW-12377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(extension): use debug statements in favour of error

---

apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/PinExtension.tsx
packages/e2e-tests/src/assert/PinWalletExtensionNotificationAssert.ts
packages/e2e-tests/src/elements/PinWalletExtensionNotification.ts
packages/e2e-tests/src/features/OnboardingCreateWallet.part2.feature
packages/e2e-tests/src/features/OnboardingRestoreWallet.part1.feature
packages/e2e-tests/src/steps/onboardingSteps.ts

test(extension): add tests for LW-10208

---

.github/actions/build/app/action.yml
.github/shared/build/action.yml
.github/workflows/ci.yml

---
Add Firefox addon build in CI pipeline

feat: build firefox addon in CI [LW-12372]

---

apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts

---
this name used as Logger context and it might contain PII since it's set by the user

fix: replace user-specified wallet 'name' with a hardcoded name

---

packages/e2e-tests/src/assert/onboarding/onboardingMainPageAssert.ts
packages/e2e-tests/src/features/MultidelegationDelegatedFundsMultiplePoolsExtended.feature
packages/e2e-tests/src/features/MultidelegationDelegatedFundsMultiplePoolsPopup.feature
packages/e2e-tests/src/features/MultidelegationDelegatedFundsSinglePoolPopup.feature
packages/e2e-tests/src/features/e2e/MultidelegationSwitchingPoolsExtendedE2E.feature

test(extension): unblock some tests

---

apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts

chore(extension): remove debug logs

---

apps/browser-extension-wallet/package.json
apps/browser-extension-wallet/webpack.app.prod.js
apps/browser-extension-wallet/webpack.common.app.js
apps/browser-extension-wallet/webpack.common.prod.js
package.json
yarn.lock

---
See Jira ticket
[LW-12393]: https://input-output.atlassian.net/browse/LW-12393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: sentry sourcemap upload once

---

apps/browser-extension-wallet/sentry.js
apps/browser-extension-wallet/src/lib/scripts/background/index.ts
apps/browser-extension-wallet/src/lib/scripts/background/onStorageChange.ts
apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts
apps/browser-extension-wallet/src/lib/scripts/types/feature-flags.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/config.ts
apps/browser-extension-wallet/src/utils/catch-and-brand-extension-api-error.ts
packages/cardano/src/wallet/lib/providers.ts
packages/common/src/AppLogger.ts
packages/common/src/ui/lib/index.ts
packages/common/src/ui/lib/is-network-error.ts
packages/core/src/shared-wallets/add-shared-wallet/creation-flow/ShareWalletDetails/utils.ts
packages/core/src/shared-wallets/docs/schema/README.md
packages/nami/.storybook/mocks/cardano-sdk.mock.ts
packages/nami/src/adapters/transactions.ts
packages/nami/src/ui/app/components/transaction.tsx
packages/nami/src/ui/app/hw/select-account.tsx
packages/nami/src/ui/app/hw/trezorTx.tsx
packages/nami/src/ui/app/pages/dapp-connector/enable.tsx
packages/nami/src/ui/app/pages/dapp-connector/signData.tsx
packages/nami/src/ui/app/pages/dapp-connector/signTx.tsx
packages/nami/src/ui/app/pages/dapp-connector/signTxUtil.ts
packages/nami/src/ui/app/pages/send.tsx
packages/staking/src/features/BrowsePools/hooks/useBrowsePoolsPersistence.tsx
packages/staking/src/features/Drawer/TransactionFail.tsx
packages/staking/src/features/store/delegationPortfolioStore/stateMachine/stateTreeUtilities.ts

---
- improve logs
- add AppLogger.error capture in Sentry (enabled by Feature Flag)
See the ticket description.

feat(all): Integrate Sentry exception throwing in logger.error [LW-12377]

---

apps/browser-extension-wallet/src/utils/catch-and-brand-extension-api-error.ts
apps/browser-extension-wallet/webpack.app.prod.js
apps/browser-extension-wallet/webpack.common.app.js

---
Improve the `ExtensionApiError` and its logging.
N/A

chore(extension): fix ExtensionApiError logging and add originalError [LW-12490]

---

sonar-project.properties

Align project version in sonar-project.properties file with the manifest.json, so Sonarcloud has properly set New Code definition.
> New code is code that you've recently added or modified. To ensure you focus your efforts on the right lines of code, Sonar will highlight technical debt (issues, code coverage, etc) in the new code.
>
>In pull requests, all code changes are considered new code. For branch and IDE, the new code definition setting tells Sonar which part of the code is considered new. 
https://docs.sonarsource.com/sonarqube-cloud/core-concepts/clean-as-you-code/about-new-code/

chore: bump-up project version in sonarcloud properties file

---

apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/DappTransactionContainer.tsx

---
Lace wrongly identifying whether user is a DRep due to limited tx history.
Temporary commenting out a modal with warning.

fix: [lw-12517] hide not registered as drep modal

---

packages/e2e-tests/src/elements/modal.ts
packages/e2e-tests/src/features/AdaHandleSendExtended.feature

test(extension): fix LW-7073

---

apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmTransaction.tsx
apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/utils.ts
apps/browser-extension-wallet/src/providers/TxWitnessRequestProvider/context.tsx
packages/cardano/src/wallet/lib/cardano-wallet.ts
packages/common/src/ui/components/Button/Button.tsx

---
See commit history/messages.
Please see the ticket. I suggest full regression for Dapp transactions.

fix(extension): dapp connector transaction error [LW-12406]

---

packages/translation/src/lib/translations/shared-wallets/en.json

fix: [LW-12503] rename button label

---

apps/browser-extension-wallet/src/dapp-connector.tsx
apps/browser-extension-wallet/src/views/BitcoinDappConnectorView.tsx

---
Reject Dapp interaction in bitcoin-mode

fix: reject dapp interaction in bitcoin mode

---

apps/browser-extension-wallet/src/views/BitcoinDappConnectorView.tsx
packages/translation/src/lib/translations/browser-extension-wallet/en.json

---
Close dapp connector window when close is clicked and update text

fix: close dapp connector window when close is clicked

---

apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/ReviewTransaction.module.scss
apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/ReviewTransaction.tsx
apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/SendContainer.tsx
apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/SendStepOne.tsx

---
- Add arrow button to bitcoin-mode send flow on popup.
- Improve text alignment

fix: improve bitcoin mode send flow component

---

apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/TransactionSuccess.tsx

---
Improve transaction hash box alignment

fix: improve transaction hash box alignment

---

apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/SendStepOne.tsx

---
Unify bitcoin numeric display logic with ada mode

fix: unify bitcoin numeric display logic with ada mode

---

packages/e2e-tests/src/features/e2e/SendNftPopupE2E.feature
packages/e2e-tests/src/steps/nftsCommonSteps.ts

test(extension): fix LW-2514 [LW-12405]

---

apps/browser-extension-wallet/src/views/browser-view/features/settings/components/CustomSubmitApiDrawer.tsx
packages/e2e-tests/src/elements/settings/CustomSubmitApiDrawer.ts
packages/e2e-tests/src/features/AddNewWalletCreatePaperWallet.feature
packages/e2e-tests/src/features/SettingsPageExtended.part2.feature
packages/e2e-tests/src/features/SettingsPagePopup.part2.feature
packages/e2e-tests/src/features/analytics/AnalyticsOnboardingEvents.feature

test(extension): maintenance 11 Apr 2025 [LW-12649]

---

apps/browser-extension-wallet/src/hooks/__tests__/useWalletManager.test.tsx
apps/browser-extension-wallet/src/hooks/useWalletManager.ts

fix: delete wallet now updates wallet profile icon for next active wallet

---

apps/browser-extension-wallet/src/components/DropdownMenu/DropdownMenu.tsx
apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/DropdownMenuOverlay.tsx
apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/AddNewBitcoinWalletLink.tsx
apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/AddNewWalletLink.tsx
apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/AddressBookLink.tsx
apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/SettingsLink.tsx
apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/SignMessageLink.tsx
packages/core/src/ui/components/WalletOwnAddressesDropdown/WalletOwnAddressDropdown.tsx
packages/e2e-tests/src/elements/settings/MessageSigningInputDrawer.ts

---
This PR probably does not address the original issue but fixes the no-op set state in the same area.

fix(extension): DropdownMenu errors [LW-12618]

---

packages/nami/src/ui/indexInternal.tsx

---
Correct path for nami-mode dapp-connector sign tx

fix: correct path for nami-mode dapp-connector

---

packages/e2e-tests/src/assert/commonAssert.ts
packages/e2e-tests/src/features/NetworkRequestsCounting.feature
packages/e2e-tests/src/hooks/beforeTagHooks.ts
packages/e2e-tests/src/steps/commonSteps.ts
packages/e2e-tests/src/steps/onboardingSteps.ts
packages/e2e-tests/src/utils/networkManager.ts
packages/e2e-tests/wdio.conf.base.ts

test(extension): add test LW-12663

---

packages/e2e-tests/package.json
packages/e2e-tests/src/utils/firefoxUtils.ts
yarn.lock

test(extension): wdio 8.44.0

---

apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmTransaction.tsx

---
[LW-12652]: https://input-output.atlassian.net/browse/LW-12652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [lw-12652] remove parenthesis char in the dapp tx popup markup

---

packages/e2e-tests/src/features/SettingsPageExtended.part2.feature
packages/e2e-tests/src/features/SettingsPagePopup.part2.feature

test(extension): unblock LW-12254 and LW-12255

---

packages/nami/src/ui/app/components/confirmModal.tsx

---
[LW-12673]: https://input-output.atlassian.net/browse/LW-12673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix on submit event handler in dapp popup for nami mode [lw-12673]

---

apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
apps/browser-extension-wallet/src/views/bitcoin-mode/features/multi-wallet/create-wallet/context.tsx

---
[LW-12638]: https://input-output.atlassian.net/browse/LW-12638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-12638] fix intermittent states during wallet creation

---

apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
apps/browser-extension-wallet/src/views/bitcoin-mode/features/multi-wallet/create-wallet/context.tsx

Reverts input-output-hk/lace#1839

Revert "fix: [lw-12638] fix intermittent states during wallet creation"

---

apps/browser-extension-wallet/src/dapp-connector.tsx

---
[LW-12709]: https://input-output.atlassian.net/browse/LW-12709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-12709] fix upgrade to lace from nami dapp

---

apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/SendFlow.tsx
apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/SendStepOne.tsx

fix: [lw-12707] add back btn into review step for btc send drawer

---

packages/e2e-tests/src/elements/AddressInput.ts
packages/e2e-tests/src/elements/settings/MessageSigningAllDoneDrawer.ts
packages/e2e-tests/src/features/MultiDelegationPageExtended.part1.feature
packages/e2e-tests/src/features/MultiDelegationPageExtended.part2.feature
packages/e2e-tests/src/steps/sendTransactionSimpleSteps.ts

test maintenance 29 Apr 2025

---

packages/bitcoin/src/wallet/lib/common/transaction.ts
packages/bitcoin/src/wallet/lib/providers/BlockchainInputResolver.ts
packages/bitcoin/test/BlockchainInputResolver.test.ts
packages/bitcoin/test/GreedyInputSelector.test.ts
packages/bitcoin/test/MaestroBitcoinDataProvider.test.ts

---
This PR adds more retroactive tests to Bitcoin package.

feat: add bitcoin package unit tests

---

.github/CODEOWNERS

feat: add bitcoin package to code owners file

---

packages/bitcoin/package.json
packages/bitcoin/src/wallet/lib/wallet/BitcoinWallet.ts
packages/bitcoin/test/BitcoinSigner.test.ts
packages/bitcoin/test/BitcoinWallet.test.ts
packages/bitcoin/test/TransactionBuilder.test.ts
yarn.lock

feat: add unit tests to bitcoin package

---

apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/SendFlow.module.scss
apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/SendFlow.tsx

---
Show confirmation drawer when canceling transaction in bitcoin-mode

fix: show confirmation drawer when canceling transaction in bitcoin-mode

---

apps/browser-extension-wallet/src/views/browser-view/features/sign-message/SignMessageDrawer.tsx
packages/common/src/ui/components/Form/TextArea/TextArea.tsx
packages/common/src/ui/components/Form/TextArea/__tests__/TextArea.test.tsx
packages/e2e-tests/src/elements/onboarding/SecureYourPaperWalletPage.ts
packages/e2e-tests/src/elements/settings/MessageSigningAllDoneDrawer.ts
packages/e2e-tests/src/elements/settings/SecureYourPaperWalletDrawer.ts

test(extension): fix paper wallet tests after recent UI toolkit update [LW-12796]

---

.github/workflows/e2e-tests-linux-split.yml
packages/e2e-tests/src/assert/stakingConfirmationScreenAssert.ts
packages/e2e-tests/src/assert/stakingPageAssert.ts
packages/e2e-tests/src/assert/topNavigationAssert.ts
packages/e2e-tests/src/elements/ForgotPasswordModal.ts
packages/e2e-tests/src/elements/Tooltip.ts
packages/e2e-tests/src/elements/WalletOption.ts
packages/e2e-tests/src/elements/glossaryPage.ts
packages/e2e-tests/src/elements/searchInput.ts
packages/e2e-tests/src/elements/sectionTitle.ts
packages/e2e-tests/src/elements/settings/YourKeysDrawer.ts
packages/e2e-tests/src/elements/staking/stakePoolDetails.ts
packages/e2e-tests/src/elements/tokenDetailsPage.ts
packages/e2e-tests/src/elements/walletUnlockPage.ts
packages/e2e-tests/src/features/SharedWalletOnboarding.feature
packages/e2e-tests/src/steps/menuHeaderSteps.ts
packages/e2e-tests/src/steps/navigationTopSteps.ts
packages/e2e-tests/src/steps/stakingSteps.ts

test(extension): maintenance 20 May 2025

---

apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
apps/browser-extension-wallet/src/hooks/__tests__/useWalletManager.test.tsx
apps/browser-extension-wallet/src/hooks/useWalletManager.ts

---
Current blockchain was still 'bitcoin' while adding/restoring new cardano wallet.
[LW-12781]: https://input-output.atlassian.net/browse/LW-12781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-12781] set proper blockchain on add/restore wallet

---

apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts
apps/browser-extension-wallet/src/views/bitcoin-mode/features/send/components/SendFlow.tsx

---
[LW-12550]: https://input-output.atlassian.net/browse/LW-12550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [lw-12550] add missing posthog events for btc wallet

---

.github/workflows/e2e-tests-linux-split.yml
packages/e2e-tests/src/features/OnboardingCreateWallet.part2.feature
packages/e2e-tests/src/features/e2e/MultidelegationSwitchingPoolsExtendedE2E.feature
packages/e2e-tests/src/steps/multidelegationSteps.ts
packages/e2e-tests/src/utils/window.ts

Restore missing Trezor flag in properties file, remove outdated tests

---

sonar-project.properties

---
Disable sonar code duplication checks (as requested)
N/A

chore: disable sonar code duplication checks [LW-12639]

---

packages/e2e-tests/src/assert/VotingCenterPageAssert.ts
packages/e2e-tests/src/assert/multidelegation/DelegateYourVotingPowerBannerAssert.ts
packages/e2e-tests/src/elements/VotingCenterPage.ts
packages/e2e-tests/src/elements/multidelegation/DelegateYourVotingPowerBanner.ts
packages/e2e-tests/src/features/MultidelegationDelegatedFundsMultiplePoolsNotRegisteredExtended.feature
packages/e2e-tests/src/features/MultidelegationDelegatedFundsMultiplePoolsNotRegisteredPopup.feature
packages/e2e-tests/src/features/TokensPageExtended.part1.feature
packages/e2e-tests/src/features/VotingCenterExtended.feature
packages/e2e-tests/src/features/VotingCenterPopup.feature
packages/e2e-tests/src/steps/VotingCenterSteps.ts
packages/e2e-tests/src/steps/commonSteps.ts
packages/e2e-tests/src/steps/multidelegationSteps.ts

test(extension): maintenance 16 Jun 2025

---

apps/browser-extension-wallet/.env.defaults
apps/browser-extension-wallet/.env.developerpreview
apps/browser-extension-wallet/.env.example
apps/browser-extension-wallet/src/lib/scripts/types/feature-flags.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/schema.ts
apps/browser-extension-wallet/src/views/browser-view/features/assets/components/MidnightEventBanner.tsx
apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsLayout.tsx
apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsWalletBase.tsx
packages/common/src/ui/components/Button/styles.module.scss

---
Move glacier drop learn more url to posthog feature flag payload

fix: move glacier drop learn more url to posthog feature flag payload

---

packages/e2e-tests/src/features/analytics/AnalyticsOnboardingEvents.feature
packages/e2e-tests/src/features/analytics/AnalyticsSettingsExtended.feature
packages/e2e-tests/src/steps/analyticsSteps.ts

test(extension): maintenance 23 June 2025

---

packages/e2e-tests/src/features/AdaHandleExtended.feature
packages/e2e-tests/src/features/AdaHandlePopup.feature

---
KoraLabs have fixed the issue on `preprod`.
Re-enabled tests disabled in a316b60ba .

test(extension): revert changes from a316b60ba

---

apps/browser-extension-wallet/src/views/bitcoin-mode/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx

---
[LW-13102]: https://input-output.atlassian.net/browse/LW-13102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: adjust copies for banxa banner for btc wallet [lw-13102]

---

apps/browser-extension-wallet/src/features/dapp/components/ConfirmData.tsx

---
Payment Address was shown instead of Drep Key in sign data popup;
Check Jira comments.
before
after
[LW-12712]: https://input-output.atlassian.net/browse/LW-12712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: show drep key in sign data popup [LW-12712]

---

packages/e2e-tests/src/assert/onboarding/onboardingMainPageAssert.ts
packages/e2e-tests/src/features/OnboardingCreateWallet.part1.feature
packages/e2e-tests/src/features/OnboardingCreateWallet.part2.feature
packages/e2e-tests/src/features/SettingsPageExtended.part1.feature
packages/e2e-tests/src/features/SettingsPagePopup.part2.feature

test: disable tests for legal links redirection due to LW-13195

---

packages/e2e-tests/src/features/SendTransactionBundlesExtended.part1.feature
packages/e2e-tests/src/features/SendTransactionSimpleExtended.part2.feature
packages/e2e-tests/src/features/SendTransactionSimplePopup.part2.feature

test: disable LW-3190, LW-3191 and LW-3192

---

packages/translation/src/lib/translations/browser-extension-wallet/en.json

fix: update tooltip [LW-13227]

---

packages/core/src/ui/components/Send/SendTransactionCost/SendTransactionCost.tsx
packages/e2e-tests/src/assert/drawerSendExtendedAssert.ts
packages/e2e-tests/src/elements/newTransaction/transactionNewPage.ts
packages/e2e-tests/src/features/SendTransactionBundlesExtended.part1.feature
packages/e2e-tests/src/features/SendTransactionSimpleExtended.part2.feature
packages/e2e-tests/src/features/SendTransactionSimplePopup.part2.feature
packages/e2e-tests/src/steps/sendTransactionBundleSteps.ts
packages/e2e-tests/src/steps/sendTransactionSimpleSteps.ts

test: unblock tests blocked by LW-13227

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json
apps/browser-extension-wallet/src/release-notes/1_25_0.tsx

https://input-output.atlassian.net/browse/LW-13261

chore: bump manifest v1.25.0

---

packages/cardano/src/wallet/lib/__tests__/stakePoolService.test.ts
packages/cardano/src/wallet/lib/stakePoolService.ts

---
If `queryStakePools` is called with specific id(s) while the system is still loading, perform direct calls to fetch all required data rather than waiting for the system init.
Tested the specific case and the calls performed by the system.

LW-13331 Fetch stake pool data directly when queried by id while still loading

---

packages/e2e-tests/src/features/SignMessage.feature

test: fix tests for signing messages

---

.github/workflows/ci.yml
.github/workflows/e2e-tests-linux-split.yml

ci: bump actions/download-artifact to v5

---

packages/e2e-tests/package.json
yarn.lock

chore: update Webdriver.io to v8.46.0

---

packages/e2e-tests/package.json
yarn.lock

chore: update Chai.js dependencies

---

packages/e2e-tests/README.md
packages/e2e-tests/package.json
packages/e2e-tests/src/assert/tokensPageAssert.ts
packages/e2e-tests/src/features/NetworkSwitchingExtended.feature
packages/e2e-tests/src/hooks/beforeTagHooks.ts
yarn.lock

test maintenance 2 Sep 2025

---

apps/browser-extension-wallet/manifest.json
apps/browser-extension-wallet/package.json
apps/browser-extension-wallet/src/release-notes/1_28_1.tsx

https://input-output.atlassian.net/browse/LW-13603?atlOrigin=eyJpIjoiODE2OTkwOTY3OThlNDFiM2I4YTQ5NzU1YWExYTFjYWIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ

chore: [LW-13603] bump manifest v1.28.1

---

apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/DropdownMenuOverlay.tsx
apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/AddNewMidnightWalletLink.tsx
apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
apps/browser-extension-wallet/src/hooks/__tests__/useWalletManager.test.tsx
apps/browser-extension-wallet/src/hooks/index.ts
apps/browser-extension-wallet/src/hooks/useLMP.ts
apps/browser-extension-wallet/src/hooks/useWalletManager.ts
apps/browser-extension-wallet/src/lib/scripts/background/index.ts
apps/browser-extension-wallet/src/lib/scripts/background/services/lmpService.ts
apps/browser-extension-wallet/src/lib/scripts/types/feature-flags.ts
apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/config.ts
apps/browser-extension-wallet/src/utils/lmp.ts
apps/browser-extension-wallet/src/views/browser-view/features/settings/components/Collateral/__tests__/CollateralDrawer.test.tsx
apps/browser-extension-wallet/src/views/browser-view/features/settings/components/__tests__/SettingsWallet.test.tsx
apps/browser-extension-wallet/webpack.common.js
apps/browser-extension-wallet/webpack.common.sw.js
packages/e2e-tests/README.md
packages/e2e-tests/src/utils/translationService.ts
packages/e2e-tests/wdio.conf.chrome.ts
packages/translation/src/lib/translations/browser-extension-wallet/en.json

This PR prepares `browser-extension-wallet` application for bundling it with LMP
---
See commits.
Existing build (without LMP) shouldn't have any functional changes. However it will load some additional code:
- export the service as global in SW (should be fine, just not used without the bundle)
- probably try to connect to remote api that doesn't exist (shouldn't cause any issues)

feat: lmp bundle integration [LW-13474]
